import datetime

canales = [
    {"id": "GH.MULTI", "n": "Multicámara", "t": "GH - Experiencia Multicámara", "d": "La casa más famosa del país vuelve a abrir sus puertas con una ambientación totalmente renovada, donde los participantes deberán sobreponerse al encierro y la convivencia para avanzar y quedarse con el tan anhelado premio.", "i": "https://i.postimg.cc/zGNBqNYG/GH-Generacion-Dorada.jpg", "g": "Reality"},
    {"id": "GH.24HS", "n": "Gran Hermano 24 hs.", "t": "Gran Hermano 24 hs.", "d": "La casa más famosa del país vuelve a abrir sus puertas con una ambientación totalmente renovada, donde los participantes deberán sobreponerse al encierro y la convivencia para avanzar y quedarse con el tan anhelado premio.", "i": "https://i.postimg.cc/zGNBqNYG/GH-Generacion-Dorada.jpg", "g": "Reality"},
    {"id": "GH.CAM1", "n": "Cámara 1", "t": "Gran Hermano - Cámara 1", "d": "La casa más famosa del país vuelve a abrir sus puertas con una ambientación totalmente renovada, donde los participantes deberán sobreponerse al encierro y la convivencia para avanzar y quedarse con el tan anhelado premio.", "i": "https://i.postimg.cc/zGNBqNYG/GH-Generacion-Dorada.jpg", "g": "Reality"},
    {"id": "GH.CAM2", "n": "Cámara 2", "t": "Gran Hermano - Cámara 2", "d": "La casa más famosa del país vuelve a abrir sus puertas con una ambientación totalmente renovada, donde los participantes deberán sobreponerse al encierro y la convivencia para avanzar y quedarse con el tan anhelado premio.", "i": "https://i.postimg.cc/zGNBqNYG/GH-Generacion-Dorada.jpg", "g": "Reality"},
    {"id": "GH.CAM3", "n": "Cámara 3", "t": "Gran Hermano - Cámara 3", "d": "La casa más famosa del país vuelve a abrir sus puertas con una ambientación totalmente renovada, donde los participantes deberán sobreponerse al encierro y la convivencia para avanzar y quedarse con el tan anhelado premio.", "i": "https://i.postimg.cc/zGNBqNYG/GH-Generacion-Dorada.jpg", "g": "Reality"},
    {"id": "Simpson", "n": "Los Simpson", "t": "Los Simpson", "g": "Comedia, Animación", "i": "https://s3.amazonaws.com/arc-wordpress-client-uploads/infobae-wp/wp-content/uploads/2017/04/17175732/mas-.jpg", "d": "Narra las vivencias de una peculiar familia norteamericana conformada por Homero, Marge, Bart, Lisa y Maggie Simpson."},
    {"id": "TRACE.UK", "n": "TRACE UK", "t": "TRACE UK", "g": "Música", "i": "https://cdn.broadbandtvnews.com/wp-content/uploads/2024/07/02103920/Trace-UK.jpg", "d": "TRACE UK brings viewers the very best of national and international artists, playing the hottest hip-hop, grime, afrobeats, rap and chart topping music videos."},
    {"id": "INFO.FLOW", "n": "FLOW", "t": "Comenzá a usar FLOW", "g": "Interés general", "i": "https://i.postimg.cc/NfmFhMVn/Flow.png", "d": "En Flow podés disfrutar de TV en vivo, películas, series, deportes, música y mucho más."},
    {"id": "Diputados.TV.ARG", "n": "Diputados TV", "t": "Diputados TV", "g": "Periodístico", "i": "https://i.postimg.cc/65nqs3gs/Diputados.png", "d": "Toda la información que concierte al trabajo de los Diputados de la Nación."},
    {"id": "Mix.TV", "n": "Mix TV", "t": "Mix TV", "g": "Interés general", "i": "https://i.postimg.cc/9FZ03MKC/Mix-TV.png", "d": "Entretenimiento sin pausa con realities, espectáculos, actualidad y contenidos que marcan tendencia."},
    {"id": "Lapacho.TV", "n": "Lapacho TV", "t": "Lapacho TV", "g": "Interés general", "i": "https://raw.githubusercontent.com/Puticastillo/EPGCL/main/zoidberg/fallback.jpg", "d": "La pantalla que refleja la identidad formoseña. Información local, cultura y actualidad."},
    {"id": "Telesol.San.Juan", "n": "Telesol", "t": "Telesol", "g": "Interés general", "i": "https://i.ytimg.com/vi/BbJo6A888a4/maxresdefault.jpg", "d": "Toda la actualidad sanjuanina en un solo lugar. Noticias y producción local."},
    {"id": "Claro.Sports.2", "n": "Claro Sports 2", "t": "Claro Sports 2", "g": "Deportes", "i": "https://cdn.amxinfra.com/clarosports/images/2024/08/paralimpicos-cs2-133315.jpg", "d": "Más acción, más competencia y más deporte en vivo. Cobertura de torneos internacionales."},
    {"id": "Sky.Sports.Mexico", "n": "Sky Sports", "t": "Sky Sports", "g": "Deportes", "i": "https://i.postimg.cc/Y2hZk9kp/Sky-Sports.png", "d": "¡Vive tu pasión por los deportes con Sky Sports! Las mejores ligas del mundo, fútbol europeo de primer nivel y grandes competencias internacionales con cobertura especializada."},
    {"id": "FOX.ONE", "n": "FOX One", "t": "FOX One", "g": "Deportes", "i": "https://i.postimg.cc/kGNRbC8x/FOX-One.jpg", "d": "Vive la pasión del deporte en FOX One, el canal donde laten las grandes competencias del mundo. Disfruta la intensidad de la Premier League, la emoción incomparable de la UEFA Champions League y los torneos más destacados del calendario internacional. Partidos en vivo, análisis experto y toda la adrenalina del fútbol de élite, en un solo lugar."},
    {"id": "DSports.Uruguay", "n": "DSports Uruguay", "t": "DSports Uruguay", "g": "Deportes", "i": "https://i.postimg.cc/13StyS19/DSports-Uruguay.png", "d": "La señal deportiva con foco en Uruguay. Fútbol local e internacional, competiciones destacadas y cobertura en vivo con análisis y producción especializada."},
    {"id": "DSports.Uruguay.Premium", "n": "DSports Uruguay Premium", "t": "DSports Uruguay Premium", "g": "Deportes", "i": "https://i.postimg.cc/3xhR3hQ3/DSports-Uruguay-Premium.png", "d": "La experiencia deportiva más completa. Partidos exclusivos, eventos premium y la mejor cobertura en vivo del deporte uruguayo e internacional."},
    {"id": "FIFA.PLUS.ESP", "n": "FIFA+ en español", "t": "FIFA+ en español", "g": "Deportes", "i": "https://i.postimg.cc/qBn6rj6Q/FIFA.png", "d": "Partidos históricos, documentales, series originales y contenido exclusivo del mundo del fútbol, las 24 horas y en español."},
    {"id": "HBO.Boxing", "n": "HBO Boxing", "t": "HBO Boxing by WBTV", "g": "Boxeo", "i": "https://canvas-lb.tubitv.com/opts/lweaVPhEK4ZaUw==/c68711a9-7ca5-4153-a288-00b76afc4372/CPwDEJ0COgUxLjEuOA==", "d": "The home of elite boxing. World-class fighters, iconic matchups and unforgettable championship nights."},
    {"id": "Rally.TV", "n": "Rally TV", "t": "Rally TV", "g": "Automovilismo", "i": "https://i.postimg.cc/ncKJ8gV9/Rally-TV.png", "d": "El canal dedicado al mundo del rally. Cobertura en vivo, etapas completas, resúmenes y toda la emoción del automovilismo off-road internacional."},
    {"id": "Cazé.TV", "n": "Cazé TV", "t": "Cazé TV", "g": "Deportes", "i": "https://mir-s3-cdn-cf.behance.net/projects/404/f02c5b206996309.Y3JvcCw4MTAsNjMzLDAsMA.png", "d": "Esporte com leveza, informação e mucha resenha. Transmissões vibrantes e convidados especiais."},
    {"id": "Tigo.Sports.2.PY", "n": "Tigo Sports 2", "t": "Tigo Sports 2", "g": "Deportes", "i": "https://raw.githubusercontent.com/Puticastillo/EPGCL/main/zoidberg/fallback.jpg", "d": "Viví la emoción del deporte como si estuvieras en la cancha. Toda la pasión de los hinchas."},
    {"id": "Flow.Sports.1", "n": "Flow Sports", "t": "Flow Sports", "g": "Deportes", "i": "https://i.postimg.cc/T2Z1Hmkk/Flow-Sports.png", "d": "Viví la pasión del deporte como si estuvieras ahí. Adrenalina y emoción en primera fila."},
    {"id": "Flow.Sports.2", "n": "Flow Sports 2", "t": "Flow Sports 2", "g": "Deportes", "i": "https://i.postimg.cc/7PphQ7Bs/Flow-Sports-2.png", "d": "Viví la pasión del deporte como si estuvieras ahí. Adrenalina y emoción en primera fila."},
    {"id": "Flow.Sports.3", "n": "Flow Sports 3", "t": "Flow Sports 3", "g": "Deportes", "i": "https://i.postimg.cc/J4Z0wnvW/Flow-Sports-3.png", "d": "Viví la pasión del deporte como si estuvieras ahí. Adrenalina y emoción en primera fila."},
    {"id": "DM.Kids.TV", "n": "DM Kids TV", "t": "DM Kids TV", "g": "Infantil", "i": "https://i.ytimg.cc/vi/JMbngwxZqZU/maxresdefault.jpg", "d": "Diversión, imaginación y aventuras. Series animadas y contenidos para aprender jugando."},
    {"id": "ENTFamily.40mediaGroup", "n": "#ENTFamily", "t": "#ENTFamily", "g": "Películas", "i": "https://i.postimg.cc/q7RQLhDm/ENT-Family.png", "d": "Contenido familiar para toda la familia. Diversión y entretenimiento seguro las 24 horas."},
    {"id": "ENTMain.40mediaGroup", "n": "#ENTChannel", "t": "#ENTChannel", "g": "Películas", "i": "https://i.postimg.cc/W43SnFYy/ENT-Channel.png", "d": "El equilibrio perfecto de las películas y las series que marcaron generaciones."},
    {"id": "TMC.40mediaGroup", "n": "#Totalmusic", "t": "#Totalmusic", "g": "Música", "i": "https://i.postimg.cc/TPwQ9LNC/Totalmusic.png", "d": "La más amplia selección de videoclips de todos los géneros y épocas."},
    {"id": "TMC80s.40mediaGroup", "n": "#Totalmusic80s", "t": "#Totalmusic80s", "g": "Música", "i": "https://raw.githubusercontent.com/Puticastillo/EPGCL/main/zoidberg/fallback.jpg", "d": "La más variada selección de videoclips de la década dorada de la música."},
    {"id": "TMC2000s.40mediaGroup", "n": "#Totalmusic2000s", "t": "#Totalmusic2000s", "g": "Música", "i": "https://raw.githubusercontent.com/Puticastillo/EPGCL/main/zoidberg/fallback.jpg", "d": "Una cuidada selección de videoclips que marcaron los años 2000."},
    {"id": "TMCConcerts.40mediaGroup", "n": "#TotalmusicConcerts", "t": "#TotalmusicConcerts", "g": "Música", "i": "https://raw.githubusercontent.com/Puticastillo/EPGCL/main/zoidberg/fallback.jpg", "d": "Selección de conciertos en vivo inolvidables de actuaciones legendarias."},
    {"id": "TMCDance.40mediaGroup", "n": "#TotalmusicDance", "t": "#TotalmusicDance", "g": "Música", "i": "https://raw.githubusercontent.com/Puticastillo/EPGCL/main/zoidberg/fallback.jpg", "d": "Selección vibrante de videoclips de música electrónica y dance."},
    {"id": "West.TV.PE", "n": "West TV", "t": "West TV", "g": "Películas", "i": "https://i.postimg.cc/C5MT6DLp/West.png", "d": "Un clásico espacio dedicado al cine del Lejano Oeste. Duelos, sheriffs y forajidos."},
    {"id": "Caras.TV", "n": "Caras TV", "t": "Caras TV", "g": "Interés general", "i": "https://media.canalnet.tv/2024/05/CYaZv3N-1157x720.jpg", "d": "La vida de los famosos, el glamour y las historias que todos comentan."},
    {"id": "El.Mueble", "n": "El Mueble", "t": "El Mueble", "g": "Interés general", "i": "https://raw.githubusercontent.com/Puticastillo/EPGCL/main/zoidberg/fallback.jpg", "d": "Inspiración, diseño y decoración. Ideas y tendencias para transformar tu hogar."},
    {"id": "Aunar", "n": "Aunar", "t": "Aunar", "g": "Cultura", "i": "https://raw.githubusercontent.com/Puticastillo/EPGCL/main/zoidberg/fallback.jpg", "d": "Cultura, sociedad y contenidos que inspiran. Historias y perspectivas del mundo."},
    {"id": "Horizons.Wild", "n": "Horizons.Wild", "t": "Horizons.Wild", "g": "Naturaleza", "i": "https://i.pinimg.com/736x/e6/a5/40/e6a540fd812d99d1d3d4584c080b9e92.jpg", "d": "Explorá la naturaleza en su estado más puro. Documentales de fauna y paisajes."},
    {"id": "Viajar", "n": "Viajar", "t": "Viajar", "g": "Viajes", "i": "https://i.postimg.cc/vTWp8p52/Viajar.png", "d": "Descubrí destinos, culturas y aventuras sin moverte de tu sillón."},
    {"id": "Flow.Music.1", "n": "Flow Music", "t": "Flow Music", "g": "Música", "i": "https://i.postimg.cc/28hyp6Mz/Flow-Music.png", "d": "La música la vivís en Flow. Shows en vivo y mucho más."},
    {"id": "Flow.Music.2", "n": "Flow Music 2", "t": "Flow Music 2", "g": "Música", "i": "https://i.postimg.cc/28hyp6Mz/Flow-Music.png", "d": "La música la vivís en Flow. Shows en vivo y mucho más."},
    {"id": "Flow.Music.3", "n": "Flow Music 3", "t": "Flow Music 3", "g": "Música", "i": "https://i.postimg.cc/28hyp6Mz/Flow-Music.png", "d": "La música la vivís en Flow. Shows en vivo y mucho más."},
    {"id": "Flow.Music.4", "n": "Flow Music 4", "t": "Flow Music 4", "g": "Música", "i": "https://i.postimg.cc/28hyp6Mz/Flow-Music.png", "d": "La música la vivís en Flow. Shows en vivo y mucho más."},
    {"id": "Billboard.AR", "n": "Billboard", "t": "Billboard", "g": "Música", "i": "https://i.postimg.cc/x1QC9QVn/Billboard.png", "d": "Lo último en música, charts y artistas que marcan tendencia."},
    {"id": "Deluxe.Music.Wintertime", "n": "Deluxe Music Wintertime", "t": "Deluxe Music Wintertime", "g": "Música", "i": "https://raw.githubusercontent.com/Puticastillo/EPGCL/main/zoidberg/fallback.jpg", "d": "Selección especial de música para disfrutar en invierno. Hits y baladas."},
    {"id": "El.Folclorico", "n": "El Folclórico", "t": "El Folclórico", "g": "Música", "i": "https://raw.githubusercontent.com/Puticastillo/EPGCL/main/zoidberg/fallback.jpg", "d": "Raíces, tradición y la esencia del folclore en cada nota. Música y danza."},
    {"id": "Hit.TV", "n": "Hit TV", "t": "Hit TV", "g": "Música", "i": "https://raw.githubusercontent.com/Puticastillo/EPGCL/main/zoidberg/fallback.jpg", "d": "Los éxitos musicales más sonados en un solo canal. Videos y listas."},
    {"id": "FMH.Kizzi", "n": "FMH Kizzi", "t": "FMH Kizzi", "g": "Música", "i": "https://raw.githubusercontent.com/Puticastillo/EPGCL/main/zoidberg/fallback.jpg", "d": "Ritmo, frescura y los mejores lanzamientos musicales actuales."},
    {"id": "Music.Box.Classic", "n": "Music Box Classic", "t": "Music Box Classic", "g": "Music", "i": "https://www.digitalfernsehen.de/wp-content/uploads/2025/12/Music-Box-Classic.jpg", "d": "Travel back in time with the greatest classics. Timeless hits and unforgettable melodies that never lose their charm."},
    {"id": "Music.Box.Dance", "n": "Music Box Dance", "t": "Music Box Dance", "g": "Music", "i": "https://www.digitalfernsehen.de/wp-content/uploads/2025/12/Music-Box-Dance.jpg", "d": "Get up and move with nonstop beats. Electronic, house, and dance tracks to keep your energy high."},
    {"id": "Music.Box.Hits", "n": "Music Box Hits", "t": "Music Box Hits", "g": "Music", "i": "https://www.digitalfernsehen.de/wp-content/uploads/2025/12/Music-Box-Hits.jpg", "d": "The hottest songs of the moment, from international chart-toppers to local favorites. Always fresh, always trending."},
    {"id": "Music.Box.Sexy", "n": "Music Box Sexy", "t": "Music Box Sexy", "g": "Music", "i": "https://www.parabola.cz/img_magazin/2025/music-box-sexy.jpg", "d": "Set the mood with smooth and sultry tunes. Lounge, R&B, and seductive rhythms to unwind or flirt."},
    {"id": "Musictop", "n": "MusicTop", "t": "MusicTop", "g": "Música", "i": "https://raw.githubusercontent.com/Puticastillo/EPGCL/main/zoidberg/fallback.jpg", "d": "Top charts y éxitos globales. Videos, rankings y artistas dominantes."},
    {"id": "Thats.70s", "n": "That's 70s", "t": "That's 70s", "g": "Música", "i": "https://i.postimg.cc/2j09ZVkC/70s-MINI.png", "d": "Relive the magic of the 1970s with a curated selection of disco, funk, and classic rock. From dancefloor anthems to acoustic masterpieces, this channel celebrates the decade of soul and style."},
    {"id": "Thats.80s", "n": "That's 80s", "t": "That's 80s", "g": "Música", "i": "https://i.postimg.cc/0jXtRHW0/80MINI.png", "d": "Step into the neon world of the 1980s. A non-stop journey through the biggest synth-pop hits, new wave classics, and hair metal ballads that defined a generation of music and culture."},
    {"id": "Thats.90s.00s", "n": "That's 90s & 00s", "t": "That's 90s & 00s", "g": "Música", "i": "https://i.postimg.cc/hjgZ9mQz/90s00s-MINI.png", "d": "Experience the evolution of sound across two powerful decades. Featuring the grunge and pop-punk explosion of the 90s alongside the iconic R&B, pop, and indie hits that dominated the early 2000s."},
    {"id": "Thats.Rock", "n": "That's Rock", "t": "That's Rock", "g": "Música", "i": "https://i.postimg.cc/3JWSCYNb/ROCKMINI.png", "d": "Turn up the volume for the ultimate rock experience. From legendary arena rock anthems to hard-hitting riffs, we bring you the most influential bands and the greatest electric guitar moments of all time."},
    {"id": "Vorterix", "n": "Vorterix", "t": "Vorterix", "g": "Música", "i": "https://i.postimg.cc/1zqMZDG2/Vorterix.png", "d": "Pionero como medio de streaming sumado a la frecuencia FM."},
    {"id": "Radio.Maria", "n": "Radio María", "t": "Radio María", "g": "Religión", "i": "https://raw.githubusercontent.com/Puticastillo/EPGCL/main/zoidberg/fallback.jpg", "d": "Espiritualidad, oración y música religiosa para acompañar tu fe."},
    {"id": "Santa.Maria", "n": "Santa María", "t": "Santa María", "g": "Religión", "i": "https://raw.githubusercontent.com/Puticastillo/EPGCL/main/zoidberg/fallback.jpg", "d": "Contenido religioso y formación espiritual con reflexiones para el hogar."},
    {"id": "Solidaria.TV", "n": "Solidaria TV", "t": "Solidaria TV", "g": "Religión", "i": "https://raw.githubusercontent.com/Puticastillo/EPGCL/main/zoidberg/fallback.jpg", "d": "Historias de ayuda, solidaridad y compromiso social inspirador."},
    {"id": "Latam.Rural", "n": "Latam Rural", "t": "Latam Rural", "g": "Agro", "i": "https://raw.githubusercontent.com/Puticastillo/EPGCL/main/zoidberg/fallback.jpg", "d": "Todo el mundo agro en un solo lugar. Noticias, producción y tecnología."},
    {"id": "BBB.MULTI", "n": "Big Brother Brasil - Multicâmera", "t": "Big Brother Brasil - Multicâmera", "g": "Reality", "i": "https://dominiopop.com.br/wp-content/uploads/2025/12/logo-bbb.jpg", "d": "Acompanhe cada momento como se você estivesse dentro da casa em tempo real."},
    {"id": "BBB.CAM1", "n": "Big Brother Brasil - Câmera 1", "t": "BBB - Câmera 1", "g": "Reality", "i": "https://dominiopop.com.br/wp-content/uploads/2025/12/logo-bbb.jpg", "d": "Acompanhe cada momento como se você estivesse dentro da casa em tempo real."},
    {"id": "BBB.CAM2", "n": "Big Brother Brasil - Câmera 2", "t": "BBB - Câmera 2", "g": "Reality", "i": "https://dominiopop.com.br/wp-content/uploads/2025/12/logo-bbb.jpg", "d": "Acompanhe cada momento como se você estivesse dentro da casa em tempo real."},
    {"id": "VTV.URUGUAY", "n": "VTV", "t": "VTV", "g": "Interés general", "i": "https://i.postimg.cc/Y0Sncxc9/vtv.jpg", "d": "Noticias, actualidad y cobertura completa de Uruguay y el mundo."},
    {"id": "Noticias.Caracol", "n": "Noticias Caracol", "t": "Noticias Caracol", "g": "Noticias", "i": "https://i.postimg.cc/HxLYNfLz/image.png", "d": "La información que necesitás con análisis y reportajes importantes."},
    # Stingray Music
    {"id": "Stingray.Big.Band", "n": "Big Band", "t": "Big Band", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Viaja a la era dorada de las grandes orquestas. Disfruta del swing vibrante, las secciones de metales impecables y el glamour de los salones de baile con las legendarias big bands que definieron una generación. Energía, elegancia y ritmo en su máxima expresión."},
    {"id": "Stingray.Clasicos.del.Dance", "n": "Clásicos del Dance", "t": "Clásicos del Dance", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Revive la energía de la pista con los himnos dance que marcaron época. Desde los primeros beats electrónicos hasta los éxitos que dominaron clubes y festivales, este canal reúne los clásicos que siguen haciendo vibrar generaciones."},
    {"id": "Stingray.Clasicos.del.Soul.y.el.Rhythm.and.Blues", "n": "Clásicos del Soul y el Rhythm and Blues", "t": "Clásicos del Soul y el Rhythm and Blues", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Sumérgete en la pasión y la intensidad del soul y el R&B clásico. Voces inolvidables, secciones de viento poderosas y canciones que dieron forma a la historia de la música popular. Sentimiento puro en cada nota."},
    {"id": "Stingray.Clasicos.Indie", "n": "Clásicos Indie", "t": "Clásicos Indie", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Descubre los himnos alternativos que definieron la escena independiente. Guitarras distintivas, letras auténticas y sonidos que marcaron tendencia fuera del circuito comercial. La esencia del espíritu indie en su mejor momento."},
    {"id": "Stingray.Club.de.Baile", "n": "Club de Baile", "t": "Club de Baile", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Quédate en casa y deja que el club venga hacia ti. Revive el ritmo y la energía de la escena musical de Nueva York, Londres, Miami Beach o Ibiza, con los éxitos house, techno y trance. No te podrás estar quieto con los programadores de Stingray Music tras los tornamesas. Si buscas algo relajante, intenta otro canal de Stingray Music, porque en Club de Baile, ¡el objetivo es no parar de bailar!"},
    {"id": "Stingray.Deep.Blues", "n": "Deep Blues", "t": "Deep Blues", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Explora las raíces más profundas del blues. Guitarras intensas, voces rasgadas y emociones crudas que cuentan historias de vida, amor y carretera. Un viaje auténtico al corazón del género."},
    {"id": "Stingray.Estandares", "n": "Estándares", "t": "Estándares", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Viaja a aquel tiempo, justo antes del Rock & Roll. Escucha la música de las grandes bandas y las estrellas de esa era. Entonces el Jazz y el Pop eran uno y las estrellas de la radio también eran la sensación en la pista de baile. Los primeros tiempos de Frank Sinatra y The Andrew Sisters, junto a las big bands de Glenn Miller, Duke Ellington, Artie Shaw, Benny Goodman y muchos más."},
    {"id": "Stingray.Euro.Hits", "n": "Euro Hits", "t": "Euro Hits", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Disfruta los éxitos más recientes del panorama musical europeo. Este canal combina una amplia gama de estilos de música compilados de las listas más importantes de las ciudades europeas. Disfruta de un canal reluciente de los mejores artistas de todo el mundo."},
    {"id": "Stingray.Exitos.de.Brasil", "n": "Éxitos de Brasil", "t": "Éxitos de Brasil", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Siente la alegría y el ritmo de Brasil con los éxitos más representativos del país. Samba, pagode, pop brasileño y mucho más en una selección vibrante y llena de energía contagiosa."},
    {"id": "Stingray.Exitos.de.Italia", "n": "Éxitos de Italia", "t": "Éxitos de Italia", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Disfruta de las canciones que dominan las listas italianas. Baladas apasionadas, pop contemporáneo y los sonidos más actuales que marcan tendencia en Italia."},
    {"id": "Stingray.Exitos.de.las.Americas", "n": "Éxitos de las Américas", "t": "Éxitos de las Américas", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Un recorrido musical por el continente americano con los éxitos más destacados del norte, centro y sur. Una mezcla dinámica de estilos que refleja la diversidad cultural de las Américas."},
    {"id": "Stingray.Exitos.del.Momento", "n": "Éxitos del Momento", "t": "Éxitos del Momento", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Lo mejor de los artistas emergentes del pop latino. Una mezcla de ritmos como la salsa, la samba, el merengue, el flamenco, el tango, reggaetón y el reggae. El panorama de la música latina actual en continua evolución. Con artistas como Shakira, Nelly Furtado, Alejandro Fernández, Aventura."},
    {"id": "Stingray.Exitos.Recientes", "n": "Éxitos Recientes", "t": "Éxitos Recientes", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Obtén lo último y lo mejor de los éxitos del momento. Olvídate de los anuncios y la charla. La lista de Éxitos Recientes tiene solo lo bueno. Aquí podrás encontrar los éxitos de hoy, y los de mañana. ¡Así es, sabemos lo que será un éxito con anticipación!"},
    {"id": "Stingray.Exitos.Tropicales", "n": "Éxitos Tropicales", "t": "Éxitos Tropicales", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "El feeling veraniego de lo más actual de la Salsa, la Rumba y los éxitos tropicales. No podrás quedarte quieto con el latido y vibrar más latinos. ¡Escúchalo incluso cuando aún no llega el verano! Familiar y exótico."},
    {"id": "Stingray.Fiesta.Continua", "n": "Fiesta Continua", "t": "Fiesta Continua", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "No esperes al fin de semana, puede ser tu noche siempre que quieras. Si puedes cantar como una estrella delante del espejo, estarás en casa escuchando Fiesta Continua."},
    {"id": "Stingray.Himnos.del.Rock", "n": "Himnos del Rock", "t": "Himnos del Rock", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Sube el volumen con los himnos que definieron generaciones. Guitarras poderosas, coros inolvidables y canciones que siguen encendiendo estadios alrededor del mundo."},
    {"id": "Stingray.Jammin.Reggae", "n": "Jammin' Reggae", "t": "Jammin' Reggae", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Ven a Jamaica a explorar las raíces y ramificaciones de diversos estilos de reggae y otras músicas de la isla. Con esta mezcla de sonidos y fuertes ritmos de leyendas del pasado y las estrellas actuales, seguro de que te mueves... Bob Marley, Peter Tosh y Jimmy Cliff siguen siendo la base de esta fascinante forma de pop de la isla."},
    {"id": "Stingray.Latin.Lounge", "n": "Latin Lounge", "t": "Latin Lounge", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Disfruta de los sofisticados sonidos y el ambiente relajado que crea este canal mientras celebras los placeres de la vida. Ponte cómodo y únete a la fiesta."},
    {"id": "Stingray.Mariachi.y.Ranchera", "n": "Mariachi y Ranchera", "t": "Mariachi y Ranchera", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Celebra la tradición mexicana con lo mejor del mariachi y la ranchera. Voces apasionadas, trompetas vibrantes y canciones que honran el amor, la tierra y las costumbres."},
    {"id": "Stingray.Musica.del.Mundo", "n": "Música del Mundo", "t": "Música del Mundo", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Explora sonidos y tradiciones de todos los rincones del planeta. Un mosaico musical que celebra la diversidad cultural a través de ritmos, instrumentos y estilos únicos."},
    {"id": "Stingray.Musica.Ligera", "n": "Música Ligera", "t": "Música Ligera", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Para algunas melodías ligeras, relajantes y  alegres, sintoniza lo mejor de la música de ambiente. Las melodías aquí son en su mayoría instrumentales, pero que no te sorprenda encontrar ocasionalmente esa canción atemporal con voces suaves, solo para añadirle variedad a este popular canal. Sintoniza este canal y déjalo todo el día para crear un ambiente de recuerdos y sonidos relajantes. Está concebido para satisfacer una gran variedad de gustos y para la gente que disfruta simplemente de la música ligera."},
    {"id": "Stingray.New.Age", "n": "New Age", "t": "New Age", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Déjate llevar por paisajes sonoros envolventes y atmósferas serenas. Perfecto para la meditación, la concentración o simplemente para desconectar del mundo exterior."},
    # Radios y Música
    {"id": "Radios.y.Musica.Top.40", "n": "Top 40", "t": "Top 40", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Los 40 éxitos más sonados del momento reunidos en un solo canal. Pop, urbano, dance y los temas que dominan las listas internacionales. Actual, dinámico y siempre en tendencia."},
    {"id": "Radios.y.Musica.Top.Europa", "n": "Top Europa", "t": "Top Europa", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Descubre lo que está marcando el ritmo en las principales capitales europeas. Una selección vibrante con los artistas y sonidos que dominan el continente."},
    {"id": "Radios.y.Musica.Nuevos.Clasicos", "n": "Nuevos Clásicos", "t": "Nuevos Clásicos", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Las canciones que ya se sienten eternas. Éxitos de los últimos años que se han convertido en imprescindibles y que siguen conquistando nuevas generaciones."},
    {"id": "Radios.y.Musica.80.Internacional", "n": "80 Internacional", "t": "80 Internacional", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Revive la década dorada del pop y el rock internacional. Sintetizadores, himnos inolvidables y la energía que definió los años 80."},
    {"id": "Radios.y.Musica.90.Internacional", "n": "90 Internacional", "t": "90 Internacional", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "El sonido que marcó una generación. Pop, rock alternativo, dance y baladas que dominaron el mundo en los inolvidables años 90."},
    {"id": "Radios.y.Musica.80.90.Internacional", "n": "80/90 Internacional", "t": "80/90 Internacional", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Una combinación explosiva de los mejores éxitos de los 80 y 90. Dos décadas icónicas reunidas en un solo canal para no dejar de cantar."},
    {"id": "Radios.y.Musica.70.Internacional", "n": "70 Internacional", "t": "70 Internacional", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "El espíritu libre de los años 70 en su máxima expresión. Rock clásico, disco, funk y baladas que marcaron el inicio de una revolución musical."},
    {"id": "Radios.y.Musica.60.Internacional", "n": "60 Internacional", "t": "60 Internacional", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Los orígenes del pop y el rock moderno. Un viaje a los años 60 con melodías que cambiaron la historia de la música."},
    {"id": "Radios.y.Musica.50.Internacional", "n": "50 Internacional", "t": "50 Internacional", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "La década que dio vida al rock & roll. Ritmos contagiosos, voces legendarias y canciones que sentaron las bases de todo lo que vino después."},
    {"id": "Radios.y.Musica.Grandes.Voces", "n": "Grandes Voces", "t": "Grandes Voces", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Interpretaciones inolvidables de las voces más impactantes de la música. Potencia, emoción y talento en cada canción."},
    {"id": "Radios.y.Musica.Ellos", "n": "Ellos", "t": "Ellos", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Una selección dedicada a las voces masculinas que han marcado historia. Baladas, pop, rock y éxitos interpretados por grandes artistas."},
    {"id": "Radios.y.Musica.Ellas", "n": "Ellas", "t": "Ellas", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Celebrando el talento femenino en la música. Voces poderosas, sensibilidad y éxitos que han dejado huella en distintas generaciones."},
    {"id": "Radios.y.Musica.Vivo", "n": "Vivo", "t": "Vivo", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "La emoción del escenario en directo. Presentaciones memorables, energía pura y la magia irrepetible de la música en vivo."},
    {"id": "Radios.y.Musica.Disco", "n": "Disco", "t": "Disco", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Brillos, pistas iluminadas y ritmos irresistibles. Los clásicos disco que siguen haciendo bailar generación tras generación."},
    {"id": "Radios.y.Musica.New.Party", "n": "New Party", "t": "New Party", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "La banda sonora perfecta para tu fiesta. Hits actuales, energía alta y ritmos que garantizan que nadie se quede sentado."},
    {"id": "Radios.y.Musica.Retro.Mix", "n": "Retro Mix", "t": "Retro Mix", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Una mezcla irresistible de éxitos retro de distintas décadas. Canciones que despiertan recuerdos y nunca pasan de moda."},
    {"id": "Radios.y.Musica.Rock.Nacional", "n": "Rock Nacional", "t": "Rock Nacional", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "El sonido que define generaciones dentro del país. Guitarras potentes, letras que conectan y clásicos del rock en nuestro idioma."},
    {"id": "Radios.y.Musica.Grandes.del.Rock", "n": "Grandes del Rock", "t": "Grandes del Rock", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Las leyendas que hicieron del rock un movimiento eterno. Himnos inolvidables y bandas que marcaron la historia."},
    {"id": "Radios.y.Musica.Heavy.Metal", "n": "Heavy Metal", "t": "Heavy Metal", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Riffs intensos, baterías demoledoras y pura adrenalina. El canal para los amantes del metal en todas sus vertientes."},
    {"id": "Radios.y.Musica.Rock.Alternativo", "n": "Rock Alternativo", "t": "Rock Alternativo", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Sonidos innovadores y propuestas que rompieron esquemas. Lo mejor del rock alternativo que desafió lo convencional."},
    {"id": "Radios.y.Musica.Power.Ballads", "n": "Power Ballads", "t": "Power Ballads", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Baladas intensas que combinan fuerza y emoción. Canciones épicas que comienzan suaves y explotan en estribillos inolvidables."},
    {"id": "Radios.y.Musica.New.Wave", "n": "New Wave", "t": "New Wave", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Sintetizadores, actitud y estética inconfundible. El movimiento que redefinió el pop y el rock a finales de los 70 y 80."},
    {"id": "Radios.y.Musica.Reggae", "n": "Reggae", "t": "Reggae", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Ritmos relajados y vibraciones positivas. El sonido jamaicano que conquistó el mundo con su mensaje y su groove inconfundible."},
    {"id": "Radios.y.Musica.Peliculas", "n": "Películas", "t": "Películas", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Las canciones que dieron vida a grandes historias en la pantalla. Bandas sonoras y temas inolvidables del cine."},
    {"id": "Radios.y.Musica.Classic.Cinema", "n": "Classic Cinema", "t": "Classic Cinema", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Un recorrido por las composiciones más emblemáticas del cine clásico. Melodías que evocan escenas eternas y emociones profundas."},
    {"id": "Radios.y.Musica.Romanticas", "n": "Románticas", "t": "Románticas", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Las canciones que hablan directo al corazón. Baladas inolvidables y éxitos románticos ideales para dedicar, recordar y sentir cada palabra."},
    {"id": "Radios.y.Musica.Lentos", "n": "Lentos", "t": "Lentos", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Baja la intensidad y déjate llevar por melodías suaves y envolventes. Perfecto para momentos tranquilos y noches especiales."},
    {"id": "Radios.y.Musica.Teens", "n": "Teens", "t": "Teens", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "El sonido que marca tendencia entre las nuevas generaciones. Pop fresco, urbano actual y los artistas favoritos del momento."},
    {"id": "Radios.y.Musica.Reggaeton", "n": "Reggaeton", "t": "Reggaeton", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Ritmo urbano que domina las pistas y las listas globales. Beats contagiosos y los éxitos más fuertes del género."},
    {"id": "Radios.y.Musica.Reggaeton.Romantico", "n": "Reggaeton Romántico", "t": "Reggaeton Romántico", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "La fusión perfecta entre ritmo urbano y letras de amor. Canciones intensas para dedicar y sentir sin dejar de moverte."},
    {"id": "Radios.y.Musica.Latinos", "n": "Latinos", "t": "Latinos", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Una celebración de los sonidos que hacen vibrar a Latinoamérica. Pop latino, urbano, tropical y mucho más en un solo canal."},
    {"id": "Radios.y.Musica.Letras.y.Canciones", "n": "Letras y Canciones", "t": "Letras y Canciones", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Para quienes disfrutan cada verso y cada historia. Canciones con contenido, emoción y letras que dejan huella."},
    {"id": "Radios.y.Musica.Salsa", "n": "Salsa", "t": "Salsa", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Sabor, ritmo y pura cadencia caribeña. Los clásicos y éxitos actuales de la salsa para no dejar de bailar."},
    {"id": "Radios.y.Musica.MPB", "n": "MPB", "t": "MPB", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Lo mejor de la Música Popular Brasileña. Elegancia, poesía y sonidos que representan la esencia musical de Brasil."},
    {"id": "Radios.y.Musica.Bossa", "n": "Bossa", "t": "Bossa", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "La suavidad y sofisticación de la bossa nova. Guitarras delicadas y melodías que evocan playas y atardeceres."},
    {"id": "Radios.y.Musica.Axe", "n": "Axe", "t": "Axe", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Energía brasileña en su máxima expresión. Ritmos festivos y contagiosos que invitan a celebrar sin parar."},
    {"id": "Radios.y.Musica.Jazz", "n": "Jazz", "t": "Jazz", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Improvisación, elegancia y tradición. Un recorrido por los grandes estándares y las figuras esenciales del jazz."},
    {"id": "Radios.y.Musica.Smooth.Jazz", "n": "Smooth Jazz", "t": "Smooth Jazz", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Sonidos suaves y contemporáneos que combinan jazz con toques modernos. Ideal para ambientes relajados y sofisticados."},
    {"id": "Radios.y.Musica.Chill.Out", "n": "Chill Out", "t": "Chill Out", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Ambientes relajantes y atmósferas envolventes. Perfecto para desconectar, trabajar o simplemente dejarse llevar."},
    {"id": "Radios.y.Musica.Chill.Africa", "n": "Chill Africa", "t": "Chill Africa", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Fusión de sonidos africanos con vibras chill. Ritmos orgánicos y paisajes sonoros llenos de identidad y calma."},
    {"id": "Radios.y.Musica.Electronica", "n": "Electrónica", "t": "Electrónica", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Beats modernos y producción de vanguardia. Desde el house hasta el techno, la electrónica en todas sus formas."},
    {"id": "Radios.y.Musica.Trendy", "n": "Trendy", "t": "Trendy", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Lo que está de moda ahora mismo. Canciones virales, artistas emergentes y sonidos que marcan tendencia."},
    {"id": "Radios.y.Musica.Lounge", "n": "Lounge", "t": "Lounge", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Ambiente sofisticado y relajado. Una mezcla elegante de sonidos ideales para reuniones, cenas o momentos especiales."},
    {"id": "Radios.y.Musica.Blend", "n": "Blend", "t": "Blend", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Una combinación equilibrada de estilos y épocas. El canal perfecto para quienes disfrutan variedad sin perder coherencia musical."},
    {"id": "Radios.y.Musica.New.Age", "n": "New Age", "t": "New Age", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Paisajes sonoros suaves y espirituales. Ideal para meditar, relajarse y encontrar armonía interior."},
    {"id": "Radios.y.Musica.Tango", "n": "Tango", "t": "Tango", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Pasión, nostalgia y elegancia rioplatense. Los grandes clásicos y nuevas interpretaciones del tango."},
    {"id": "Radios.y.Musica.Tango.Electronico", "n": "Tango Electrónico", "t": "Tango Electrónico", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "La tradición del tango fusionada con beats modernos. Una propuesta innovadora que respeta la esencia y mira al futuro."},
    {"id": "Radios.y.Musica.Clasica", "n": "Clásica", "t": "Clásica", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Obras maestras que han trascendido el tiempo. Sinfonías, conciertos y piezas inolvidables de los grandes compositores."},
    {"id": "Radios.y.Musica.Opera", "n": "Ópera", "t": "Ópera", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "La fuerza y dramatismo de las grandes producciones operísticas. Voces extraordinarias y arias que estremecen."},
    {"id": "Radios.y.Musica.Opera.Romantica", "n": "Ópera Romántica", "t": "Ópera Romántica", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Las arias y escenas más apasionadas del repertorio operístico. Emoción intensa y belleza vocal en cada interpretación."},
    # Radios
    {"id": "Radio.10", "n": "Radio 10", "t": "Radio 10 AM 710", "g": "Radios", "i": "https://i.postimg.cc/rmvVrB6S/Radio-10.png", "d": "Sintoniza la emblemática Radio 10, donde la actualidad, la opinión y la mejor música se combinan para mantenerte informado y entretenido todo el día. Con programas dinámicos y voces reconocidas, Radio 10 es la compañía ideal para tus momentos más importantes."},
    {"id": "Radio.Aspen", "n": "Radio Aspen", "t": "Radio Aspen FM 102.3", "g": "Radios", "i": "https://i.postimg.cc/NMWsH3hX/Radio-Aspen.png", "d": "Aspen te invita a disfrutar de un sonido sofisticado, con música selecta, programas culturales y entrevistas exclusivas. Perfecta para quienes buscan un espacio de distensión y buena conversación en el día a día."},
    {"id": "Radio.Cadena.3", "n": "Radio Cadena 3", "t": "Radio Cadena 3 AM 700", "g": "Radios", "i": "https://i.postimg.cc/DZtvX9Vv/Cadena-3.png", "d": "La radio líder de la Argentina, Cadena 3, te acerca lo mejor de la música nacional e internacional, junto con noticias, deportes y entretenimiento. Con una programación variada y cercana, Cadena 3 es el puente que conecta a la gente con su cultura y su pasión."},
    {"id": "Radio.Cosquin.Rock", "n": "Radio Cosquín Rock", "t": "Radio Cosquín Rock FM 95.5", "g": "Radios", "i": "https://i.postimg.cc/j5Bxm0hq/Cosquin-Rock.png", "d": "El rock argentino suena fuerte. Conciertos y clásicos."},
    {"id": "Radio.Del.Plata", "n": "Radio Del Plata", "t": "Radio Del Plata AM 1030", "g": "Radios", "i": "https://i.postimg.cc/MGjTbmRH/Radio-Del-Plata.png", "d": "Variedad musical, deportes, noticias y entretenimiento."},
    {"id": "Radio.Disney", "n": "Radio Disney", "t": "Radio Disney FM 94.3", "g": "Radios", "i": "https://i.postimg.cc/6pPqvm7Q/Radio-Disney.png", "d": "Los hits que todos aman y contenido para chicos y adolescentes."},
    {"id": "DSports.Radio", "n": "DSports Radio", "t": "DSports Radio FM 103.1", "g": "Radios", "i": "https://i.postimg.cc/sXtjhkFZ/DSports-Radio.png", "d": "Para los fanáticos del deporte, DSports Radio ofrece la cobertura más completa, análisis, entrevistas y la emoción de los grandes eventos deportivos. Mantente al tanto de cada jugada y cada resultado con la voz de los expertos que hacen vibrar a la audiencia."},
    {"id": "Radio.France.Internationale", "n": "Radio France Internationale", "t": "Radio France Internationale", "g": "Radios", "i": "https://i.postimg.cc/6qk02LfR/RFI.png", "d": "Radio France Internationale vous invite à découvrir une sélection pointue de nouvelles, de culture et de musique du monde entier. Avec une perspective francophone unique, ce canal vous connecte à l’actualité internationale, à des interviews captivantes et à une diversité musicale qui traverse les continents."},
    {"id": "Radio.La.Red", "n": "Radio La Red", "t": "Radio La Red AM 910", "g": "Radios", "i": "https://i.postimg.cc/1R7kshbP/Radio-La-Red.png", "d": "Actualidad, fútbol, debate y noticias con opinión."},
    {"id": "Radio.Latina", "n": "Radio Latina", "t": "Radio Latina FM 101.1", "g": "Radios", "i": "https://i.postimg.cc/xdbCy3Hd/Radio-Latina.png", "d": "Éxitos en español y ritmos latinos para disfrutar."},
    {"id": "Radio.Los.40", "n": "Radio Los 40", "t": "Radio Los 40 FM 105.5", "g": "Radios", "i": "https://i.postimg.cc/CKf1HsD1/Radio-Los-40.png", "d": "Los hits del momento y artistas que marcan tendencia pop."},
    {"id": "Radio.Mega", "n": "Radio Mega", "t": "Radio Mega FM 98.3", "g": "Radios", "i": "https://i.postimg.cc/Bv16cBDg/Radio-Mega.png", "d": "Música, entretenimiento y diversión para todos los gustos."},
    {"id": "Radio.Nacional.Clasica", "n": "Radio Nacional Clásica", "t": "Radio Nacional Clásica FM 96.7", "g": "Radios", "i": "https://i.postimg.cc/QNRCn565/Radio-Nacional-Clasica.png", "d": "La música clásica y la cultura sonora a tu alcance."},
    {"id": "Radio.Nacional.Folclorica", "n": "Radio Nacional Folclórica", "t": "Radio Nacional Folclórica FM 98.7", "g": "Radios", "i": "https://i.postimg.cc/zD9vPWd0/Radio-Nacional-Folclorica.png", "d": "Tradición, cultura y folclore argentino en cada nota."},
    {"id": "Radio.Nacional.Rock", "n": "Radio Nacional Rock", "t": "Radio Nacional Rock FM 93.7", "g": "Radios", "i": "https://i.postimg.cc/Vs3vHM74/Radio-Nacional-Rock.png", "d": "Rock nacional e internacional las 24 horas."},
    {"id": "Radio.La.Popu", "n": "Radio La Popu", "t": "Radio La Popu FM 92.3", "g": "Radios", "i": "https://i.postimg.cc/MT7pgZ9S/Radio-La-Popu.png", "d": "La música popular que mueve a la gente."},
    {"id": "Radio.Rivadavia", "n": "Radio Rivadavia", "t": "Radio Rivadavia AM 630", "g": "Radios", "i": "https://i.postimg.cc/y8Kd7KCN/Radio-Rivadavia.png", "d": "Radio Rivadavia es la radio que ha marcado un antes y un después en la historia de la radiofonía argentina. Hoy, llegamos a millones de personas. Te contamos todo lo que pasa en la voz de los periodistas más respetados de nuestro país."},
    {"id": "Radio.Rock.and.Pop", "n": "Radio Rock and Pop", "t": "Radio Rock and Pop FM 95.9", "g": "Radios", "i": "https://i.postimg.cc/fLcR1W8X/Radio-Rock-and-Pop.png", "d": "Todo el rock, pop y música alternativa."},
    {"id": "Radio.Vida", "n": "Radio Vida", "t": "Radio Vida FM 97.9", "g": "Radios", "i": "https://i.ytimg.com/vi/dGQ25rVfUH4/maxresdefault.jpg", "d": "Música variada todo el día con los hits del momento."},
]

def clean_text(text):
    # Reemplaza el carácter '&' por su equivalente válido en XML
    return text.replace("&", "&amp;")

def generar_xml():
    inicio_fijo = datetime.datetime(2026, 2, 23, 0, 0, 0)
    
    lines = []
    lines.append('<?xml version="1.0" encoding="utf-8"?>')
    lines.append('<tv generator-info="EPG Generator">')
    
    for c in canales:
        nombre = clean_text(c["n"])
        lines.append(f'  <channel id="{c["id"]}">')
        lines.append(f'    <display-name>{nombre}</display-name>')
        lines.append('  </channel>')

    for c in canales:
        for d in range(6):
            for h in range(0, 24, 4):
                start_dt = inicio_fijo + datetime.timedelta(days=d, hours=h)
                stop_dt = start_dt + datetime.timedelta(hours=4)
                
                s = start_dt.strftime("%Y%m%d%H%M%S -0300")
                e = stop_dt.strftime("%Y%m%d%H%M%S -0300")
                
                # Limpiamos los textos antes de agregarlos al XML
                titulo = clean_text(c["t"])
                desc = clean_text(c["d"])
                cat = clean_text(c["g"])
                
                lines.append(f'  <programme start="{s}" stop="{e}" channel="{c["id"]}">')
                lines.append(f'    <title>{titulo}</title>')
                lines.append(f'    <desc>{desc}</desc>')
                lines.append(f'    <icon src="{c.get("i")}"/>')
                lines.append(f'    <category>{cat}</category>')
                lines.append(f'  </programme>')

    lines.append('</tv>')
    
    with open("data_v9.xml", "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    
    print("Archivo data_v9.xml generado correctamente y validado contra errores de '&'.")

if __name__ == "__main__":
    generar_xml()
