import datetime

canales = [
    {"id": "GH.MULTI", "n": "Multicámara", "t": "GH - Experiencia Multicámara", "d": "La casa más famosa del país vuelve a abrir sus puertas con una ambientación totalmente renovada, donde los participantes deberán sobreponerse al encierro y la convivencia para avanzar y quedarse con el tan anhelado premio.", "i": "https://i.postimg.cc/zGNBqNYG/GH-Generacion-Dorada.jpg", "g": "Reality"},
    {"id": "GH.24HS", "n": "Gran Hermano 24 hs.", "t": "Gran Hermano 24 hs.", "d": "La casa más famosa del país vuelve a abrir sus puertas con una ambientación totalmente renovada, donde los participantes deberán sobreponerse al encierro y la convivencia para avanzar y quedarse con el tan anhelado premio.", "i": "https://i.postimg.cc/zGNBqNYG/GH-Generacion-Dorada.jpg", "g": "Reality"},
    {"id": "GH.CAM1", "n": "Cámara 1", "t": "Gran Hermano - Cámara 1", "d": "La casa más famosa del país vuelve a abrir sus puertas con una ambientación totalmente renovada, donde los participantes deberán sobreponerse al encierro y la convivencia para avanzar y quedarse con el tan anhelado premio.", "i": "https://i.postimg.cc/zGNBqNYG/GH-Generacion-Dorada.jpg", "g": "Reality"},
    {"id": "GH.CAM2", "n": "Cámara 2", "t": "Gran Hermano - Cámara 2", "d": "La casa más famosa del país vuelve a abrir sus puertas con una ambientación totalmente renovada, donde los participantes deberán sobreponerse al encierro y la convivencia para avanzar y quedarse con el tan anhelado premio.", "i": "https://i.postimg.cc/zGNBqNYG/GH-Generacion-Dorada.jpg", "g": "Reality"},
    {"id": "GH.CAM3", "n": "Cámara 3", "t": "Gran Hermano - Cámara 3", "d": "La casa más famosa del país vuelve a abrir sus puertas con una ambientación totalmente renovada, donde los participantes deberán sobreponerse al encierro y la convivencia para avanzar y quedarse con el tan anhelado premio.", "i": "https://i.postimg.cc/zGNBqNYG/GH-Generacion-Dorada.jpg", "g": "Reality"},
    {"id": "Simpson", "n": "Los Simpson", "t": "Los Simpson", "g": "Comedia, Animación", "i": "https://s3.amazonaws.com/arc-wordpress-client-uploads/infobae-wp/wp-content/uploads/2017/04/17175732/mas-.jpg", "d": "Narra las vivencias de una peculiar familia norteamericana conformada por Homero, Marge, Bart, Lisa y Maggie Simpson."},
    {"id": "El.Chavo", "n": "El Chavo del 8", "t": "El Chavo del 8", "g": "Comedia", "i": "https://i.postimg.cc/Znsj3cMd/El-Chavo-Mini.jpg", "d": "En una humilde vecindad, un niño huérfano vive divertidas aventuras junto a sus vecinos. Entre travesuras y malentendidos con Quico, la Chilindrina y Don Ramón, cada episodio ofrece humor blanco y situaciones entrañables que han marcado a generaciones."},
    {"id": "KNino.TV", "n": "KNino TV", "t": "KNino TV", "g": "Bienestar animal", "i": "https://i.postimg.cc/T3hTD1B9/KNino-mini.png", "d": "El canal pensado para el bienestar de tu perro. Un ecosistema de compañía, calma y cuidado con contenidos diseñados para relajar, estimular y acompañar a las mascotas cuando están en casa."},
    {"id": "TRACE.UK", "n": "TRACE UK", "t": "TRACE UK", "g": "Música", "i": "https://cdn.broadbandtvnews.com/wp-content/uploads/2024/07/02103920/Trace-UK.jpg", "d": "TRACE UK brings viewers the very best of national and international artists, playing the hottest hip-hop, grime, afrobeats, rap and chart topping music videos."},
    {"id": "INFO.FLOW", "n": "FLOW", "t": "Comenzá a usar FLOW", "g": "Interés general", "i": "https://i.postimg.cc/NfmFhMVn/Flow.png", "d": "En Flow podés disfrutar de TV en vivo, películas, series, deportes, música y mucho más."},
    {"id": "Diputados.TV.ARG", "n": "Diputados TV", "t": "Diputados TV", "g": "Periodístico", "i": "https://i.postimg.cc/65nqs3gs/Diputados.png", "d": "Toda la información que concierte al trabajo de los Diputados de la Nación."},
    {"id": "Mix.TV", "n": "Mix TV", "t": "Mix TV", "g": "Interés general", "i": "https://i.postimg.cc/9FZ03MKC/Mix-TV.png", "d": "Entretenimiento sin pausa con realities, espectáculos, actualidad y contenidos que marcan tendencia."},
    {"id": "Lapacho.TV", "n": "Lapacho TV", "t": "Lapacho TV", "g": "Interés general", "i": "https://raw.githubusercontent.com/Puticastillo/EPGCL/main/zoidberg/fallback.jpg", "d": "La pantalla que refleja la identidad formoseña. Información local, cultura y actualidad."},
    {"id": "Telesol.San.Juan", "n": "Telesol", "t": "Telesol", "g": "Interés general", "i": "https://i.ytimg.com/vi/BbJo6A888a4/maxresdefault.jpg", "d": "Toda la actualidad sanjuanina en un solo lugar. Noticias y producción local."},
    {"id": "Claro.Sports.2", "n": "Claro Sports 2", "t": "Claro Sports 2", "g": "Deportes", "i": "https://cdn.amxinfra.com/clarosports/images/2024/08/paralimpicos-cs2-133315.jpg", "d": "Más acción, más competencia y más deporte en vivo. Cobertura de torneos internacionales."},
    {"id": "Sky.Sports.Mexico", "n": "Sky Sports", "t": "Sky Sports", "g": "Deportes", "i": "https://i.postimg.cc/Y2hZk9kp/Sky-Sports.png", "d": "¡Vive tu pasión por los deportes con Sky Sports! Las mejores ligas del mundo, fútbol europeo de primer nivel y grandes competencias internacionales con cobertura especializada."},
    {"id": "Sky.Sports.F1.MX", "n": "Sky Sports F1", "t": "Sky Sports F1", "g": "Deportes", "i": "https://i.postimg.cc/J4Qt1TNr/Sky-Sports-F1.png", "d": "A través de Sky Sports, Izzi ofrecerá la cobertura completa de la temporada 2026 de F1, incluyendo prácticas, clasificaciones y la carrera."},
    {"id": "FOX.ONE", "n": "FOX One", "t": "FOX One", "g": "Deportes", "i": "https://i.postimg.cc/kGNRbC8x/FOX-One.jpg", "d": "Vive la pasión del deporte en FOX One, el canal donde laten las grandes competencias del mundo. Disfruta la intensidad de la Premier League, la emoción incomparable de la UEFA Champions League y los torneos más destacados del calendario internacional."},
    {"id": "DSports.Uruguay", "n": "DSports Uruguay", "t": "DSports Uruguay", "g": "Deportes", "i": "https://i.postimg.cc/13StyS19/DSports-Uruguay.png", "d": "La señal deportiva con foco en Uruguay. Fútbol local e internacional, competiciones destacadas y cobertura en vivo con análisis y producción especializada."},
    {"id": "DSports.Uruguay.Premium", "n": "DSports Uruguay Premium", "t": "DSports Uruguay Premium", "g": "Deportes", "i": "https://i.postimg.cc/3xhR3hQ3/DSports-Uruguay-Premium.png", "d": "La experiencia deportiva más completa. Partidos exclusivos, eventos premium y la mejor cobertura en vivo del deporte uruguayo e internacional."},
    {"id": "FUTBOLCANAL", "n": "Fútbol Canal", "t": "Fútbol Canal", "g": "Deportes", "i": "https://i.postimg.cc/BbtbbyQk/Futbol-Canal.png", "d": "La señal oficial del fútbol boliviano que transmite en vivo cada fecha del torneo nacional. Partidos exclusivos, análisis, entrevistas y toda la pasión de nuestro campeonato."},
    {"id": "FIFA.PLUS.ESP", "n": "FIFA+ en español", "t": "FIFA+ en español", "g": "Deportes", "i": "https://i.postimg.cc/qBn6rj6Q/FIFA.png", "d": "Partidos históricos, documentales, series originales y contenido exclusivo del mundo del fútbol, las 24 horas y en español."},
    {"id": "HBO.Boxing", "n": "HBO Boxing", "t": "HBO Boxing by WBTV", "g": "Boxeo", "i": "https://canvas-lb.tubitv.com/opts/lweaVPhEK4ZaUw==/c68711a9-7ca5-4153-a288-00b76afc4372/CPwDEJ0COgUxLjEuOA==", "d": "The home of elite boxing. World-class fighters, iconic matchups and unforgettable championship nights."},
    {"id": "Rally.TV", "n": "Rally TV", "t": "Rally TV", "g": "Automovilismo", "i": "https://i.postimg.cc/ncKJ8gV9/Rally-TV.png", "d": "El canal dedicado al mundo del rally. Cobertura en vivo, etapas completas, resúmenes y toda la emoción del automovilismo off-road internacional."},
    {"id": "Cazé.TV", "n": "Cazé TV", "t": "Cazé TV", "g": "Deportes", "i": "https://mir-s3-cdn-cf.behance.net/projects/404/f02c5b206996309.Y3JvcCw4MTAsNjMzLDAsMA.png", "d": "Esporte com leveza, informação e mucha resenha. Transmissões vibrantes e convidados especiales."},
    {"id": "Peacock.Premier.League", "n": "Peacock Premier League TV", "t": "Peacock Premier League TV", "g": "Fútbol", "i": "https://i.postimg.cc/TPPCVVkF/Peacock.png", "d": "The exclusive home of Premier League action. Experience every goal, world-class analysis, and live matches from the world's most exciting football league."},
    {"id": "Latin.American.Sports", "n": "Latin American Sports", "t": "Latin American Sports", "g": "Deportes", "i": "https://i.postimg.cc/GmKXT7jV/LAS.png", "d": "Disfruta de la mejor variedad deportiva con un enfoque regional. Cobertura en vivo de torneos locales, análisis profundo y lo mejor del talento latinoamericano."},
    {"id": "GETV.Brasil", "n": "GETV", "t": "GETV", "g": "Entretenimiento", "i": "https://i.postimg.cc/GppqFF70/GETV-Mini.png", "d": "O melhor do entretenimento e informação em um só lugar. Uma programação dinâmica com conteúdos variados para todos os públicos e gostos."},
    {"id": "CONMEBOL.Paramount", "n": "CONMEBOL no Paramount+ Brasil", "t": "CONMEBOL no Paramount+ Brasil", "g": "Fútbol", "i": "https://i.ytimg.com/vi/VJuVyVxBKLY/maxresdefault.jpg", "d": "Assista às maiores emoções do futebol sul-americano. Acompanhe a CONMEBOL Libertadores e Sudamericana com transmissão de alta qualidade e cobertura exclusiva."},
    {"id": "Sportdigital.Free", "n": "Sportdigital Free", "t": "Sportdigital Free", "g": "Deportes", "i": "https://images-1.rakuten.tv/storage/global-live-channel/translation/artwork/4c633f01-1ddb-435b-b7cf-2cc10d0fe2ca.jpeg", "d": "Fußball rund um die Uhr! Erleben Sie spannende internationale Ligen und packende Live-Spiele aus der ganzen Welt völlig kostenlos auf Sportdigital Free."},
    {"id": "Sportdigital.Scooore", "n": "Sportdigital Scooore", "t": "Sportdigital Scooore", "g": "Deportes", "i": "https://i.postimg.cc/0NNcYYWx/Scooore.png", "d": "Ihre Heimat für internationalen Spitzenfußball. Exklusive Live-Übertragungen der besten Ligen weltweit mit fachkundigem Kommentar für echte Fußballfans."},
    {"id": "Tigo.Sports.Plus.PY", "n": "Tigo Sports +", "t": "Tigo Sports +", "g": "Deportes", "i": "https://img.youtube.com/vi/YKmBJnOYgRw/maxresdefault.jpg", "d": "Viví la emoción del deporte como si estuvieras en la cancha. Toda la pasión de los hinchas."},
    {"id": "Eventos.Disney", "n": "ESPN en Disney+ • Eventos", "t": "ESPN en Disney+ • Eventos", "g": "Deportes", "i": "https://i.postimg.cc/QCJ151zz/ESPN-en-Disney-Plus-mini.jpg", "d": "Disfrutá los mejores eventos deportivos en vivo con el sello de la pantalla líder en deportes. Fútbol, tenis, básquet, Fórmula 1 y las competencias más apasionantes del mundo."},
    {"id": "Flow.Sports.1", "n": "Flow Sports", "t": "Flow Sports", "g": "Deportes", "i": "https://i.postimg.cc/T2Z1Hmkk/Flow-Sports.png", "d": "Viví la pasión del deporte como si estuvieras ahí. Adrenalina y emoción en primera fila."},
    {"id": "Flow.Sports.2", "n": "Flow Sports 2", "t": "Flow Sports 2", "g": "Deportes", "i": "https://i.postimg.cc/7PphQ7Bs/Flow-Sports-2.png", "d": "Viví la pasión del deporte como si estuvieras ahí. Adrenalina y emoción en primera fila."},
    {"id": "Flow.Sports.3", "n": "Flow Sports 3", "t": "Flow Sports 3", "g": "Deportes", "i": "https://i.postimg.cc/J4Z0wnvW/Flow-Sports-3.png", "d": "Viví la pasión del deporte como si estuvieras ahí. Adrenalina y emoción en primera fila."},
    {"id": "DM.Kids.TV", "n": "DM Kids TV", "t": "DM Kids TV", "g": "Infantil", "i": "https://i.ytimg.cc/vi/JMbngwxZqZU/maxresdefault.jpg", "d": "Diversión, imaginación y aventuras. Series animadas y contenidos para aprender jugando."},
    {"id": "ENTFamily.40mediaGroup", "n": "#ENTFamily", "t": "#ENTFamily", "g": "Películas", "i": "https://i.postimg.cc/q7RQLhDm/ENT-Family.png", "d": "Contenido familiar para toda la familia. Diversión y entretenimiento seguro las 24 horas."},
    {"id": "ENTMain.40mediaGroup", "n": "#ENTChannel", "t": "#ENTChannel", "g": "Películas", "i": "https://i.postimg.cc/W43SnFYy/ENT-Channel.png", "d": "El equilibrio perfecto de las películas y las series que marcaron generaciones."},
    {"id": "TMC.40mediaGroup", "n": "#Totalmusic", "t": "#Totalmusic", "g": "Música", "i": "https://i.postimg.cc/TPwQ9LNC/Totalmusic.png", "d": "La más amplia selección de videoclips de todos los géneros y épocas."},
    {"id": "TMC80s.40mediaGroup", "n": "#Totalmusic80s", "t": "#Totalmusic80s", "g": "Música", "i": "https://raw.githubusercontent.com/Puticastillo/EPGCL/main/zoidberg/fallback.jpg", "d": "La más variada selección de videoclips de la década dorada de la música."},
    {"id": "TMC2000s.40mediaGroup", "n": "#Totalmusic2000s", "t": "#Totalmusic2000s", "g": "Música", "i": "https://raw.githubusercontent.com/Puticastillo/EPGCL/main/zoidberg/fallback.jpg", "d": "Una cuidada selección de videoclips que marcaron los años 2000."},
    {"id": "TMCConcerts.40mediaGroup", "n": "#TotalmusicConcerts", "t": "#TotalmusicConcerts", "g": "Música", "i": "https://raw.githubusercontent.com/Puticastillo/EPGCL/main/zoidberg/fallback.jpg", "d": "Selección de conciertos en vivo inolvidables de actuaciones legendarias."},
    {"id": "TMCDance.40mediaGroup", "n": "#TotalmusicDance", "t": "#TotalmusicDance", "g": "Música", "i": "https://raw.githubusercontent.com/Puticastillo/EPGCL/main/zoidberg/fallback.jpg", "d": "Selección vibrante de videoclips de música electrónica y dance."},
    {"id": "West.TV.PE", "n": "West TV", "t": "West TV", "g": "Películas", "i": "https://i.postimg.cc/C5MT6DLp/West.png", "d": "Un clásico espacio dedicado al cine del Lejano Oeste. Duelos, sheriffs y forajidos."},
    {"id": "Caras.TV", "n": "Caras TV", "t": "Caras TV", "g": "Interés general", "i": "https://media.canalnet.tv/2024/05/CYaZv3N-1157x720.jpg", "d": "La vida de los famosos, el glamour y las historias que todos comentan."},
    {"id": "El.Mueble", "n": "El Mueble", "t": "El Mueble", "g": "Interés general", "i": "https://raw.githubusercontent.com/Puticastillo/EPGCL/main/zoidberg/fallback.jpg", "d": "Inspiración, diseño y decoración. Ideas y tendencias para transformar tu hogar."},
    {"id": "Aunar", "n": "Aunar", "t": "Aunar", "g": "Cultura", "i": "https://raw.githubusercontent.com/Puticastillo/EPGCL/main/zoidberg/fallback.jpg", "d": "Cultura, sociedad y contenidos que inspiran. Historias y perspectivas del mundo."},
    {"id": "Horizons.Wild", "n": "Horizons.Wild", "t": "Horizons.Wild", "g": "Naturaleza", "i": "https://i.pinimg.com/736x/e6/a5/40/e6a540fd812d99d1d3d4584c080b9e92.jpg", "d": "Explorá la naturaleza en su estado más puro. Documentales de fauna y paisajes."},
    {"id": "Viajar", "n": "Viajar", "t": "Viajar", "g": "Viajes", "i": "https://i.postimg.cc/vTWp8p52/Viajar.png", "d": "Descubrí destinos, culturas y aventuras sin moverte de tu sillón."},
    {"id": "Flow.Music.1", "n": "Flow Music", "t": "Flow Music", "g": "Música", "i": "https://i.postimg.cc/28hyp6Mz/Flow-Music.png", "d": "La música la vivís en Flow. Shows en vivo y mucho más."},
    {"id": "Flow.Music.2", "n": "Flow Music 2", "t": "Flow Music 2", "g": "Música", "i": "https://i.postimg.cc/28hyp6Mz/Flow-Music.png", "d": "La música la vivís en Flow. Shows en vivo y mucho más."},
    {"id": "Flow.Music.3", "n": "Flow Music 3", "t": "Flow Music 3", "g": "Música", "i": "https://i.postimg.cc/28hyp6Mz/Flow-Music.png", "d": "La música la vivís en Flow. Shows en vivo y mucho más."},
    {"id": "Flow.Music.4", "n": "Flow Music 4", "t": "Flow Music 4", "g": "Música", "i": "https://i.postimg.cc/28hyp6Mz/Flow-Music.png", "d": "La música la vivís en Flow. Shows en vivo y mucho más."},
    {"id": "Billboard.AR", "n": "Billboard", "t": "Billboard", "g": "Música", "i": "https://i.postimg.cc/x1QC9QVn/Billboard.png", "d": "Lo último en música, charts y artistas que marcan tendencia."},
    {"id": "Deluxe.Music.Wintertime", "n": "Deluxe Music Wintertime", "t": "Deluxe Music Wintertime", "g": "Musik", "i": "https://raw.githubusercontent.com/Puticastillo/EPGCL/main/zoidberg/fallback.jpg", "d": "Eine besondere Musikauswahl für die Winterzeit. Genießen Sie die besten Hits und gefühlvolle Balladen für gemütliche Stunden."},
    {"id": "El.Folklorico", "n": "El Folklórico", "t": "El Folklórico", "g": "Música", "i": "https://raw.githubusercontent.com/Puticastillo/EPGCL/main/zoidberg/fallback.jpg", "d": "Raíces, tradición y la esencia del folclore en cada nota. Música y danza."},
    {"id": "Hit.TV", "n": "Hit TV", "t": "Hit TV", "g": "Música", "i": "https://raw.githubusercontent.com/Puticastillo/EPGCL/main/zoidberg/fallback.jpg", "d": "Los éxitos musicales más sonados en un solo canal. Videos y listas."},
    {"id": "FMH.Kizzi", "n": "FMH Kizzi", "t": "FMH Kizzi", "g": "Música", "i": "https://raw.githubusercontent.com/Puticastillo/EPGCL/main/zoidberg/fallback.jpg", "d": "Ritmo, frescura y los mejores lanzamientos musicales actuales."},
    {"id": "Music.Box.Classic", "n": "Music Box Classic", "t": "Music Box Classic", "g": "Music", "i": "https://www.digitalfernsehen.de/wp-content/uploads/2025/12/Music-Box-Classic.jpg", "d": "Travel back in time with the greatest classics. Timeless hits and unforgettable melodies that never lose their charm."},
    {"id": "Music.Box.Dance", "n": "Music Box Dance", "t": "Music Box Dance", "g": "Music", "i": "https://www.digitalfernsehen.de/wp-content/uploads/2025/12/Music-Box-Dance.jpg", "d": "Get up and move with nonstop beats. Electronic, house, and dance tracks to keep your energy high."},
    {"id": "Music.Box.Hits", "n": "Music Box Hits", "t": "Music Box Hits", "g": "Music", "i": "https://www.digitalfernsehen.de/wp-content/uploads/2025/12/Music-Box-Hits.jpg", "d": "The hottest songs of the moment, from international chart-toppers to local favorites. Always fresh, always trending."},
    {"id": "Music.Box.Sexy", "n": "Music Box Sexy", "t": "Music Box Sexy", "g": "Music", "i": "https://www.parabola.cz/img_magazin/2025/music-box-sexy.jpg", "d": "Set the mood with smooth and sultry tunes. Lounge, R&B, and seductive rhythms to unwind or flirt."},
    {"id": "Musictop", "n": "MusicTop", "t": "MusicTop", "g": "Música", "i": "https://raw.githubusercontent.com/Puticastillo/EPGCL/main/zoidberg/fallback.jpg", "d": "Top charts y éxitos globales. Videos, rankings y artistas dominantes."},
    {"id": "Thats.70s", "n": "That's 70s", "t": "That's 70s", "g": "Música", "i": "https://i.postimg.cc/2j09ZVkC/70s-MINI.png", "d": "Relive the magic of the 1970s with a curated selection of disco, funk, and classic rock."},
    {"id": "Thats.80s", "n": "That's 80s", "t": "That's 80s", "g": "Música", "i": "https://i.postimg.cc/0jXtRHW0/80MINI.png", "d": "Step into the neon world of the 1980s. A non-stop journey through the biggest synth-pop hits, new wave classics, and hair metal ballads."},
    {"id": "Thats.90s.00s", "n": "That's 90s & 00s", "t": "That's 90s & 00s", "g": "Música", "i": "https://i.postimg.cc/hjgZ9mQz/90s00s-MINI.png", "d": "Experience the evolution of sound across two powerful decades. Grunge, pop-punk and early 2000s hits."},
    {"id": "Thats.Rock", "n": "That's Rock", "t": "That's Rock", "g": "Música", "i": "https://i.postimg.cc/3JWSCYNb/ROCKMINI.png", "d": "Turn up the volume for the ultimate rock experience. From legendary arena rock anthems to hard-hitting riffs."},
    {"id": "Vevo.Pop.Esp", "n": "Vevo Pop Español", "t": "Vevo Pop Español", "g": "Música", "i": "https://i.postimg.cc/JnbcF8pV/vevopopespanol-mini.png", "d": "Los éxitos más grandes del pop en nuestro idioma, desde baladas románticas hasta ritmos urbanos."},
    {"id": "Vevo.Retro", "n": "Vevo Retro", "t": "Vevo Retro", "g": "Música", "i": "https://i.postimg.cc/TwrqsxCB/vevoretro-mini.png", "d": "Un viaje visual por los clásicos inolvidables que definieron generaciones."},
    {"id": "Vevo.Retro.Rock", "n": "Vevo Retro Rock", "t": "Vevo Retro Rock", "g": "Música", "i": "https://i.postimg.cc/RFcQYmXk/vevoretrorock-mini.png", "d": "Las guitarras más legendarias y los himnos del rock que nunca pasan de moda."},
    {"id": "Vevo.70s.80s", "n": "Vevo '70s & '80s", "t": "Vevo '70s & '80s", "g": "Música", "i": "https://i.postimg.cc/50wqrJs1/vevo70s80s-mini.png", "d": "Desde la música disco hasta el sintetizador: lo mejor de dos décadas revolucionarias."},
    {"id": "Vevo.90s.00s", "n": "Vevo '90s & '00s", "t": "Vevo '90s & '00s", "g": "Música", "i": "https://i.postimg.cc/zBmFpvSQ/vevo80s90s-mini.png", "d": "Revive la era del grunge, el pop adolescente y el nacimiento del nuevo milenio."},
    {"id": "Vevo.2010s", "n": "Vevo '2010s", "t": "Vevo '2010s", "g": "Música", "i": "https://i.postimg.cc/DZqdNhxv/vevo2010s-mini.png", "d": "Los videos más virales y los artistas que dominaron las listas en la última década."},
    {"id": "Vevo.HipHop.RB", "n": "Vevo Hip-Hop & R&B", "t": "Vevo Hip-Hop & R&B", "g": "Música", "i": "https://i.postimg.cc/Twrqsxt8/vevohiphopandr-and-b-mini.png", "d": "El mejor flow, beats pesados y las voces más potentes del R&B y el Hip-Hop mundial."},
    {"id": "Vorterix", "n": "Vorterix", "t": "Vorterix", "g": "Música", "i": "https://i.postimg.cc/1zqMZDG2/Vorterix.png", "d": "Pionero como medio de streaming sumado a la frecuencia FM."},
    {"id": "Radio.Maria", "n": "Radio María", "t": "Radio María", "g": "Religión", "i": "https://raw.githubusercontent.com/Puticastillo/EPGCL/main/zoidberg/fallback.jpg", "d": "Espiritualidad, oración y música religiosa para acompañar tu fe."},
    {"id": "Santa.Maria", "n": "Santa María", "t": "Santa María", "g": "Religión", "i": "https://raw.githubusercontent.com/Puticastillo/EPGCL/main/zoidberg/fallback.jpg", "d": "Contenido religioso y formación espiritual con reflexiones para el hogar."},
    {"id": "Solidaria.TV", "n": "Solidaria TV", "t": "Solidaria TV", "g": "Religión", "i": "https://raw.githubusercontent.com/Puticastillo/EPGCL/main/zoidberg/fallback.jpg", "d": "Historias de ayuda, solidaridad y compromiso social inspirador."},
    {"id": "Latam.Rural", "n": "Latam Rural", "t": "Latam Rural", "g": "Agro", "i": "https://raw.githubusercontent.com/Puticastillo/EPGCL/main/zoidberg/fallback.jpg", "d": "Todo el mundo agro en un solo lugar. Noticias, producción y tecnología."},
    {"id": "BBB.MULTI", "n": "Big Brother Brasil - Multicâmera", "t": "Big Brother Brasil - Multicâmera", "g": "Reality", "i": "https://dominiopop.com.br/wp-content/uploads/2025/12/logo-bbb.jpg", "d": "Acompanhe cada momento como se você estivesse dentro da casa em tempo real."},
    {"id": "BBB.CAM1", "n": "Big Brother Brasil - Câmera 1", "t": "BBB - Câmera 1", "g": "Reality", "i": "https://dominiopop.com.br/wp-content/uploads/2025/12/logo-bbb.jpg", "d": "Acompanhe cada momento como se você estivesse dentro da casa em tempo real."},
    {"id": "BBB.CAM2", "n": "Big Brother Brasil - Câmera 2", "t": "BBB - Câmera 2", "g": "Reality", "i": "https://dominiopop.com.br/wp-content/uploads/2025/12/logo-bbb.jpg", "d": "Acompanhe cada momento como se você estivesse dentro da casa em tempo real."},
    {"id": "VTV.URUGUAY", "n": "VTV", "t": "VTV", "g": "Interés general", "i": "https://i.postimg.cc/Y0Sncxc9/vtv.jpg", "d": "Noticias, actualidad y cobertura completa de Uruguay y el mundo."},
    {"id": "Noticias.Caracol", "n": "Noticias Caracol", "t": "Noticias Caracol", "g": "Noticias", "i": "https://i.postimg.cc/HxLYNfLz/image.png", "d": "La información que necesitás con análisis y reportajes importantes."},
    {"id": "Exxxotica.Channel", "n": "EXXXOTICA", "t": "EXXXOTICA", "g": "Adultos", "i": "https://raw.githubusercontent.com/Puticastillo/EPGCL/main/zoidberg/fallback.jpg", "d": "Premium adult entertainment featuring high-quality content and exclusive productions from the most renowned stars in the industry."},
    {"id": "Red.Lips.TV", "n": "Red Lips", "t": "Red Lips", "g": "Adultos", "i": "https://raw.githubusercontent.com/Puticastillo/EPGCL/main/zoidberg/fallback.jpg", "d": "Elegant and provocative adult programming designed for a sophisticated audience, showcasing artistic and high-definition content."},
    # Regionales
    {"id": "Somos.AMBA", "n": "Somos AMBA", "t": "Somos AMBA", "g": "Noticias", "i": "https://i.postimg.cc/XvHh2rJ9/Somos-AMBA.png", "d": "Toda la actualidad del área metropolitana de Buenos Aires. Noticias locales, política y cultura con la cobertura más completa de la región."},
    {"id": "Somos.Bahia.Blanca", "n": "Somos Bahía Blanca", "t": "Somos Bahía Blanca", "g": "Noticias", "i": "https://i.postimg.cc/CKLXHGFM/Somos-Bahia-Blanca.png", "d": "La información más relevante de Bahía Blanca y la región. Entrevistas, deportes y el análisis de los hechos que marcan el día a día local."},
    {"id": "Somos.Bell.Ville", "n": "Somos Bell Ville", "t": "Somos Bell Ville", "g": "Noticias", "i": "https://i.postimg.cc/258MFQzL/Somos-Bell-Ville.png", "d": "Conectados con la realidad de Bell Ville. El resumen de noticias, eventos comunitarios y la actualidad cordobesa con mirada profesional."},
    {"id": "Somos.El.Valle", "n": "Somos El Valle", "t": "Somos El Valle", "g": "Noticias", "i": "https://i.postimg.cc/QMxwkQXk/Somos-El-Valle.png", "d": "La voz del Alto Valle rionegrino. Sigue de cerca la producción, la política y los temas sociales que interesan a toda nuestra comunidad."},
    {"id": "Somos.Entre.Rios", "n": "Somos Entre Ríos", "t": "Somos Entre Ríos", "g": "Noticias", "i": "https://i.postimg.cc/3wJVCXKF/Somos-Entre-Rios.png", "d": "El pulso informativo de la provincia de Entre Ríos. Cobertura federal con noticias, cultura y los protagonistas de nuestra tierra entrerriana."},
    {"id": "Somos.La.Plata", "n": "Somos La Plata", "t": "Somos La Plata", "g": "Noticias", "i": "https://i.postimg.cc/nLcgY4HL/Somos-La-Plata.png", "d": "Información de primera mano sobre la capital bonaerense. Política provincial, actualidad platense y la agenda cultural de toda la ciudad."},
    {"id": "Somos.Litoral", "n": "Somos Litoral", "t": "Somos Litoral", "g": "Noticias", "i": "https://i.postimg.cc/W4bC6G21/Somos-Litoral.png", "d": "Las noticias más importantes de la región del Litoral. Un recorrido por la actualidad de Corrientes y zonas aledañas con enfoque regional."},
    {"id": "Somos.MDQ.Necochea", "n": "Somos Mar del Plata - Necochea", "t": "Somos Mar del Plata - Necochea", "g": "Noticias", "i": "https://i.postimg.cc/x1PBzxS2/Somos-MDQ-Necochea.png", "d": "Toda la actualidad de Mar del Plata y Necochea. Información turística, política local y el seguimiento de lo que pasa en la costa atlántica."},
    {"id": "Somos.Rosario", "n": "Somos Rosario", "t": "Somos Rosario", "g": "Noticias", "i": "https://i.postimg.cc/Pqr9zWtm/Somos-Rosario.png", "d": "El canal de los rosarinos. Noticias de último momento, deportes, política y toda la vida social de la ciudad más importante de Santa Fe."},
    {"id": "Somos.Salta.Jujuy", "n": "Somos Salta - Jujuy", "t": "Somos Salta - Jujuy", "g": "Noticias", "i": "https://i.postimg.cc/8CK3y75h/Somos-Salta-Jujuy.png", "d": "La actualidad del Noroeste Argentino. Uniendo Salta y Jujuy con las noticias más destacadas, cultura regional y la información del día."},
    {"id": "Somos.Santa.Fe", "n": "Somos Santa Fe", "t": "Somos Santa Fe", "g": "Noticias", "i": "https://i.postimg.cc/BvQkcTqM/Somos-Santa-Fe.png", "d": "Desde la capital santafesina, toda la cobertura política y social. El análisis de los hechos y la información que importa a los ciudadanos."},
    {"id": "Somos.Tucuman", "n": "Somos Tucumán", "t": "Somos Tucumán", "g": "Noticias", "i": "https://i.postimg.cc/mr2JNYb2/Somos-Tucuman.png", "d": "La actualidad del Jardín de la República. Información local, política tucumana y cultura con la cobertura más completa de toda la provincia."},
    {"id": "Canal.Provincial", "n": "Canal Provincial", "t": "Canal Provincial", "g": "Noticias", "i": "https://i.postimg.cc/k4WvDyG4/Provincial.png", "d": "Toda la actualidad de la provincia de Buenos Aires. Información local, política, cultura y sociedad con la cobertura más profesional de nuestra región."},
    {"id": "UNLP.TV", "n": "Universidad Nacional de La Plata TV", "t": "Universidad Nacional de La Plata TV", "g": "Cultura", "i": "https://i.postimg.cc/nLy1HWFX/UNLP.png", "d": "El canal de la Universidad Nacional de La Plata. Divulgación científica, cultura, debates académicos y noticias con el respaldo de una gran institución."},
    {"id": "Telejunin", "n": "Telejunín", "t": "Telejunín", "g": "Noticias", "i": "https://i.postimg.cc/s2kJVLjX/Telejunin.png", "d": "La actualidad de Junín y el noroeste bonaerense. Sigue los hechos más relevantes, entrevistas y el deporte local con la mayor cercanía a nuestra gente."},
    {"id": "Verte.Olavarria", "n": "Verte+", "t": "Verte+", "g": "Noticias", "i": "https://i.postimg.cc/G2vx9jtb/Verte-Olavarria.png", "d": "Noticias y actualidad de Olavarría. El primer canal digital con toda la información, política y sociedad de la ciudad transmitiendo en vivo para vos."},
    {"id": "Canal.79.MDQ", "n": "Canal 79", "t": "Canal 79", "g": "Variedades", "i": "https://i.postimg.cc/tgKzXcq0/Canal-79.png", "d": "El canal local de Mar del Plata con enfoque en la comunidad. Programación variada, noticias costeras y eventos culturales de 'La Feliz' durante todo el año."},
    {"id": "Canal.2.MDQ", "n": "Canal 2", "t": "Canal 2", "g": "Variedades", "i": "https://i.postimg.cc/dVSBf1gk/Canal-2-MDQ.jpg", "d": "Canal pionero en Mar del Plata. Toda la información del sudeste bonaerense, eventos, espectáculos y el acontecer diario de la costa con calidad HD."},
    {"id": "Canal.Universidad.UNMDP", "n": "Canal Universidad UNMDP", "t": "Canal Universidad UNMDP", "g": "Cultura", "i": "https://i.postimg.cc/wBCk6rq8/Canal-UNMDP.png", "d": "Desde la Universidad Nacional de Mar del Plata para toda la región. Ciencia, arte, pensamiento crítico y producciones audiovisuales con sello académico."},
    {"id": "Eco.TV.Tandil", "n": "Eco TV", "t": "Eco TV", "g": "Noticias", "i": "https://i.postimg.cc/fbGvwPzN/Eco-TV.png", "d": "La voz de Tandil. Noticias locales, el pulso de la ciudad serrana y toda la información de la región con un equipo periodístico comprometido y veraz."},
    {"id": "Canal.C.CBA", "n": "Canal C", "t": "Canal C", "g": "Noticias", "i": "https://i.postimg.cc/cJpcszx0/Canal-C.png", "d": "El canal de opinión de Córdoba. Análisis político, actualidad provincial y debate con los protagonistas que marcan la agenda del centro del país."},
    {"id": "Showsport.CBA", "n": "Showsport", "t": "Showsport", "g": "Deportes", "i": "https://i.postimg.cc/5tY3WJMK/Showsport.png", "d": "Toda la pasión del deporte cordobés en un solo lugar. Seguimiento de los clubes locales, ligas regionales y las mejores coberturas del mundo deportivo."},
    {"id": "Next.TV.Carlos.Paz", "n": "Next TV", "t": "Next TV", "g": "Variedades", "i": "https://i.postimg.cc/xdJRVQS4/Next-VCP.png", "d": "Información y entretenimiento desde Villa Carlos Paz. El pulso del turismo, la temporada teatral y los eventos más importantes de la villa cordobesa."},
    {"id": "Rafaela.Noticias", "n": "Rafaela Noticias TV", "t": "Rafaela Noticias TV", "g": "Noticias", "i": "https://i.postimg.cc/W4B72y2C/Rafaela-Noticias.png", "d": "Toda la actualidad de Rafaela y el departamento Castellanos. Noticias de último momento, política y sociedad santafesina con mirada profesional."},
    {"id": "Vive.TV.Rosario", "n": "Vive TV Rosario", "t": "Vive TV Rosario", "g": "Variedades", "i": "https://i.postimg.cc/4375RGTD/Vive-Rosario.png", "d": "El canal joven de Rosario. Música, tendencias, entrevistas y la actualidad de la ciudad más vibrante de Santa Fe con una estética moderna y dinámica."},
    {"id": "AIRE.Santa.Fe", "n": "Aire de Santa Fe", "t": "Aire de Santa Fe", "g": "Noticias", "i": "https://i.postimg.cc/T2VcxGKM/AIRE.png", "d": "Noticias, actualidad y todo lo que pasa en Santa Fe y la región en vivo."},
    {"id": "Cable.Diario.SFE", "n": "Cable & Diario", "t": "Cable & Diario", "g": "Noticias", "i": "https://i.postimg.cc/SK2rb4p6/Cable-Diario.png", "d": "La mejor información de la capital santafesina. Análisis político, economía regional y cultura con la experiencia de un medio líder en la provincia."},
    {"id": "Litus.TV.SFE", "n": "Litus TV", "t": "Litus TV", "g": "Cultura", "i": "https://i.postimg.cc/R06Rxmz1/Litus.png", "d": "El canal de la Universidad Nacional del Litoral. Educación, ciencia, arte y debate ciudadano desde Santa Fe para conectar conocimiento con la sociedad."},
    {"id": "El.Once.Parana", "n": "El Once", "t": "El Once", "g": "Noticias", "i": "https://i.postimg.cc/YSG3B7wf/El-Once.png", "d": "El medio más visto de Entre Ríos. Noticias las 24 horas, solidaridad, deportes y la vida de los entrerrianos con la cobertura más amplia de la región."},
    {"id": "Somos.Uno.Chaco", "n": "Somos UNO", "t": "Somos UNO", "g": "Noticias", "i": "https://i.postimg.cc/QM9bZDrJ/Somos-Uno.png", "d": "Información pública de la provincia del Chaco. Cultura, educación y las noticias de nuestra tierra chaqueña con enfoque federal y participativo."},
    {"id": "NG.Federal", "n": "Norte Grande Federal TV", "t": "Norte Grande Federal TV", "g": "Noticias", "i": "https://i.postimg.cc/s2QcCzR7/NG-Federal.png", "d": "Periodismo desde el Norte Grande para todo el país. Noticias de Chaco, Corrientes y la región con un enfoque profundamente federal y auténtico."},
    {"id": "Ciudad.TV.RES", "n": "Ciudad Televisión", "t": "Ciudad Televisión", "g": "Noticias", "i": "https://i.postimg.cc/rp0J2TLW/Ciudad-TV.png", "d": "Actualidad y noticias de Resistencia y todo el Chaco. Sigue de cerca los hechos políticos, sociales y culturales que definen el día a día provincial."},
    {"id": "5TV.CTES", "n": "5TV", "t": "5TV", "g": "Noticias", "i": "https://i.postimg.cc/6Q20xKNZ/5TV.jpg", "d": "La información de Corrientes minuto a minuto. Política, sociedad y toda la agenda regional con el compromiso de un equipo periodístico de vanguardia."},
    {"id": "Corrientes.TV", "n": "Corrientes TV", "t": "Corrientes TV", "g": "Noticias", "i": "https://i.postimg.cc/8CJHgGV6/Corrientes-TV.png", "d": "El canal oficial de la provincia de Corrientes. Cultura, chamamé, noticias institucionales y los eventos que nos representan ante todo el país."},
    {"id": "T5.Satelital", "n": "T5 Satelital", "t": "T5 Satelital", "g": "Variedades", "i": "https://i.postimg.cc/JhDqC8WD/T5.png", "d": "Desde Corrientes para todo el país. Una señal federal con programas de interés general, folclore, noticias regionales y una mirada abierta al interior."},
    {"id": "Canal.3.FOR", "n": "Canal 3", "t": "Canal 3", "g": "Noticias", "i": "https://i.postimg.cc/T3H9sw-Bq/Canal-3-Formosa.jpg", "d": "La señal de Formosa para toda la familia. Información provincial, cultura formoseña y los temas de interés social que mueven a nuestra comunidad."},
    {"id": "Misiones.Cuatro", "n": "Misiones Cuatro", "t": "Misiones Cuatro", "g": "Noticias", "i": "https://i.postimg.cc/bwFT5J49/Misiones-Cuatro.png", "d": "Toda la actualidad de la tierra colorada. Noticias, política, deportes y la vida cotidiana de Posadas y el interior misionero con voz propia y veraz."},
    {"id": "Canal.4.JUJ", "n": "Canal 4", "t": "Canal 4", "g": "Noticias", "i": "https://i.postimg.cc/4xF50djh/Canal-Cuatro-Jujuy.png", "d": "Líder en información en San Salvador de Jujuy. Sigue toda la actualidad del NOA, festividades, política y los hechos que marcan nuestra identidad."},
    {"id": "Canal.9.La.Rioja", "n": "Canal 9", "t": "Canal 9", "g": "Noticias", "i": "https://i.postimg.cc/mg6wnDK9/9-La-Rioja.png", "d": "La señal oficial riojana con toda la actualidad. Noticias, eventos culturales, deportes y la cobertura federal de cada rincón de nuestra provincia."},
    {"id": "Canal.13.La.Rioja", "n": "Canal 13", "t": "Canal 13", "g": "Noticias", "i": "https://i.postimg.cc/2SXwt6g3/13-La-Rioja.png", "d": "Información y cultura desde La Rioja. Programación variada con noticias de último momento, política riojana y el pulso social del noroeste argentino."},
    {"id": "Multivision.Federal", "n": "Multivisión Federal", "t": "Multivisión Federal", "g": "Noticias", "i": "https://i.postimg.cc/qR2xgGqt/Multivision.jpg", "d": "Periodismo federal desde Salta para Argentina. Las noticias del norte y de todo el país con móviles en vivo y la información al instante que necesitas."},
    {"id": "San.Luis.Mas", "n": "San Luis +", "t": "San Luis +", "g": "Noticias", "i": "https://i.postimg.cc/gJ3HrKjn/San-Luis-mini.png", "d": "La evolución de la información en San Luis. Actualidad, tecnología y servicios para toda la provincia con una mirada innovadora y comprometida."},
    {"id": "TVP.Fueguina", "n": "Televisión Pública Fueguina", "t": "Televisión Pública Fueguina", "g": "Noticias", "i": "https://i.postimg.cc/k4WvDyG2/TVP-Fueguina.png", "d": "Desde el fin del mundo, la televisión pública de Tierra del Fuego. Noticias de Ushuaia, Río Grande y la Antártida con soberanía e identidad local."},
    # Stingray Music
    {"id": "Stingray.Big.Band", "n": "Big Band", "t": "Big Band", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Viaja a la era dorada de las grandes orquestas. Swing vibrante y glamour de los salones de baile."},
    {"id": "Stingray.Clasicos.del.Dance", "n": "Clásicos del Dance", "t": "Clásicos del Dance", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Revive la energía de la pista con los himnos dance que marcaron época."},
    {"id": "Stingray.Clasicos.del.Soul.y.el.Rhythm.and.Blues", "n": "Clásicos del Soul y el Rhythm and Blues", "t": "Clásicos del Soul y el Rhythm and Blues", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Sumérgete en la pasión y la intensidad del soul y el R&B clásico."},
    {"id": "Stingray.Clasicos.Indie", "n": "Clásicos Indie", "t": "Clásicos Indie", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Descubre los himnos alternativos que definieron la escena independiente."},
    {"id": "Stingray.Club.de.Baile", "n": "Club de Baile", "t": "Club de Baile", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Éxitos house, techno y trance para no parar de bailar."},
    {"id": "Stingray.Deep.Blues", "n": "Deep Blues", "t": "Deep Blues", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Explora las raíces más profundas del blues. Guitarras intensas y emociones crudas."},
    {"id": "Stingray.Estandares", "n": "Estándares", "t": "Estándares", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "La música de las grandes bandas y las estrellas antes del Rock & Roll."},
    {"id": "Stingray.Euro.Hits", "n": "Euro Hits", "t": "Euro Hits", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Disfruta los éxitos más recientes del panorama musical europeo."},
    {"id": "Stingray.Exitos.de.Brasil", "n": "Éxitos de Brasil", "t": "Éxitos de Brasil", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Siente la alegría y el ritmo de Brasil con los éxitos más representativos."},
    {"id": "Stingray.Exitos.de.Italia", "n": "Éxitos de Italia", "t": "Éxitos de Italia", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Disfruta de las canciones que dominan las listas italianas."},
    {"id": "Stingray.Exitos.de.las.Americas", "n": "Éxitos de las Américas", "t": "Éxitos de las Américas", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Un recorrido musical por el continente americano con sus éxitos más destacados."},
    {"id": "Stingray.Exitos.del.Momento", "n": "Éxitos del Momento", "t": "Éxitos del Momento", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Lo mejor de los artistas emergentes del pop latino."},
    {"id": "Stingray.Exitos.Recientes", "n": "Éxitos Recientes", "t": "Éxitos Recientes", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Obtén lo último y lo mejor de los éxitos del momento."},
    {"id": "Stingray.Exitos.Tropicales", "n": "Éxitos Tropicales", "t": "Éxitos Tropicales", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "El feeling veraniego de lo más actual de la Salsa, la Rumba y el Merengue."},
    {"id": "Stingray.Fiesta.Continua", "n": "Fiesta Continua", "t": "Fiesta Continua", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "No esperes al fin de semana, la fiesta está aquí todas las noches."},
    {"id": "Stingray.Himnos.del.Rock", "n": "Himnos del Rock", "t": "Himnos del Rock", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Sube el volumen con los himnos que definieron generaciones."},
    {"id": "Stingray.Jammin.Reggae", "n": "Jammin' Reggae", "t": "Jammin' Reggae", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Raíces y ramificaciones de diversos estilos de reggae de la isla."},
    {"id": "Stingray.Latin.Lounge", "n": "Latin Lounge", "t": "Latin Lounge", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Sonidos sofisticados y ambiente relajado para celebrar los placeres de la vida."},
    {"id": "Stingray.Mariachi.y.Ranchera", "n": "Mariachi y Ranchera", "t": "Mariachi y Ranchera", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Celebra la tradición mexicana con lo mejor del mariachi y la ranchera."},
    {"id": "Stingray.Musica.del.Mundo", "n": "Música del Mundo", "t": "Música del Mundo", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Explora sonidos y tradiciones de todos los rincones del planeta."},
    {"id": "Stingray.Musica.Ligera", "n": "Música Ligera", "t": "Música Ligera", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Melodías relajantes y alegres, ideal para música de ambiente."},
    {"id": "Stingray.New.Age", "n": "New Age", "t": "New Age", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Paisajes sonoros envolventes y atmósferas serenas para la relajación."},
    # Radios y Música
    {"id": "Radios.y.Musica.Top.40", "n": "Top 40", "t": "Top 40", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Los 40 éxitos más sonados del momento reunidos en un solo canal."},
    {"id": "Radios.y.Musica.Top.Europa", "n": "Top Europa", "t": "Top Europa", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Descubre lo que está marcando el ritmo en las principales capitales europeas."},
    {"id": "Radios.y.Musica.Nuevos.Clasicos", "n": "Nuevos Clásicos", "t": "Nuevos Clásicos", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Éxitos de los últimos años que ya se sienten como imprescindibles."},
    {"id": "Radios.y.Musica.80.Internacional", "n": "80 Internacional", "t": "80 Internacional", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Revive la década dorada del pop y el rock internacional."},
    {"id": "Radios.y.Musica.90.Internacional", "n": "90 Internacional", "t": "90 Internacional", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "El sonido que marcó una generación: Pop, rock alternativo y dance de los 90."},
    {"id": "Radios.y.Musica.80.90.Internacional", "n": "80/90 Internacional", "t": "80/90 Internacional", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Una combinación explosiva de los mejores éxitos de los 80 y 90."},
    {"id": "Radios.y.Musica.70.Internacional", "n": "70 Internacional", "t": "70 Internacional", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Rock clásico, disco y funk de los años 70."},
    {"id": "Radios.y.Musica.60.Internacional", "n": "60 Internacional", "t": "60 Internacional", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Un viaje a los años 60 con melodías que cambiaron la historia."},
    {"id": "Radios.y.Musica.50.Internacional", "n": "50 Internacional", "t": "50 Internacional", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "La década que dio vida al rock & roll y ritmos contagiosos."},
    {"id": "Radios.y.Musica.Grandes.Voces", "n": "Grandes Voces", "t": "Grandes Voces", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Interpretaciones inolvidables de las voces más impactantes."},
    {"id": "Radios.y.Musica.Ellos", "n": "Ellos", "t": "Ellos", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Grandes artistas masculinos que han dejado huella."},
    {"id": "Radios.y.Musica.Ellas", "n": "Ellas", "t": "Ellas", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Celebrando el talento y las voces más poderosas de la música femenina."},
    {"id": "Radios.y.Musica.Vivo", "n": "Vivo", "t": "Vivo", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Presentaciones memorables y la magia irrepetible de la música en directo."},
    {"id": "Radios.y.Musica.Disco", "n": "Disco", "t": "Disco", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Brillos y ritmos irresistibles de los clásicos de la era disco."},
    {"id": "Radios.y.Musica.New.Party", "n": "New Party", "t": "New Party", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Hits actuales y energía alta para animar cualquier fiesta."},
    {"id": "Radios.y.Musica.Retro.Mix", "n": "Retro Mix", "t": "Retro Mix", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Una mezcla irresistible de éxitos retro de distintas décadas."},
    {"id": "Radios.y.Musica.Rock.Nacional", "n": "Rock Nacional", "t": "Rock Nacional", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "El sonido que define generaciones dentro del rock en nuestro idioma."},
    {"id": "Radios.y.Musica.Grandes.del.Rock", "n": "Grandes del Rock", "t": "Grandes del Rock", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Las leyendas y bandas que hicieron del rock un movimiento eterno."},
    {"id": "Radios.y.Musica.Heavy.Metal", "n": "Heavy Metal", "t": "Heavy Metal", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Riffs intensos y pura adrenalina para los amantes del metal."},
    {"id": "Radios.y.Musica.Rock.Alternativo", "n": "Rock Alternativo", "t": "Rock Alternativo", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Sonidos innovadores y propuestas que rompieron esquemas."},
    {"id": "Radios.y.Musica.Power.Ballads", "n": "Power Ballads", "t": "Power Ballads", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Baladas intensas que combinan fuerza y emoción épica."},
    {"id": "Radios.y.Musica.New.Wave", "n": "New Wave", "t": "New Wave", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Sintetizadores y actitud del movimiento que redefinió el pop en los 80."},
    {"id": "Radios.y.Musica.Reggae", "n": "Reggae", "t": "Reggae", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Ritmos relajados y vibraciones positivas del sonido jamaicano."},
    {"id": "Radios.y.Musica.Peliculas", "n": "Películas", "t": "Películas", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Las canciones y bandas sonoras que dieron vida a historias en el cine."},
    {"id": "Radios.y.Musica.Classic.Cinema", "n": "Classic Cinema", "t": "Classic Cinema", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Un recorrido por las composiciones más emblemáticas del cine clásico."},
    {"id": "Radios.y.Musica.Romanticas", "n": "Románticas", "t": "Románticas", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Canciones que hablan directo al corazón, ideales para dedicar."},
    {"id": "Radios.y.Musica.Lentos", "n": "Lentos", "t": "Lentos", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Melodías suaves y envolventes para momentos tranquilos."},
    {"id": "Radios.y.Musica.Teens", "n": "Teens", "t": "Teens", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "El sonido que marca tendencia entre las nuevas generaciones."},
    {"id": "Radios.y.Musica.Reggaeton", "n": "Reggaeton", "t": "Reggaeton", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Ritmo urbano contagioso que domina las pistas globales."},
    {"id": "Radios.y.Musica.Reggaeton.Romantico", "n": "Reggaeton Romántico", "t": "Reggaeton Romántico", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "La fusión perfecta entre ritmo urbano y letras de amor."},
    {"id": "Radios.y.Musica.Latinos", "n": "Latinos", "t": "Latinos", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Una celebración de los sonidos que hacen vibrar a Latinoamérica."},
    {"id": "Radios.y.Musica.Letras.y.Canciones", "n": "Letras y Canciones", "t": "Letras y Canciones", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Canciones con contenido y letras que dejan huella."},
    {"id": "Radios.y.Musica.Salsa", "n": "Salsa", "t": "Salsa", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Sabor y ritmo caribeño con los clásicos y éxitos de la salsa."},
    {"id": "Radios.y.Musica.MPB", "n": "MPB", "t": "MPB", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Lo mejor de la Música Popular Brasileña: Elegancia y poesía."},
    {"id": "Radios.y.Musica.Bossa", "n": "Bossa", "t": "Bossa", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "La suavidad y sofisticación de la bossa nova."},
    {"id": "Radios.y.Musica.Axe", "n": "Axe", "t": "Axe", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Energía y ritmos festivos brasileños para celebrar sin parar."},
    {"id": "Radios.y.Musica.Jazz", "n": "Jazz", "t": "Jazz", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Elegancia y tradición a través de los grandes estándares del jazz."},
    {"id": "Radios.y.Musica.Smooth.Jazz", "n": "Smooth Jazz", "t": "Smooth Jazz", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Sonidos contemporáneos y relajados para ambientes sofisticados."},
    {"id": "Radios.y.Musica.Chill.Out", "n": "Chill Out", "t": "Chill Out", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Ambientes relajantes y atmósferas envolventes para desconectar."},
    {"id": "Radios.y.Musica.Chill.Africa", "n": "Chill Africa", "t": "Chill Africa", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Fusión de sonidos africanos y vibras chill con identidad propia."},
    {"id": "Radios.y.Musica.Electronica", "n": "Electrónica", "t": "Electrónica", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Beats modernos y producción de vanguardia en la electrónica."},
    {"id": "Radios.y.Musica.Trendy", "n": "Trendy", "t": "Trendy", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Lo que está de moda ahora: Canciones virales y artistas nuevos."},
    {"id": "Radios.y.Musica.Lounge", "n": "Lounge", "t": "Lounge", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Mezcla elegante de sonidos para ambientes sofisticados."},
    {"id": "Radios.y.Musica.Blend", "n": "Blend", "t": "Blend", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Combinación equilibrada de distintos estilos y épocas."},
    {"id": "Radios.y.Musica.New.Age", "n": "New Age", "t": "New Age", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Paisajes sonoros suaves para encontrar armonía interior."},
    {"id": "Radios.y.Musica.Tango", "n": "Tango", "t": "Tango", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Pasión y elegancia rioplatense con los grandes clásicos del tango."},
    {"id": "Radios.y.Musica.Tango.Electronico", "n": "Tango Electrónico", "t": "Tango Electrónico", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "La tradición del tango fusionada con ritmos modernos."},
    {"id": "Radios.y.Musica.Clasica", "n": "Clásica", "t": "Clásica", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Obras maestras de los grandes compositores de la historia."},
    {"id": "Radios.y.Musica.Opera", "n": "Ópera", "t": "Ópera", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Dramatismo y fuerza vocal en las grandes producciones operísticas."},
    {"id": "Radios.y.Musica.Opera.Romantica", "n": "Ópera Romántica", "t": "Ópera Romántica", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Las arias más apasionadas y emocionantes del repertorio."},
    # Radios
    {"id": "Radio.10", "n": "Radio 10", "t": "Radio 10 AM 710", "g": "Radios", "i": "https://i.postimg.cc/rmvVrB6S/Radio-10.png", "d": "Actualidad, opinión y compañía informativa durante todo el día."},
    {"id": "Radio.Aspen", "n": "Radio Aspen", "t": "Radio Aspen FM 102.3", "g": "Radios", "i": "https://i.postimg.cc/NMWsH3hX/Radio-Aspen.png", "d": "Música selecta y sonido sofisticado para los amantes de los clásicos."},
    {"id": "Radio.Cadena.3", "n": "Radio Cadena 3", "t": "Radio Cadena 3 AM 700", "g": "Radios", "i": "https://i.postimg.cc/DZtvX9Vv/Cadena-3.png", "d": "Noticias, deportes y entretenimiento de alcance federal."},
    {"id": "Radio.Cosquin.Rock", "n": "Radio Cosquín Rock", "t": "Radio Cosquín Rock FM 95.5", "g": "Radios", "i": "https://i.postimg.cc/j5Bxm0hq/Cosquin-Rock.png", "d": "El rock argentino suena fuerte con clásicos y grabaciones en vivo."},
    {"id": "Radio.Del.Plata", "n": "Radio Del Plata", "t": "Radio Del Plata AM 1030", "g": "Radios", "i": "https://i.postimg.cc/MGjTbmRH/Radio-Del-Plata.png", "d": "Variedad musical, actualidad y deportes."},
    {"id": "Radio.Disney", "n": "Radio Disney", "t": "Radio Disney FM 94.3", "g": "Radios", "i": "https://i.postimg.cc/6pPqvm7Q/Radio-Disney.png", "d": "Los hits que todos aman y contenido para toda la familia."},
    {"id": "DSports.Radio", "n": "DSports Radio", "t": "DSports Radio FM 103.1", "g": "Radios", "i": "https://i.postimg.cc/sXtjhkFZ/DSports-Radio.png", "d": "La cobertura deportiva más completa con la voz de los expertos."},
    {"id": "Radio.France.Internationale", "n": "Radio France Internationale", "t": "Radio France Internationale", "g": "Radios", "i": "https://i.postimg.cc/6qk02LfR/RFI.png", "d": "Perspectiva global única con noticias y cultura desde Francia."},
    {"id": "Radio.La.Red", "n": "Radio La Red", "t": "Radio La Red AM 910", "g": "Radios", "i": "https://i.postimg.cc/1R7kshbP/Radio-La-Red.png", "d": "Fútbol, debate y las noticias del momento con opinión."},
    {"id": "Radio.Latina", "n": "Radio Latina", "t": "Radio Latina FM 101.1", "g": "Radios", "i": "https://i.postimg.cc/xdbCy3Hd/Radio-Latina.png", "d": "Éxitos en español y los ritmos latinos más populares."},
    {"id": "Radio.Los.40", "n": "Radio Los 40", "t": "Radio Los 40 FM 105.5", "g": "Radios", "i": "https://i.postimg.cc/CKf1HsD1/Radio-Los-40.png", "d": "Los hits que marcan tendencia y tus artistas favoritos."},
    {"id": "Radio.Mega", "n": "Radio Mega", "t": "Radio Mega FM 98.3", "g": "Radios", "i": "https://i.postimg.cc/Bv16cBDg/Radio-Mega.png", "d": "Puro rock nacional las 24 horas del día."},
    {"id": "Radio.Nacional.Clasica", "n": "Radio Nacional Clásica", "t": "Radio Nacional Clásica FM 96.7", "g": "Radios", "i": "https://i.postimg.cc/QNRCn565/Radio-Nacional-Clasica.png", "d": "La mejor selección de música clásica y cultura sonora."},
    {"id": "Radio.Nacional.Folclorica", "n": "Radio Nacional Folclórica", "t": "Radio Nacional Folclórica FM 98.7", "g": "Radios", "i": "https://i.postimg.cc/zD9vPWd0/Radio-Nacional-Folclorica.png", "d": "Tradición y cultura argentina a través de sus raíces."},
    {"id": "Radio.Nacional.Rock", "n": "Radio Nacional Rock", "t": "Radio Nacional Rock FM 93.7", "g": "Radios", "i": "https://i.postimg.cc/Vs3vHM74/Radio-Nacional-Rock.png", "d": "Rock nacional e internacional con un toque alternativo."},
    {"id": "Radio.La.Popu", "n": "Radio La Popu", "t": "Radio La Popu FM 92.3", "g": "Radios", "i": "https://i.postimg.cc/MT7pgZ9S/Radio-La-Popu.png", "d": "Música popular que conecta con el sentimiento de la gente."},
    {"id": "Radio.Rivadavia", "n": "Radio Rivadavia", "t": "Radio Rivadavia AM 630", "g": "Radios", "i": "https://i.postimg.cc/y8Kd7KCN/Radio-Rivadavia.png", "d": "Una radio histórica con los periodistas más respetados del país."},
    {"id": "Radio.Rock.and.Pop", "n": "Radio Rock and Pop", "t": "Radio Rock and Pop FM 95.9", "g": "Radios", "i": "https://i.postimg.cc/fLcR1W8X/Radio-Rock-and-Pop.png", "d": "Todo el rock, el pop y la cultura musical alternativa."},
    {"id": "Radio.Vida", "n": "Radio Vida", "t": "Radio Vida FM 97.9", "g": "Radios", "i": "https://i.ytimg.com/vi/dGQ25rVfUH4/maxresdefault.jpg", "d": "Compañía musical con los hits que suenan en todo momento."},
]

def clean_text(text):
    return text.replace("&", "&amp;")

def generar_xml():
    # CAMBIO CLAVE: Obtiene la fecha actual dinámicamente cada vez que corre el script
    ahora = datetime.datetime.now()
    # Crea el inicio a las 00:00:00 del día actual (sin importar qué mes sea)
    inicio_dinamico = datetime.datetime(ahora.year, ahora.month, ahora.day, 0, 0, 0)
    
    lines = []
    lines.append('<?xml version="1.0" encoding="utf-8"?>')
    lines.append('<tv generator-info="EPG Generator">')
    
    # Declaración de canales
    for c in canales:
        nombre = clean_text(c["n"])
        lines.append(f'  <channel id="{c["id"]}">')
        lines.append(f'    <display-name>{nombre}</display-name>')
        lines.append('  </channel>')

    # Generación de programación (7 días para mayor margen)
    for c in canales:
        for d in range(7):
            for h in range(0, 24, 4):
                # Se suma el tiempo a la fecha dinámica de hoy
                start_dt = inicio_dinamico + datetime.timedelta(days=d, hours=h)
                stop_dt = start_dt + datetime.timedelta(hours=4)
                
                s = start_dt.strftime("%Y%m%d%H%M%S -0300")
                e = stop_dt.strftime("%Y%m%d%H%M%S -0300")
                
                titulo = clean_text(c["t"])
                desc = clean_text(c["d"])
                cat = clean_text(c["g"])
                
                lines.append(f'  <programme start="{s}" stop="{e}" channel="{c["id"]}">')
                lines.append(f'    <title>{titulo}</title>')
                lines.append(f'    <desc>{desc}</desc>')
                lines.append(f'    <icon src="{c.get("i")}"/>')
                lines.append(f'    <category>{cat}</category>')
                lines.append(f'  </programme>')

    lines.append('</tv>')
    
    with open("data_v9.xml", "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    
    print(f"Guía generada para la semana del {inicio_dinamico.strftime('%d/%m/%Y')}.")

if __name__ == "__main__":
    generar_xml()
