import datetime

canales = [
    {"id": "GH.MULTI", "n": "Multicámara", "t": "GH - Experiencia Multicámara", "d": "La casa más famosa del país vuelve a abrir sus puertas con una ambientación totalmente renovada, donde los participantes deberán sobreponerse al encierro y la convivencia para avanzar y quedarse con el tan anhelado premio.", "i": "https://i.postimg.cc/zGNBqNYG/GH-Generacion-Dorada.jpg", "g": "Reality"},
    {"id": "GH.24HS", "n": "Gran Hermano 24 hs.", "t": "Gran Hermano 24 hs.", "d": "La casa más famosa del país vuelve a abrir sus puertas con una ambientación totalmente renovada, donde los participantes deberán sobreponerse al encierro y la convivencia para avanzar y quedarse con el tan anhelado premio.", "i": "https://i.postimg.cc/zGNBqNYG/GH-Generacion-Dorada.jpg", "g": "Reality"},
    {"id": "GH.CAM1", "n": "Cámara 1", "t": "Gran Hermano - Cámara 1", "d": "La casa más famosa del país vuelve a abrir sus puertas con una ambientación totalmente renovada, donde los participantes deberán sobreponerse al encierro y la convivencia para avanzar y quedarse con el tan anhelado premio.", "i": "https://i.postimg.cc/zGNBqNYG/GH-Generacion-Dorada.jpg", "g": "Reality"},
    {"id": "GH.CAM2", "n": "Cámara 2", "t": "Gran Hermano - Cámara 2", "d": "La casa más famosa del país vuelve a abrir sus puertas con una ambientación totalmente renovada, donde los participantes deberán sobreponerse al encierro y la convivencia para avanzar y quedarse con el tan anhelado premio.", "i": "https://i.postimg.cc/zGNBqNYG/GH-Generacion-Dorada.jpg", "g": "Reality"},
    {"id": "GH.CAM3", "n": "Cámara 3", "t": "Gran Hermano - Cámara 3", "d": "La casa más famosa del país vuelve a abrir sus puertas con una ambientación totalmente renovada, donde los participantes deberán sobreponerse al encierro y la convivencia para avanzar y quedarse con el tan anhelado premio.", "i": "https://i.postimg.cc/zGNBqNYG/GH-Generacion-Dorada.jpg", "g": "Reality"},
    {"id": "Simpson", "n": "Los Simpson", "t": "Los Simpson", "g": "Comedia, Animación", "i": "https://s3.amazonaws.com/arc-wordpress-client-uploads/infobae-wp/wp-content/uploads/2017/04/17175732/mas-.jpg", "d": "Narra las vivencias de una peculiar familia norteamericana conformada por Homero, Marge, Bart, Lisa y Maggie Simpson."},
    {"id": "Billy.Mandy", "n": "Las sombrías aventuras de Billy y Mandy", "t": "Las sombrías aventuras de Billy y Mandy", "g": "Comedia, Animación", "i": "https://i.postimg.cc/XqbCb4NW/Billy-Mandy-mini.jpg", "d": "Un niño tonto y una niña cruel ganan una apuesta a la Muerte y la obligan a ser su amigo. Juntos viven absurdas, oscuras y sobrenaturales aventuras llenas de humor negro."},
    {"id": "Tom.y.Jerry", "n": "Tom y Jerry", "t": "Tom y Jerry", "g": "Comedia, Animación", "i": "https://i.postimg.cc/SR3HsT50/Tom-y-Jerry-mini.jpg", "d": "Un gato y un ratón que convirtieron la rivalidad en arte. Entre trampas y persecuciones, su caos cómico es una leyenda eterna que ha marcado a muchas generaciones."},
    {"id": "El.Chavo", "n": "El Chavo del 8", "t": "El Chavo del 8", "g": "Comedia", "i": "https://i.postimg.cc/Znsj3cMd/El-Chavo-Mini.jpg", "d": "En una humilde vecindad, un niño huérfano vive divertidas aventuras junto a sus vecinos. Entre travesuras y malentendidos con Quico, la Chilindrina y Don Ramón, cada episodio ofrece humor blanco y situaciones entrañables que han marcado a generaciones."},
    {"id": "KNino.TV", "n": "KNino TV", "t": "KNino TV", "g": "Bienestar animal", "i": "https://i.postimg.cc/T3hTD1B9/KNino-mini.png", "d": "El canal pensado para el bienestar de tu perro. Un ecosistema de compañía, calma y cuidado con contenidos diseñados para relajar, estimular y acompañar a las mascotas cuando están en casa."},
    {"id": "TRACE.UK", "n": "TRACE UK", "t": "TRACE UK", "g": "Música", "i": "https://cdn.broadbandtvnews.com/wp-content/uploads/2024/07/02103920/Trace-UK.jpg", "d": "TRACE UK brings viewers the very best of national and international artists, playing the hottest hip-hop, grime, afrobeats, rap and chart topping music videos."},
    {"id": "INFO.FLOW", "n": "FLOW", "t": "Comenzá a usar FLOW", "g": "Interés general", "i": "https://i.postimg.cc/NfmFhMVn/Flow.png", "d": "En Flow podés disfrutar de TV en vivo, películas, series, deportes, música y mucho más."},
    {"id": "Diputados.TV.ARG", "n": "Diputados TV", "t": "Diputados TV", "g": "Periodístico", "i": "https://i.postimg.cc/65nqs3gs/Diputados.png", "d": "Toda la información que concierte al trabajo de los Diputados de la Nación."},
    {"id": "Mix.TV", "n": "Mix TV", "t": "Mix TV", "g": "Interés general", "i": "https://i.postimg.cc/9FZ03MKC/Mix-TV.png", "d": "Entretenimiento sin pausa con realities, espectáculos, actualidad y contenidos que marcan tendencia."},
    {"id": "Lapacho.TV", "n": "Lapacho TV", "t": "Lapacho TV", "g": "Interés general", "i": "https://raw.githubusercontent.com/Puticastillo/EPGCL/main/zoidberg/fallback.jpg", "d": "La pantalla que refleja la identidad formoseña. Información local, cultura y actualidad."},
    {"id": "Telesol.San.Juan", "n": "Telesol", "t": "Telesol", "g": "Interés general", "i": "https://i.ytimg.com/vi/BbJo6A888a4/maxresdefault.jpg", "d": "Toda la actualidad sanjuanina en un solo lugar. Noticias y producción local."},
    {"id": "EL.SIETE.MZA", "n": "El Siete", "t": "El Siete", "g": "Interés general", "i": "https://i.postimg.cc/gjZDk2v3/El-Siete-mini.png", "d": "¡Sentí Mendoza en cada pantalla! Disfrutá la mejor información en vivo, grandes historias y todo el color de nuestra provincia. El líder que elegís cada día para estar conectado."},
    {"id": "LPF.Play", "n": "La Pasión del Fútbol Play", "t": "La Pasión del Fútbol Play", "g": "Deportes", "i": "https://i.imgur.com/K2BkZgP.jpeg", "d": "Viví la pasión del fútbol en LPF Play, la casa del ascenso y las promesas. Disfrutá la Primera Nacional, el Torneo Proyección y todo el aguante del femenino con el sello oficial de AFA."},
	{"id": "Claro.Sports.2", "n": "Claro Sports 2", "t": "Claro Sports 2", "g": "Deportes", "i": "https://cdn.amxinfra.com/clarosports/images/2024/08/paralimpicos-cs2-133315.jpg", "d": "Más acción, más competencia y más deporte en vivo. Cobertura de torneos internacionales."},
    {"id": "Sky.Sports.Mexico", "n": "Sky Sports", "t": "Sky Sports", "g": "Deportes", "i": "https://i.postimg.cc/Y2hZk9kp/Sky-Sports.png", "d": "¡Vive tu pasión por los deportes con Sky Sports! Las mejores ligas del mundo, fútbol europeo de primer nivel y grandes competencias internacionales con cobertura especializada."},
    {"id": "Sky.Sports.F1.MX", "n": "Sky Sports F1", "t": "Sky Sports F1", "g": "Deportes", "i": "https://i.postimg.cc/J4Qt1TNr/Sky-Sports-F1.png", "d": "¡Vive la emoción de la Fórmula 1 en Sky Sports F1! Prácticas, clasificaciones y todas las carreras del calendario en vivo con la cobertura más completa y especializada."},
    {"id": "FOX.ONE", "n": "FOX ONE", "t": "FOX ONE", "g": "Deportes", "i": "https://i.postimg.cc/kGNRbC8x/FOX-One.jpg", "d": "Vive la pasión del deporte en FOX ONE, el canal donde laten las grandes competencias del mundo. Disfruta la intensidad de la Premier League, la emoción de la UEFA Champions League y los torneos más destacados del calendario."},
    {"id": "DSports.Uruguay", "n": "DSports Uruguay", "t": "DSports Uruguay", "g": "Deportes", "i": "https://i.postimg.cc/13StyS19/DSports-Uruguay.png", "d": "La señal deportiva con foco en Uruguay. Fútbol local e internacional, competiciones destacadas y cobertura en vivo con análisis y producción especializada."},
    {"id": "TVC.Deportes.2", "n": "TVC Deportes 2", "t": "TVC Deportes 2", "g": "Deportes", "i": "https://i.postimg.cc/kDr3S6SQ/tvc-deportes-2-mini.png", "d": "Vive la intensidad del deporte las 24 horas: partidos vibrantes, análisis sin filtro y cobertura exclusiva que te mete en el juego como nunca antes con pura emoción total."},
	{"id": "SportMax", "n": "SportMax", "t": "SportMax", "g": "Deportes", "i": "https://i.postimg.cc/t4PpML3f/Sports-Max-mini.png", "d": "Pasión, análisis y toda la emoción del deporte nacional en un solo lugar. Coberturas, debates y protagonistas para quienes viven cada jugada con intensidad y disfrutan cada historia del deporte argentino."},
    {"id": "DSports.Uruguay.Premium", "n": "DSports Uruguay Premium", "t": "DSports Uruguay Premium", "g": "Deportes", "i": "https://i.postimg.cc/3xhR3hQ3/DSports-Uruguay-Premium.png", "d": "La experiencia deportiva más completa. Partidos exclusivos, eventos premium y la mejor cobertura en vivo del deporte uruguayo e internacional."},
    {"id": "FUTBOLCANAL", "n": "Fútbol Canal", "t": "Fútbol Canal", "g": "Deportes", "i": "https://i.postimg.cc/BbtbbyQk/Futbol-Canal.png", "d": "La señal oficial del fútbol boliviano que transmite en vivo cada fecha del torneo nacional. Partidos exclusivos, análisis, entrevistas y toda la pasión de nuestro campeonato."},
    {"id": "HBO.Boxing", "n": "HBO Boxing", "t": "HBO Boxing by WBTV", "g": "Boxeo", "i": "https://canvas-lb.tubitv.com/opts/lweaVPhEK4ZaUw==/c68711a9-7ca5-4153-a288-00b76afc4372/CPwDEJ0COgUxLjEuOA==", "d": "The home of elite boxing. World-class fighters, iconic matchups and unforgettable championship nights."},
    {"id": "Rally.TV", "n": "Rally TV", "t": "Rally TV", "g": "Automovilismo", "i": "https://i.postimg.cc/ncKJ8gV9/Rally-TV.png", "d": "El canal dedicado al mundo del rally. Cobertura en vivo, etapas completas, resúmenes y toda la emoción del automovilismo off-road internacional."},
    {"id": "Cazé.TV", "n": "Cazé TV", "t": "Cazé TV", "g": "Deportes", "i": "https://mir-s3-cdn-cf.behance.net/projects/404/f02c5b206996309.Y3JvcCw4MTAsNjMzLDAsMA.png", "d": "Esporte com leveza, informação e mucha resenha. Transmissões vibrantes e convidados especiales."},
    {"id": "Telemundo.Deportes.Ahora", "n": "Telemundo Deportes Ahora", "t": "Telemundo Deportes Ahora", "g": "Deportes", "i": "https://i.postimg.cc/tJ1jCnyw/Telemundo-Deportes-Ahora-mini.png", "d": "Vive la emoción del deporte en español con cobertura vibrante, análisis al instante y eventos imperdibles. Fútbol, boxeo y más, gratis y en vivo, cuando quieras."},
	{"id": "Peacock.Premier.League", "n": "Peacock Premier League TV", "t": "Peacock Premier League TV", "g": "Fútbol", "i": "https://i.postimg.cc/TPPCVVkF/Peacock.png", "d": "The exclusive home of Premier League action. Experience every goal, world-class analysis, and live matches from the world's most exciting football league."},
    {"id": "Latin.American.Sports", "n": "Latin American Sports", "t": "Latin American Sports", "g": "Deportes", "i": "https://i.postimg.cc/GmKXT7jV/LAS.png", "d": "Disfruta de la mejor variedad deportiva con un enfoque regional. Cobertura en vivo de torneos locales, análisis profundo y lo mejor del talento latinoamericano."},
    {"id": "CONMEBOL.Paramount", "n": "CONMEBOL no Paramount+ Brasil", "t": "CONMEBOL no Paramount+ Brasil", "g": "Fútbol", "i": "https://i.ytimg.com/vi/VJuVyVxBKLY/maxresdefault.jpg", "d": "Assista às maiores emoções do futebol sul-americano. Acompanhe a CONMEBOL Libertadores e Sudamericana com transmissão de alta qualidade e cobertura exclusiva."},
    {"id": "Sportdigital.Free", "n": "Sportdigital Free", "t": "Sportdigital Free", "g": "Deportes", "i": "https://images-1.rakuten.tv/storage/global-live-channel/translation/artwork/4c633f01-1ddb-435b-b7cf-2cc10d0fe2ca.jpeg", "d": "Fußball rund um die Uhr! Erleben Sie spannende internationale Ligen und packende Live-Spiele aus der ganzen Welt völlig kostenlos auf Sportdigital Free."},
    {"id": "Sportdigital.Scooore", "n": "Sportdigital Scooore", "t": "Sportdigital Scooore", "g": "Deportes", "i": "https://i.postimg.cc/0NNcYYWx/Scooore.png", "d": "Ihre Heimat für internationalen Spitzenfußball. Exklusive Live-Übertragungen der besten Ligen weltweit mit fachkundigem Kommentar für echte Fußballfans."},
    {"id": "Tigo.Sports.Plus.PY", "n": "Tigo Sports +", "t": "Tigo Sports +", "g": "Deportes", "i": "https://img.youtube.com/vi/YKmBJnOYgRw/maxresdefault.jpg", "d": "Viví la emoción del deporte como si estuvieras en la cancha. Toda la pasión de los hinchas."},
    {"id": "Flow.Sports.1", "n": "Flow Sports", "t": "Flow Sports", "g": "Deportes", "i": "https://i.postimg.cc/T2Z1Hmkk/Flow-Sports.png", "d": "Viví la pasión del deporte como si estuvieras ahí. Adrenalina y emoción en primera fila."},
    {"id": "Flow.Sports.2", "n": "Flow Sports 2", "t": "Flow Sports 2", "g": "Deportes", "i": "https://i.postimg.cc/7PphQ7Bs/Flow-Sports-2.png", "d": "Viví la pasión del deporte como si estuvieras ahí. Adrenalina y emoción en primera fila."},
    {"id": "Flow.Sports.3", "n": "Flow Sports 3", "t": "Flow Sports 3", "g": "Deportes", "i": "https://i.postimg.cc/J4Z0wnvW/Flow-Sports-3.png", "d": "Viví la pasión del deporte como si estuvieras ahí. Adrenalina y emoción en primera fila."},
    {"id": "DM.Kids.TV", "n": "DM Kids TV", "t": "DM Kids TV", "g": "Infantil", "i": "https://i.ytimg.cc/vi/JMbngwxZqZU/maxresdefault.jpg", "d": "Diversión, imaginación y aventuras. Series animadas y contenidos para aprender jugando."},
    {"id": "Cinema.Platino.2", "n": "Cinema Platino 2", "t": "Cinema Platino 2", "g": "Películas", "i": "https://i.postimg.cc/QNyP4yt8/Cinema-Platino-2-mini.png", "d": "Películas en español con estrenos impactantes, clásicos inolvidables y títulos premiados, con ciclos especiales y una selección de historias intensas y memoerables."},
	{"id": "ENTFamily.40mediaGroup", "n": "#ENTFamily", "t": "#ENTFamily", "g": "Películas", "i": "https://i.postimg.cc/q7RQLhDm/ENT-Family.png", "d": "Contenido familiar para toda la familia. Diversión y entretenimiento seguro las 24 horas."},
    {"id": "ENTMain.40mediaGroup", "n": "#ENTChannel", "t": "#ENTChannel", "g": "Películas", "i": "https://i.postimg.cc/W43SnFYy/ENT-Channel.png", "d": "El equilibrio perfecto de las películas y las series que marcaron generaciones."},
    {"id": "TMC.40mediaGroup", "n": "#Totalmusic", "t": "#Totalmusic", "g": "Música", "i": "https://i.postimg.cc/TPwQ9LNC/Totalmusic.png", "d": "La más amplia selección de videoclips de todos los géneros y épocas."},
    {"id": "TMC80s.40mediaGroup", "n": "#Totalmusic80s", "t": "#Totalmusic80s", "g": "Música", "i": "https://raw.githubusercontent.com/Puticastillo/EPGCL/main/zoidberg/fallback.jpg", "d": "La más variada selección de videoclips de la década dorada de la música."},
    {"id": "TMC2000s.40mediaGroup", "n": "#Totalmusic2000s", "t": "#Totalmusic2000s", "g": "Música", "i": "https://raw.githubusercontent.com/Puticastillo/EPGCL/main/zoidberg/fallback.jpg", "d": "Una cuidada selección de videoclips que marcaron los años 2000."},
    {"id": "TMCConcerts.40mediaGroup", "n": "#TotalmusicConcerts", "t": "#TotalmusicConcerts", "g": "Música", "i": "https://raw.githubusercontent.com/Puticastillo/EPGCL/main/zoidberg/fallback.jpg", "d": "Selección de conciertos en vivo inolvidables de actuaciones legendarias."},
    {"id": "TMCDance.40mediaGroup", "n": "#TotalmusicDance", "t": "#TotalmusicDance", "g": "Música", "i": "https://raw.githubusercontent.com/Puticastillo/EPGCL/main/zoidberg/fallback.jpg", "d": "Selección vibrante de videoclips de música electrónica y dance."},
    {"id": "West.TV.PE", "n": "West TV", "t": "West TV", "g": "Películas", "i": "https://i.postimg.cc/C5MT6DLp/West.png", "d": "Un clásico espacio dedicado al cine del Lejano Oeste. Duelos, sheriffs y forajidos."},
    {"id": "Caras.TV", "n": "Caras TV", "t": "Caras TV", "g": "Interés general", "i": "https://media.canalnet.tv/2024/05/CYaZv3N-1157x720.jpg", "d": "La vida de los famosos, el glamour y las historias que todos comentan."},
    {"id": "Aunar", "n": "Aunar", "t": "Aunar", "g": "Cultura", "i": "https://raw.githubusercontent.com/Puticastillo/EPGCL/main/zoidberg/fallback.jpg", "d": "Cultura, sociedad y contenidos que inspiran. Historias y perspectivas del mundo."},
    {"id": "Horizons.Wild", "n": "Horizons.Wild", "t": "Horizons.Wild", "g": "Naturaleza", "i": "https://i.pinimg.com/736x/e6/a5/40/e6a540fd812d99d1d3d4584c080b9e92.jpg", "d": "Explorá la naturaleza en su estado más puro. Documentales de fauna y paisajes."},
    {"id": "Viajar", "n": "Viajar", "t": "Viajar", "g": "Viajes", "i": "https://i.postimg.cc/vTWp8p52/Viajar.png", "d": "Descubrí destinos, culturas y aventuras sin moverte de tu sillón."},
    {"id": "Flow.Music.1", "n": "Flow Music", "t": "Flow Music", "g": "Música", "i": "https://i.postimg.cc/28hyp6Mz/Flow-Music.png", "d": "La música la vivís en Flow con shows en vivo, festivales, entrevistas exclusivas y playlists para cada momento. Disfrutá a tus artistas favoritos y descubrí mucho más contenido."},
    {"id": "Flow.Music.2", "n": "Flow Music 2", "t": "Flow Music 2", "g": "Música", "i": "https://i.postimg.cc/28hyp6Mz/Flow-Music.png", "d": "La música la vivís en Flow con shows en vivo, festivales, entrevistas exclusivas y playlists para cada momento. Disfrutá a tus artistas favoritos y descubrí mucho más contenido."},
    {"id": "Flow.Music.3", "n": "Flow Music 3", "t": "Flow Music 3", "g": "Música", "i": "https://i.postimg.cc/28hyp6Mz/Flow-Music.png", "d": "La música la vivís en Flow con shows en vivo, festivales, entrevistas exclusivas y playlists para cada momento. Disfrutá a tus artistas favoritos y descubrí mucho más contenido."},
    {"id": "Flow.Music.4", "n": "Flow Music 4", "t": "Flow Music 4", "g": "Música", "i": "https://i.postimg.cc/28hyp6Mz/Flow-Music.png", "d": "La música la vivís en Flow con shows en vivo, festivales, entrevistas exclusivas y playlists para cada momento. Disfrutá a tus artistas favoritos y descubrí mucho más contenido."},
    {"id": "Billboard.AR", "n": "Billboard", "t": "Billboard", "g": "Música", "i": "https://i.postimg.cc/x1QC9QVn/Billboard.png", "d": "Lo último en música, charts y artistas que marcan tendencia."},
    {"id": "El.Folklorico", "n": "El Folklórico", "t": "El Folklórico", "g": "Música", "i": "https://raw.githubusercontent.com/Puticastillo/EPGCL/main/zoidberg/fallback.jpg", "d": "Raíces, tradición y la esencia del folclore en cada nota. Música y danza."},
    {"id": "Hit.TV", "n": "Hit TV", "t": "Hit TV", "g": "Música", "i": "https://raw.githubusercontent.com/Puticastillo/EPGCL/main/zoidberg/fallback.jpg", "d": "Los éxitos musicales más sonados en un solo canal. Videos y listas."},
    {"id": "FMH.Kizzi", "n": "FMH Kizzi", "t": "FMH Kizzi", "g": "Música", "i": "https://raw.githubusercontent.com/Puticastillo/EPGCL/main/zoidberg/fallback.jpg", "d": "Ritmo, frescura y los mejores lanzamientos musicales actuales."},
    {"id": "Music.Box.Classic", "n": "Music Box Classic", "t": "Music Box Classic", "g": "Music", "i": "https://www.digitalfernsehen.de/wp-content/uploads/2025/12/Music-Box-Classic.jpg", "d": "Travel back in time with the greatest classics. Timeless hits and unforgettable melodies that never lose their charm."},
    {"id": "Music.Box.Dance", "n": "Music Box Dance", "t": "Music Box Dance", "g": "Music", "i": "https://www.digitalfernsehen.de/wp-content/uploads/2025/12/Music-Box-Dance.jpg", "d": "Get up and move with nonstop beats. Electronic, house, and dance tracks to keep your energy high."},
    {"id": "Music.Box.Hits", "n": "Music Box Hits", "t": "Music Box Hits", "g": "Music", "i": "https://www.digitalfernsehen.de/wp-content/uploads/2025/12/Music-Box-Hits.jpg", "d": "The hottest songs of the moment, from international chart-toppers to local favorites. Always fresh, always trending."},
    {"id": "Music.Box.Sexy", "n": "Music Box Sexy", "t": "Music Box Sexy", "g": "Music", "i": "https://www.parabola.cz/img_magazin/2025/music-box-sexy.jpg", "d": "Set the mood with smooth and sultry tunes. Lounge, R&B, and seductive rhythms to unwind or flirt."},
    {"id": "Musictop", "n": "MusicTop", "t": "MusicTop", "g": "Música", "i": "https://raw.githubusercontent.com/Puticastillo/EPGCL/main/zoidberg/fallback.jpg", "d": "Top charts y éxitos globales. Videos, rankings y artistas dominantes."},
    {"id": "Thats.70s", "n": "That's 70s", "t": "That's 70s", "g": "Música", "i": "https://i.postimg.cc/2j09ZVkC/70s-MINI.png", "d": "Relive the magic of the 1970s with a curated selection of disco, funk, and classic rock."},
    {"id": "Thats.80s", "n": "That's 80s", "t": "That's 80s", "g": "Música", "i": "https://i.postimg.cc/0jXtRHW0/80MINI.png", "d": "Step into the neon world of the 1980s. A non-stop journey through the biggest synth-pop hits, new wave classics, and hair metal ballads."},
    {"id": "Thats.90s.00s", "n": "That's 90s & 00s", "t": "That's 90s & 00s", "g": "Música", "i": "https://i.postimg.cc/hjgZ9mQz/90s00s-MINI.png", "d": "Experience the evolution of sound across two powerful decades. Grunge, pop-punk and early 2000s hits."},
    {"id": "Thats.Rock", "n": "That's Rock", "t": "That's Rock", "g": "Música", "i": "https://i.postimg.cc/3JWSCYNb/ROCKMINI.png", "d": "Turn up the volume for the ultimate rock experience. From legendary arena rock anthems to hard-hitting riffs."},
    {"id": "Vevo.Pop.Esp", "n": "Vevo Pop Español", "t": "Vevo Pop Español", "g": "Música", "i": "https://i.postimg.cc/JnbcF8pV/vevopopespanol-mini.png", "d": "Los éxitos más grandes del pop en nuestro idioma, desde baladas románticas hasta ritmos urbanos."},
    {"id": "Vevo.Retro", "n": "Vevo Retro", "t": "Vevo Retro", "g": "Música", "i": "https://i.postimg.cc/TwrqsxCB/vevoretro-mini.png", "d": "Un viaje visual por los clásicos inolvidables que definieron generaciones."},
    {"id": "Vevo.Retro.Rock", "n": "Vevo Retro Rock", "t": "Vevo Retro Rock", "g": "Música", "i": "https://i.postimg.cc/RFcQYmXk/vevoretrorock-mini.png", "d": "Las guitarras más legendarias y los himnos del rock que nunca pasan de moda."},
    {"id": "Vevo.70s.80s", "n": "Vevo '70s & '80s", "t": "Vevo '70s & '80s", "g": "Música", "i": "https://i.postimg.cc/50wqrJs1/vevo70s80s-mini.png", "d": "Desde la música disco hasta el sintetizador: lo mejor de dos décadas revolucionarias."},
    {"id": "Vevo.90s.00s", "n": "Vevo '90s & '00s", "t": "Vevo '90s & '00s", "g": "Música", "i": "https://i.postimg.cc/zBmFpvSQ/vevo80s90s-mini.png", "d": "Revive la era del grunge, el pop adolescente y el nacimiento del nuevo milenio."},
    {"id": "Vevo.2010s", "n": "Vevo '2010s", "t": "Vevo '2010s", "g": "Música", "i": "https://i.postimg.cc/DZqdNhxv/vevo2010s-mini.png", "d": "Los videos más virales y los artistas que dominaron las listas en la última década."},
    {"id": "Vevo.HipHop.RB", "n": "Vevo Hip-Hop & R&B", "t": "Vevo Hip-Hop & R&B", "g": "Música", "i": "https://i.postimg.cc/Twrqsxt8/vevohiphopandr-and-b-mini.png", "d": "El mejor flow, beats pesados y las voces más potentes del R&B y el Hip-Hop mundial."},
    {"id": "Vorterix", "n": "Vorterix", "t": "Vorterix", "g": "Música", "i": "https://i.postimg.cc/1zqMZDG2/Vorterix.png", "d": "Pionero como medio de streaming sumado a la frecuencia FM."},
    {"id": "Radio.Maria", "n": "Radio María", "t": "Radio María", "g": "Religión", "i": "https://raw.githubusercontent.com/Puticastillo/EPGCL/main/zoidberg/fallback.jpg", "d": "Espiritualidad, oración y música religiosa para acompañar tu fe."},
    {"id": "Santa.Maria", "n": "Santa María", "t": "Santa María", "g": "Religión", "i": "https://raw.githubusercontent.com/Puticastillo/EPGCL/main/zoidberg/fallback.jpg", "d": "Contenido religioso y formación espiritual con reflexiones para el hogar."},
    {"id": "Solidaria.TV", "n": "Solidaria TV", "t": "Solidaria TV", "g": "Religión", "i": "https://raw.githubusercontent.com/Puticastillo/EPGCL/main/zoidberg/fallback.jpg", "d": "Historias de ayuda, solidaridad y compromiso social inspirador."},
    {"id": "Latam.Rural", "n": "Latam Rural", "t": "Latam Rural", "g": "Agro", "i": "https://raw.githubusercontent.com/Puticastillo/EPGCL/main/zoidberg/fallback.jpg", "d": "Todo el mundo agro en un solo lugar. Noticias, producción y tecnología."},
    {"id": "Maussan.Television", "n": "Maussan Televisión", "t": "Maussan Televisión", "g": "Documental", "i": "https://i.postimg.cc/pTSGdLg4/Maussan-mini.jpg", "d": "Explora los grandes misterios del cosmos y la vida extraterrestre en un espacio dedicado a la investigación ufológica, con evidencias exclusivas y análisis de lo oculto en el cielo."},
    {"id": "Quiero.TV.MX", "n": "Quiero TV", "t": "Quiero TV", "g": "Variedades", "i": "https://i.postimg.cc/SsPTKxBF/Quiero-mini.png", "d": "Disfruta de una programación fresca y dinámica que combina noticias locales con el mejor entretenimiento familiar, conectando con la audiencia a través de un estilo muy auténtico."},
    {"id": "Canal.Izzi", "n": "Canal Izzi", "t": "Canal Izzi", "g": "Entretenimiento", "i": "https://i.postimg.cc/76RsLZFy/Izzi-mini.png", "d": "Accede a un mundo de contenidos exclusivos diseñados para el suscriptor moderno, ofreciendo desde estrenos especiales hasta información relevante sobre todos tus servicios favoritos."},
    {"id": "Basket.Americas.TV", "n": "Basket Americas TV", "t": "Basket Americas TV", "g": "Deportes", "i": "https://i.postimg.cc/hjYyGtkR/Basket-Americas-TV-mini.png", "d": "Siente la intensidad de la duela con cada clavada y triple en este canal dedicado íntegramente al baloncesto continental, cubriendo las ligas más emocionantes de toda esta región."},
    {"id": "Beisbol.Latino.TV", "n": "Beisbol Latino TV", "t": "Beisbol Latino TV", "g": "Deportes", "i": "https://i.postimg.cc/xCZxd1wr/Beisbol-Latino-TV-mini.png", "d": "Vive la pasión del rey de los deportes con una cobertura exhaustiva de los diamantes latinoamericanos, donde el talento y la emoción del juego se encuentran en cada transmisión hoy."},
    {"id": "Mexico.al.Aire.Libre", "n": "México al Aire Libre", "t": "México al Aire Libre", "g": "Deportes", "i": "https://i.postimg.cc/LXWCs8cS/Mexico-al-aire-libre-mini.png", "d": "Descubre la adrenalina de las disciplinas extremas y el contacto directo con la naturaleza en una señal que celebra la aventura y el deporte fuera de los escenarios tradicionales."},
    {"id": "Comba.TV", "n": "Comba TV", "t": "Comba TV", "g": "Deportes", "i": "https://i.postimg.cc/MTLPGpCS/Comba-TV-mini.png", "d": "Prepárate para la acción pura en el cuadrilátero y la jaula, con los combates más electrizantes de las artes marciales y el boxeo que definen a los grandes campeones de esta época."},
    {"id": "BBB.MULTI", "n": "Big Brother Brasil - Multicâmera", "t": "Big Brother Brasil - Multicâmera", "g": "Reality", "i": "https://dominiopop.com.br/wp-content/uploads/2025/12/logo-bbb.jpg", "d": "Acompanhe cada momento como se você estivesse dentro da casa em tempo real."},
    {"id": "BBB.CAM1", "n": "Big Brother Brasil - Câmera 1", "t": "Big Brother Brasil - Câmera 1", "g": "Reality", "i": "https://dominiopop.com.br/wp-content/uploads/2025/12/logo-bbb.jpg", "d": "Acompanhe cada momento como se você estivesse dentro da casa em tempo real."},
    {"id": "BBB.CAM2", "n": "Big Brother Brasil - Câmera 2", "t": "Big Brother Brasil - Câmera 2", "g": "Reality", "i": "https://dominiopop.com.br/wp-content/uploads/2025/12/logo-bbb.jpg", "d": "Acompanhe cada momento como se você estivesse dentro da casa em tempo real."},
    {"id": "Noticias.Caracol", "n": "Noticias Caracol", "t": "Noticias Caracol", "g": "Noticias", "i": "https://i.postimg.cc/HxLYNfLz/image.png", "d": "La información que necesitás con análisis y reportajes importantes."},
    {"id": "Exxxotica.Channel", "n": "EXXXOTICA", "t": "EXXXOTICA", "g": "Adultos", "i": "https://raw.githubusercontent.com/Puticastillo/EPGCL/main/zoidberg/fallback.jpg", "d": "Premium adult entertainment featuring high-quality content and exclusive productions from the most renowned stars in the industry."},
    {"id": "Red.Lips.TV", "n": "Red Lips", "t": "Red Lips", "g": "Adultos", "i": "https://raw.githubusercontent.com/Puticastillo/EPGCL/main/zoidberg/fallback.jpg", "d": "Elegant and provocative adult programming designed for a sophisticated audience, showcasing artistic and high-definition content."},
    # Regionales
    {"id": "Somos.AMBA", "n": "Somos AMBA", "t": "Somos AMBA", "g": "Noticias", "i": "https://i.postimg.cc/XvHh2rJ9/Somos-AMBA.png", "d": "Toda la actualidad del área metropolitana de Buenos Aires. Noticias locales, política y cultura con la cobertura más completa de la región."},
    {"id": "Somos.Bahia.Blanca", "n": "Somos Bahía Blanca", "t": "Somos Bahía Blanca", "g": "Noticias", "i": "https://i.postimg.cc/CKLXHGFM/Somos-Bahia-Blanca.png", "d": "La información más relevante de Bahía Blanca y la región. Entrevistas, deportes y el análisis de los hechos que marcan el día a día local."},
    {"id": "Somos.Bell.Ville", "n": "Somos Bell Ville", "t": "Somos Bell Ville", "g": "Noticias", "i": "https://i.postimg.cc/258MFQzL/Somos-Bell-Ville.png", "d": "Conectados con la realidad de Bell Ville. El resumen de noticias, eventos comunitarios y la actualidad cordobesa con mirada profesional."},
    {"id": "Somos.El.Valle", "n": "Somos El Valle", "t": "Somos El Valle", "g": "Noticias", "i": "https://i.postimg.cc/QMxwkQXk/Somos-El-Valle.png", "d": "La voz del Alto Valle rionegrino. Sigue de cerca la producción, la política y los temas sociales que interesan a toda nuestra comunidad."},
    {"id": "Somos.Entre.Rios", "n": "Somos Entre Ríos", "t": "Somos Entre Ríos", "g": "Noticias", "i": "https://i.postimg.cc/3wJVCXKF/Somos-Entre-Rios.png", "d": "El pulso informativo de la provincia de Entre Ríos. Cobertura federal con noticias, cultura y los protagonistas de nuestra tierra entrerriana."},
    {"id": "Somos.La.Plata", "n": "Somos La Plata", "t": "Somos La Plata", "g": "Noticias", "i": "https://i.postimg.cc/nLcgY4HL/Somos-La-Plata.png", "d": "Información de primera mano sobre la capital bonaerense. Política provincial, actualidad platense y la agenda cultural de toda la ciudad."},
    {"id": "Somos.Litoral", "n": "Somos Litoral", "t": "Somos Litoral", "g": "Noticias", "i": "https://i.postimg.cc/W4bC6G21/Somos-Litoral.png", "d": "Las noticias más importantes de la región del Litoral. Un recorrido por la actualidad de Corrientes y zonas aledañas con enfoque regional."},
    {"id": "Somos.MDQ.Necochea", "n": "Somos Mar del Plata - Necochea", "t": "Somos Mar del Plata - Necochea", "g": "Noticias", "i": "https://i.postimg.cc/x1PBzxS2/Somos-MDQ-Necochea.png", "d": "Toda la actualidad de Mar del Plata y Necochea. Información turística, política local y el seguimiento de lo que pasa en la costa atlántica."},
    {"id": "Somos.Rosario", "n": "Somos Rosario", "t": "Somos Rosario", "g": "Noticias", "i": "https://i.postimg.cc/Pqr9zWtm/Somos-Rosario.png", "d": "El canal de los rosarinos. Noticias de último momento, deportes, política y toda la vida social de la ciudad más importante de Santa Fe."},
    {"id": "Somos.Salta.Jujuy", "n": "Somos Salta - Jujuy", "t": "Somos Salta - Jujuy", "g": "Noticias", "i": "https://i.postimg.cc/8CK3y75h/Somos-Salta-Jujuy.png", "d": "La actualidad del Noroeste Argentino. Uniendo Salta y Jujuy con las noticias más destacadas, cultura regional y la información del día."},
    {"id": "Somos.Santa.Fe", "n": "Somos Santa Fe", "t": "Somos Santa Fe", "g": "Noticias", "i": "https://i.postimg.cc/BvQkcTqM/Somos-Santa-Fe.png", "d": "Desde la capital santafesina, toda la cobertura política y social. El análisis de los hechos y la información que importa a los ciudadanos."},
    {"id": "Somos.Tucuman", "n": "Somos Tucumán", "t": "Somos Tucumán", "g": "Noticias", "i": "https://i.postimg.cc/mr2JNYb2/Somos-Tucuman.png", "d": "La actualidad del Jardín de la República. Información local, política tucumana y cultura con la cobertura más completa de toda la provincia."},
    {"id": "Canal.Provincial", "n": "Canal Provincial", "t": "Canal Provincial", "g": "Noticias", "i": "https://i.postimg.cc/k4WvDyG4/Provincial.png", "d": "Toda la actualidad de la provincia de Buenos Aires. Información local, política, cultura y sociedad con la cobertura más profesional de nuestra región."},
    {"id": "UNLP.TV", "n": "Universidad Nacional de La Plata TV", "t": "Universidad Nacional de La Plata TV", "g": "Cultura", "i": "https://i.postimg.cc/nLy1HWFX/UNLP.png", "d": "El canal de la Universidad Nacional de La Plata. Divulgación científica, cultura, debates académicos y noticias con el respaldo de una gran institución."},
    {"id": "Telejunin", "n": "Telejunín", "t": "Telejunín", "g": "Noticias", "i": "https://i.postimg.cc/s2kJVLjX/Telejunin.png", "d": "La actualidad de Junín y el noroeste bonaerense. Sigue los hechos más relevantes, entrevistas y el deporte local con la mayor cercanía a nuestra gente."},
    {"id": "Verte.Olavarria", "n": "Verte+", "t": "Verte+", "g": "Noticias", "i": "https://i.postimg.cc/G2vx9jtb/Verte-Olavarria.png", "d": "Noticias y actualidad de Olavarría. El primer canal digital con toda la información, política y sociedad de la ciudad transmitiendo en vivo para vos."},
    {"id": "Canal.79.MDQ", "n": "Canal 79", "t": "Canal 79", "g": "Variedades", "i": "https://i.postimg.cc/tgKzXcq0/Canal-79.png", "d": "El canal local de Mar del Plata con enfoque en la comunidad. Programación variada, noticias costeras y eventos culturales de 'La Feliz' durante todo el año."},
    {"id": "Canal.2.MDQ", "n": "Canal 2", "t": "Canal 2", "g": "Variedades", "i": "https://i.postimg.cc/dVSBf1gk/Canal-2-MDQ.jpg", "d": "Canal pionero en Mar del Plata. Toda la información del sudeste bonaerense, eventos, espectáculos y el acontecer diario de la costa con calidad HD."},
    {"id": "Canal.Universidad.UNMDP", "n": "Canal Universidad UNMDP", "t": "Canal Universidad UNMDP", "g": "Cultura", "i": "https://i.postimg.cc/wBCk6rq8/Canal-UNMDP.png", "d": "Desde la Universidad Nacional de Mar del Plata para toda la región. Ciencia, arte, pensamiento crítico y producciones audiovisuales con sello académico."},
    {"id": "Eco.TV.Tandil", "n": "Eco TV", "t": "Eco TV", "g": "Noticias", "i": "https://i.postimg.cc/fbGvwPzN/Eco-TV.png", "d": "La voz de Tandil. Noticias locales, el pulso de la ciudad serrana y toda la información de la región con un equipo periodístico comprometido y veraz."},
    {"id": "BVC.BB", "n": "Bahía Visión Color", "t": "Bahía Visión Color", "g": "Noticias", "i": "https://i.imgur.com/6sNxpd7.png", "d": "Medio de comunicación líder en Bahía Blanca con fuerte enfoque local y regional. Ofrece programación variada para toda la familia y noticias locales, siendo parte de la grilla digital de la empresa local de internet y cable."},
	{"id": "Canal.C.CBA", "n": "Canal C", "t": "Canal C", "g": "Noticias", "i": "https://i.postimg.cc/cJpcszx0/Canal-C.png", "d": "El canal de opinión de Córdoba. Análisis político, actualidad provincial y debate con los protagonistas que marcan la agenda del centro del país."},
    {"id": "Showsport.CBA", "n": "Showsport", "t": "Showsport", "g": "Deportes", "i": "https://i.postimg.cc/5tY3WJMK/Showsport.png", "d": "Toda la pasión del deporte cordobés en un solo lugar. Seguimiento de los clubes locales, ligas regionales y las mejores coberturas del mundo deportivo."},
    {"id": "Next.TV.Carlos.Paz", "n": "Next TV", "t": "Next TV", "g": "Variedades", "i": "https://i.postimg.cc/xdJRVQS4/Next-VCP.png", "d": "Información y entretenimiento desde Villa Carlos Paz. El pulso del turismo, la temporada teatral y los eventos más importantes de la villa cordobesa."},
    {"id": "Vive.TV.Rosario", "n": "Vive TV Rosario", "t": "Vive TV Rosario", "g": "Variedades", "i": "https://i.postimg.cc/4375RGTD/Vive-Rosario.png", "d": "El canal joven de Rosario. Música, tendencias, entrevistas y la actualidad de la ciudad más vibrante de Santa Fe con una estética moderna y dinámica."},
    {"id": "Rafaela.Noticias", "n": "Rafaela Noticias TV", "t": "Rafaela Noticias TV", "g": "Noticias", "i": "https://i.postimg.cc/W4B72y2C/Rafaela-Noticias.png", "d": "Toda la actualidad de Rafaela y el departamento Castellanos. Noticias de último momento, política y sociedad santafesina con mirada profesional."},
    {"id": "AIRE.Santa.Fe", "n": "Aire de Santa Fe", "t": "Aire de Santa Fe", "g": "Noticias", "i": "https://i.postimg.cc/T2VcxGKM/AIRE.png", "d": "Noticias, actualidad y todo lo que pasa en Santa Fe y la región en vivo."},
    {"id": "Cable.Diario.SFE", "n": "Cable & Diario", "t": "Cable & Diario", "g": "Noticias", "i": "https://i.postimg.cc/SK2rb4p6/Cable-Diario.png", "d": "La mejor información de la capital santafesina. Análisis político, economía regional y cultura con la experiencia de un medio líder en la provincia."},
    {"id": "Litus.TV.SFE", "n": "Litus TV", "t": "Litus TV", "g": "Cultura", "i": "https://i.postimg.cc/R06Rxmz1/Litus.png", "d": "El canal de la Universidad Nacional del Litoral. Educación, ciencia, arte y debate ciudadano desde Santa Fe para conectar conocimiento con la sociedad."},
    {"id": "Veo.Santa.Fe", "n": "Veo Santa Fe", "t": "Veo Santa Fe", "g": "Noticias", "i": "https://i.postimg.cc/Prrzzg6S/Veo-SF-Mini.png", "d": "La esencia de la capital en tu pantalla. Viví el pulso de la ciudad con noticias al instante, deportes, cultura y toda la actualidad santafesina que te identifica día a día."},
    {"id": "Veo.Santo.Tome", "n": "Veo Santo Tomé", "t": "Veo Santo Tomé", "g": "Noticias", "i": "https://i.postimg.cc/155cckW7/Veo-ST-Mini.png", "d": "El reflejo fiel de Santo Tomé. Seguí de cerca cada historia, los reclamos de los barrios y el acontecer local con la cercanía y el compromiso que solo nuestra comunidad merece."},
    {"id": "El.Once.Parana", "n": "El Once", "t": "El Once", "g": "Noticias", "i": "https://i.postimg.cc/YSG3B7wf/El-Once.png", "d": "El medio más visto de Entre Ríos. Noticias las 24 horas, solidaridad, deportes y la vida de los entrerrianos con la cobertura más amplia de la región."},
    {"id": "Somos.Uno.Chaco", "n": "Somos UNO", "t": "Somos UNO", "g": "Noticias", "i": "https://i.postimg.cc/QM9bZDrJ/Somos-Uno.png", "d": "Información pública de la provincia del Chaco. Cultura, educación y las noticias de nuestra tierra chaqueña con enfoque federal y participativo."},
    {"id": "NG.Federal", "n": "Norte Grande Federal TV", "t": "Norte Grande Federal TV", "g": "Noticias", "i": "https://i.postimg.cc/s2QcCzR7/NG-Federal.png", "d": "Periodismo desde el Norte Grande para todo el país. Noticias de Chaco, Corrientes y la región con un enfoque profundamente federal y auténtico."},
    {"id": "Ciudad.TV.RES", "n": "Ciudad Televisión", "t": "Ciudad Televisión", "g": "Noticias", "i": "https://i.postimg.cc/rp0J2TLW/Ciudad-TV.png", "d": "Actualidad y noticias de Resistencia y todo el Chaco. Sigue de cerca los hechos políticos, sociales y culturales que definen el día a día provincial."},
    {"id": "5TV.CTES", "n": "5TV", "t": "5TV", "g": "Noticias", "i": "https://i.postimg.cc/6Q20xKNZ/5TV.jpg", "d": "La información de Corrientes minuto a minuto. Política, sociedad y toda la agenda regional con el compromiso de un equipo periodístico de vanguardia."},
    {"id": "Corrientes.TV", "n": "Corrientes TV", "t": "Corrientes TV", "g": "Noticias", "i": "https://i.postimg.cc/8CJHgGV6/Corrientes-TV.png", "d": "El canal oficial de la provincia de Corrientes. Cultura, chamamé, noticias institucionales y los eventos que nos representan ante todo el país."},
    {"id": "T5.Satelital", "n": "T5 Satelital", "t": "T5 Satelital", "g": "Variedades", "i": "https://i.postimg.cc/JhDqC8WD/T5.png", "d": "Desde Corrientes para todo el país. Una señal federal con programas de interés general, folclore, noticias regionales y una mirada abierta al interior."},
    {"id": "Canal.3.FOR", "n": "Canal 3", "t": "Canal 3", "g": "Noticias", "i": "https://i.postimg.cc/T3H9sw-Bq/Canal-3-Formosa.jpg", "d": "La señal de Formosa para toda la familia. Información provincial, cultura formoseña y los temas de interés social que mueven a nuestra comunidad."},
    {"id": "Misiones.Cuatro", "n": "Misiones Cuatro", "t": "Misiones Cuatro", "g": "Noticias", "i": "https://i.postimg.cc/bwFT5J49/Misiones-Cuatro.png", "d": "Toda la actualidad de la tierra colorada. Noticias, política, deportes y la vida cotidiana de Posadas y el interior misionero con voz propia y veraz."},
    {"id": "CPE.Santa.Rosa", "n": "Cooperativa Popular de Electricidad de Santa Rosa TV", "t": "Cooperativa Popular de Electricidad de Santa Rosa TV", "g": "Noticias", "i": "https://i.postimg.cc/yx4fcqB3/CPEtv.png", "d": "Programación variada con noticias, historias de vida, tecnología, documentales, cultura, música y entrevistas, reflejando la identidad pampeana y actualidad diaria."},    
	{"id": "Canal.4.JUJ", "n": "Canal 4", "t": "Canal 4", "g": "Noticias", "i": "https://i.postimg.cc/4xF50djh/Canal-Cuatro-Jujuy.png", "d": "Líder en información en San Salvador de Jujuy. Sigue toda la actualidad del NOA, festividades, política y los hechos que marcan nuestra identidad."},
    {"id": "Canal.9.La.Rioja", "n": "Canal 9", "t": "Canal 9", "g": "Noticias", "i": "https://i.postimg.cc/mg6wnDK9/9-La-Rioja.png", "d": "La señal oficial riojana con toda la actualidad. Noticias, eventos culturales, deportes y la cobertura federal de cada rincón de nuestra provincia."},
    {"id": "Canal.13.La.Rioja", "n": "Canal 13", "t": "Canal 13", "g": "Noticias", "i": "https://i.postimg.cc/2SXwt6g3/13-La-Rioja.png", "d": "Información y cultura desde La Rioja. Programación variada con noticias de último momento, política riojana y el pulso social del noroeste argentino."},
    {"id": "Multivision.Federal", "n": "Multivisión Federal", "t": "Multivisión Federal", "g": "Noticias", "i": "https://i.postimg.cc/qR2xgGqt/Multivision.jpg", "d": "Periodismo federal desde Salta para Argentina. Las noticias del norte y de todo el país con móviles en vivo y la información al instante que necesitas."},
    {"id": "San.Luis.Mas", "n": "San Luis +", "t": "San Luis +", "g": "Noticias", "i": "https://i.postimg.cc/gJ3HrKjn/San-Luis-mini.png", "d": "La evolución de la información en San Luis. Actualidad, tecnología y servicios para toda la provincia con una mirada innovadora y comprometida."},
    {"id": "TVP.Fueguina", "n": "Televisión Pública Fueguina", "t": "Televisión Pública Fueguina", "g": "Noticias", "i": "https://i.postimg.cc/k4WvDyG2/TVP-Fueguina.png", "d": "Desde el fin del mundo, la televisión pública de Tierra del Fuego. Noticias de Ushuaia, Río Grande y la Antártida con soberanía e identidad local."},
    # Mundo
    {"id": "Latina.Noticias", "n": "Latina Noticias", "t": "Latina Noticias", "g": "Noticias", "i": "https://i.postimg.cc/Prc2xqL2/Latina-Noticias-mini.png", "d": "Noticiero televisivo peruano que cubre política, economía, sociedad y sucesos en vivo, con reportajes, análisis y corresponsales en todo el país, para informar con rapidez diaria."},
    # Stingray Music
	{"id": "Stingray.2000s", "n": "2000s", "t": "2000s", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Creando la memoria musical del nuevo milenio."},
	{"id": "Stingray.Adulto.Alternativo", "n": "Adulto Alternativo", "t": "Adulto Alternativo", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Rock y Pop contemporáneo con grandes canciones del ayer."},
	{"id": "Stingray.Alternative", "n": "Alternative", "t": "Alternative", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Siente la intensidad de lo mejor del rock alternativo actual y acuérdate de los orígenes del grunge (concentrado e inquisitivo)."},
	{"id": "Stingray.Anos.70", "n": "Años 70", "t": "Años 70", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Para amantes del rock, del baile o de la canción romántica. ¡Deja que este canal te devuelva a la era de la pompa y el glamour!"},
	{"id": "Stingray.Anos.80", "n": "Años 80", "t": "Años 80", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Sube el volumen con la música de nuestra década favorita. ¡Este canal es para que te muevas! Un viaje de vuelta a los días de hombreras y cabello voluminoso."},
	{"id": "Stingray.Anos.90", "n": "Años 90", "t": "Años 90", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Un recordatorio de los tiempos precedentes al nuevo milenio. Viaja a cuando los pantalones anchos y las camisas de franela estaban de moda. Los tiempos que hicieron de MC Hammer y Nirvana íconos por su propio peso."},
	{"id": "Stingray.Big.Band", "n": "Big Band", "t": "Big Band", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Viaja a la era dorada de las grandes orquestas. Swing vibrante y glamour de los salones de baile."},
	{"id": "Stingray.Blues", "n": "Blues", "t": "Blues", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "¡80 años de auténtico Blues! Este canal incluye una variedad del viejo blues con sabor europeo."},
	{"id": "Stingray.Clasicos.del.Dance", "n": "Clásicos del Dance", "t": "Clásicos del Dance", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Revive la energía de la pista con los himnos dance que marcaron época."},
	{"id": "Stingray.Clasicos.del.Soul.y.el.Rhythm.and.Blues", "n": "Clásicos del Soul y el Rhythm and Blues", "t": "Clásicos del Soul y el Rhythm and Blues", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Sumérgete en la pasión y la intensidad del soul y el R&B clásico."},
	{"id": "Stingray.Clasicos.Indie", "n": "Clásicos Indie", "t": "Clásicos Indie", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Descubre los himnos alternativos que definieron la escena independiente."},
	{"id": "Stingray.Club.de.Baile", "n": "Club de Baile", "t": "Club de Baile", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Éxitos house, techno y trance para no parar de bailar."},
	{"id": "Stingray.Cocktail.Lounge", "n": "Cocktail Lounge", "t": "Cocktail Lounge", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Un canal de música lounge con un toque de nostalgia. Ideal para el oyente casual que busca algo tranquilo y familiar en letras y música."},
	{"id": "Stingray.Deep.Blues", "n": "Deep Blues", "t": "Deep Blues", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Explora las raíces más profundas del blues. Guitarras intensas y emociones crudas."},
	{"id": "Stingray.El.Salon.Chill", "n": "El Salón Chill", "t": "El Salón Chill", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Ven y relájate en El Salón Chill. Chillout Lounge. Los sonidos hip y groovy de la música electrónica, trip hop, acid jazz y down tempo. Deja este canal durante todo el día y la noche para crear un ambiente relajante, o sintoniza para acompañar una cena o un cóctel nocturno. Ritmos suaves con la música de los mejores clubs lounge de todo el mundo que definen la cultura hip lounge."},
	{"id": "Stingray.En.el.Spa", "n": "En el Spa", "t": "En el Spa", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Música instrumental electro-acústica relajante."},
	{"id": "Stingray.Estandares", "n": "Estándares", "t": "Estándares", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "La música de las grandes bandas y las estrellas antes del Rock & Roll."},
	{"id": "Stingray.Euro.Hits", "n": "Euro Hits", "t": "Euro Hits", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Disfruta los éxitos más recientes del panorama musical europeo."},
	{"id": "Stingray.Exitos.de.Brasil", "n": "Éxitos de Brasil", "t": "Éxitos de Brasil", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Siente la alegría y el ritmo de Brasil con los éxitos más representativos."},
	{"id": "Stingray.Exitos.de.España", "n": "Éxitos de España", "t": "Éxitos de España", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Los mejores éxitos musicales de España."},
	{"id": "Stingray.Exitos.de.Italia", "n": "Éxitos de Italia", "t": "Éxitos de Italia", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Disfruta de las canciones que dominan las listas italianas."},
	{"id": "Stingray.Exitos.de.la.Musica.Regional", "n": "Éxitos de la Música Regional", "t": "Éxitos de la Música Regional", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Lo mejor de la música de Mariachi, vernácula, ranchera y tradicional de México."},
	{"id": "Stingray.Exitos.de.las.Americas", "n": "Éxitos de las Américas", "t": "Éxitos de las Américas", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Un recorrido musical por el continente americano con sus éxitos más destacados."},
	{"id": "Stingray.Exitos.de.Salsa.y.Merengue", "n": "Éxitos de Salsa y Merengue", "t": "Éxitos de Salsa y Merengue", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Baila toda la noche y transpórtate a las playas de Cuba y la República Dominicana."},
	{"id": "Stingray.Exitos.del.Momento", "n": "Éxitos del Momento", "t": "Éxitos del Momento", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Lo mejor de los artistas emergentes del pop latino."},
	{"id": "Stingray.Exitos.del.Reino.Unido", "n": "Éxitos del Reino Unido", "t": "Éxitos del Reino Unido", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Canciones inglesas que también ocupan un lugar privilegiado en las listas de éxitos del otro lado del charco."},
	{"id": "Stingray.Exitos.Recientes", "n": "Éxitos Recientes", "t": "Éxitos Recientes", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Obtén lo último y lo mejor de los éxitos del momento."},
	{"id": "Stingray.Exitos.Regional.Mexicano", "n": "Éxitos Regional Mexicano", "t": "Éxitos Regional Mexicano", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Lo mejor de una música con muchos estilos como Banda, Ranchero, Mariachi y Norteñas. Los artistas y canciones populares de primera y segunda generación. Los hispanos hacen de este el destino de un amplio rango de gustos a través de la frontera y del oeste de los Estados Unidos. Aquí hay grandes temas de Vicente Fernández, Marco Antonio Solís, Intocable y Los Tigres del Norte."},
	{"id": "Stingray.Exitos.Tropicales", "n": "Éxitos Tropicales", "t": "Éxitos Tropicales", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "El feeling veraniego de lo más actual de la Salsa, la Rumba y el Merengue."},
	{"id": "Stingray.Fiesta.Continua", "n": "Fiesta Continua", "t": "Fiesta Continua", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "No esperes al fin de semana, la fiesta está aquí todas las noches."},
	{"id": "Stingray.Fiesta.Maxima", "n": "Fiesta Máxima", "t": "Fiesta Máxima", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "La mejor música para que la fiesta no termine."},
	{"id": "Stingray.Flashback.70s", "n": "Flashback 70s", "t": "Flashback 70s", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Revive la explosiva música de la década de los 70."},
	{"id": "Stingray.Flashback.de.los.60s", "n": "Flashback de los 60s", "t": "Flashback de los 60s", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Una maquina del tiempo a los años 60 para sentirse muy 'groovy'."},
	{"id": "Stingray.Grandes.Exitos", "n": "Grandes Éxitos", "t": "Grandes Éxitos", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "La colección de los más grandes éxitos universales."},
	{"id": "Stingray.Groove.Disco.y.Funk", "n": "Groove: Disco y Funk", "t": "Groove: Disco y Funk", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Cargado de éxitos Disco y Funk que te pondrán a bailar."},
	{"id": "Stingray.Hard.Rock", "n": "Hard Rock", "t": "Hard Rock", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Esto está al máximo. Experimenta en su totalidad los sonidos estridentes de guitarra del Rock pesado. Desde los clásicos hasta los grupos que forman la escena actual. Siente la fuerza de bandas como Mastodon y Dark Tranquility junto con Lamb of God y Black Dahlia Murder. Es posible que haya contenido explícito. Se recomienda discreción."},
	{"id": "Stingray.Himnos.del.Rock", "n": "Himnos del Rock", "t": "Himnos del Rock", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Sube el volumen con los himnos que definieron generaciones."},
	{"id": "Stingray.Holiday.Hits", "n": "Holiday Hits", "t": "Holiday Hits", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Esta música coincide con las estaciones y festividades: desde el Día de San Valentín, el Día Internacional de la Mujer y el Día de la Madre hasta Halloween y Navidad. Este canal ofrece las mejores canciones para todas las ocasiones."},
	{"id": "Stingray.Jammin.Reggae", "n": "Jammin' Reggae", "t": "Jammin' Reggae", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Raíces y ramificaciones de diversos estilos de reggae de la isla."},
	{"id": "Stingray.Jazz.Latino", "n": "Jazz Latino", "t": "Jazz Latino", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Recopilando lo mejor del Jazz latino, la bossa nova y el jazz afro-cubano siempre con un toque de improvisación."},
	{"id": "Stingray.Jazz.Moderno", "n": "Jazz Moderno", "t": "Jazz Moderno", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Un espacio para oír el mundo actual del Jazz."},
	{"id": "Stingray.Las.Mujeres.en.la.Musica", "n": "Las Mujeres en la Música", "t": "Las Mujeres en la Música", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Celebra a las mujeres que han sabido romper barreras, sobresalir e ir más allá de lo esperado. Escucha sus mayores éxitos incluyendo todos los géneros, épocas y estilos de vida."},
	{"id": "Stingray.Latin.Lounge", "n": "Latin Lounge", "t": "Latin Lounge", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Sonidos sofisticados y ambiente relajado para celebrar los placeres de la vida."},
	{"id": "Stingray.Maestros.del.Clasico", "n": "Maestros del Clásico", "t": "Maestros del Clásico", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Lo sofisticado, lo estimulante y arrebatador. Maestros del Clásico te trae conciertos, sinfonías y música de Ballet desde 1760 hasta ahora. Desde Bach hasta Bartok y Stravinsky, con énfasis en Haydn, Mozart, Beethoven, Schubert, Schumann, Brahms, Dvorak y otros."},
	{"id": "Stingray.Maestros.del.Jazz", "n": "Maestros del Jazz", "t": "Maestros del Jazz", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "La contribución de los Estados Unidos a la música moderna. Los maestros del Jazz que dieron forma a este fantástico género musical. Desde Ellington y Gillespie a Miles Davis, MJQ y cantantes populares como Billie Holiday, Ella Fitzgerald y Frank Sinatra. Estos son los íconos pioneros del Jazz."},
	{"id": "Stingray.Mariachi.y.Ranchera", "n": "Mariachi y Ranchera", "t": "Mariachi y Ranchera", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Celebra la tradición mexicana con lo mejor del mariachi y la ranchera."},
	{"id": "Stingray.MPB.(Musica.Popular.Brasileña)", "n": "MPB (Música Popular Brasileña)", "t": "MPB (Música Popular Brasileña)", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Sonidos suaves procedentes de Brasil. El canal ofrece una mezcla sensual de \"Música Popular Brasilera\", con artistas que van de la bossa-nova de los años 60 a la actual generación de artistas \"Nueva MPB\". Sonidos acústicos y electrónicos, buenas letras y ritmos atemporales hacen de este canal el lugar perfecto para escapar de la realidad."},
	{"id": "Stingray.Musica.del.Mundo", "n": "Música del Mundo", "t": "Música del Mundo", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Explora sonidos y tradiciones de todos los rincones del planeta."},
	{"id": "Stingray.Musica.Ligera", "n": "Música Ligera", "t": "Música Ligera", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Melodías relajantes y alegres, ideal para música de ambiente."},
	{"id": "Stingray.New.Age", "n": "New Age", "t": "New Age", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Paisajes sonoros envolventes y atmósferas serenas para la relajación."},
	{"id": "Stingray.Opera.Plus", "n": "Ópera Plus", "t": "Ópera Plus", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "La música Coral y de Ópera más conocida de los siglos XVIII y XIX, así como los recitales de los mejores intérpretes."},
	{"id": "Stingray.Pop.Adulto", "n": "Pop Adulto", "t": "Pop Adulto", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Desde éxitos recientes hasta legendarias canciones favoritas e imperecederas."},
	{"id": "Stingray.Popcorn", "n": "Popcorn", "t": "Popcorn", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Transpórtate al cine, a esa experiencia de disfrutar solamente los éxitos de las bandas sonoras. Con los éxitos de Hollywood y los clásicos de la pantalla grande, este canal está hecho para cinéfilos. Es un canal de música continua de las bandas sonoras."},
	{"id": "Stingray.Popular.Classical", "n": "Popular Classical", "t": "Popular Classical", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "La música clásica más amada en el mundo: el \"Para Elisa\" de Beethoven, la Apertura 1812 de Tchaikovsky, los valses de Strauss... La mejor música  de los últimos 200 años en un solo lugar. Siempre ha habido música \"popular\", y estos clásicos han sobrepasado la prueba del tiempo."},
	{"id": "Stingray.Reggaeton", "n": "Reggaetón", "t": "Reggaetón", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Toda la potencia de los sonidos y ritmos del Reggaetón urbano. El sonido latino que unió el hip hop con el reggae, hoy en día un sonido urbano global."},
	{"id": "Stingray.Retro.Latino", "n": "Retro Latino", "t": "Retro Latino", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Disfruta de lo mejor de las grandes estrellas de ayer."},
	{"id": "Stingray.Rock.Clasico", "n": "Rock Clásico", "t": "Rock Clásico", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Rock clásico de finales de los años 60 a los 80."},
	{"id": "Stingray.Rock.de.Brasil", "n": "Rock de Brasil", "t": "Rock de Brasil", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Este canal presenta lo mejor de la siempre floreciente escena musical de Rock Brasilero. El rock está vivo y en todas sus formas. Durante casi 30 años, el rock nacional ha sido la elección preferida de la juventud de Brasil. Este canal ofrece una poderosa mezcla de letras y un amplio espectro de influencias musicales que van del pop y la electrónica al punk y el rap."},
	{"id": "Stingray.Rock.en.Espanol", "n": "Rock en Español", "t": "Rock en Español", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "De hispanoamérica para el mundo el mejor Rock en español desde los clásicos, pasando por  los 90 hasta cruzar el siglo con los éxitos del momento.  Permite que este canal te lleve a tu propio mundo y disfruta la esencia del rock en español."},
	{"id": "Stingray.Romance.Latino", "n": "Romance Latino", "t": "Romance Latino", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Los temas y los cantantes que han hecho enamorarse a varias generaciones. Romance Latino es el canal perfecto para disfrutar durante una tarde romántica o simplemente cuando tengas ganas de recordar."},
	{"id": "Stingray.Rompepistas", "n": "Rompepistas", "t": "Rompepistas", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "¿No puedes ir a las discotecas? ¡Nosotros te las traemos! Sin parar, 24 horas al día, los mejores temas dance. Una recopilación de esa energía y entusiasmo de temas presentes en las pistas de baile alrededor de Europa."},
	{"id": "Stingray.Samba.y.Pagode", "n": "Samba y Pagode", "t": "Samba y Pagode", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Haz tu fiesta Brasileña al ritmo de la Samba y el Pagode."},
	{"id": "Stingray.Sesiones.Dancehall", "n": "Sesiones Dancehall", "t": "Sesiones Dancehall", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Durante los comienzos de los años ochenta, cuando los DJs eran los reyes y los cantantes eran los príncipes, la música dancehall arrasó en Jamaica y luego en todo el mundo. Para el público estadounidense, esta es la época dorada de la música jamaiquina. De Yellowman y Barrington Levy a Shabba Ranks y Vybz Kartel, adéntrate en la cultura vibrante de las sesiones Dancehall."},
	{"id": "Stingray.Silk.(Canciones.de.Amor)", "n": "Silk (Canciones de Amor)", "t": "Silk (Canciones de Amor)", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "¡A quién le importan las baladas, aquí están las canciones de amor! Casi todas las canciones populares que se han escrito, han sido sobre el amor. Aquí hay una selección de temas sin parar, lo más moderno entre los lamentos de hoy en día."},
	{"id": "Stingray.Solo.90s", "n": "Sólo 90s", "t": "Sólo 90s", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Combinación de R, Rock y Dance, con énfasis en el Pop y música alternativa de la década de los 90."},
	{"id": "Stingray.Solo.para.Peques", "n": "Solo para Peques", "t": "Solo para Peques", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Música instrumental y canciones en español para niños."},
	{"id": "Stingray.Solo.Rock", "n": "Sólo Rock", "t": "Sólo Rock", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Gran Rock, desde los años 80 hasta la actualidad."},
	{"id": "Stingray.Tango", "n": "Tango", "t": "Tango", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Nacido como una mezcla entre el ritmo incesante de los tambores africanos y la música de los primeros colonizadores españoles. Su nombre proviene del término “tangere” que en latín significa (tocar). El tango ha llegado al siglo 21 como uno de los estilos de música más aclamados. Aún más, se ha convertido en una cultura, en un estilo de vida. Este canal te entrega en tu hogar la sensualidad de esta música."},
	{"id": "Stingray.Todo.de.los.80s", "n": "Todo de los 80s", "t": "Todo de los 80s", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "La mejor música Pop de la década de los 80."},
	{"id": "Stingray.Viejitas.pero.Buenisimas", "n": "Viejitas pero Buenísimas", "t": "Viejitas pero Buenísimas", "g": "Stingray Music", "i": "https://music.stingray.com/themes/custom/music/images/Stingray-Music-MetaImage-en.png", "d": "Los diners, las tiendas de malteadas, los auto cinemas, los bailes sock-hop... Si los recuerdas, te encantarán las 'Viejitas pero Buenísimas'. No gastes en la rockola, esta selección de rolas va por nosotros. Revive los días que vieron nacer el Rock & Roll con la mejor música de los años 50 y 60: Elvis Presley, Buddy Holly, Chuck Berry, Fats Domino, los Beatles, los Beach Boys y mucho más."},
	# Radios y Música
    {"id": "Radios.y.Musica.50.Internacional", "n": "50 Internacional", "t": "50 Internacional", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "La década que dio vida al rock & roll y ritmos contagiosos."},
    {"id": "Radios.y.Musica.60.Internacional", "n": "60 Internacional", "t": "60 Internacional", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Un viaje a los años 60 con melodías que cambiaron la historia."},
    {"id": "Radios.y.Musica.70.Internacional", "n": "70 Internacional", "t": "70 Internacional", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Rock clásico, disco y funk de los años 70."},
    {"id": "Radios.y.Musica.80.90.Internacional", "n": "80/90 Internacional", "t": "80/90 Internacional", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Una combinación explosiva de los mejores éxitos de los 80 y 90."},
    {"id": "Radios.y.Musica.80.Internacional", "n": "80 Internacional", "t": "80 Internacional", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Revive la década dorada del pop y el rock internacional."},
    {"id": "Radios.y.Musica.90.Internacional", "n": "90 Internacional", "t": "90 Internacional", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "El sonido que marcó una generación: Pop, rock alternativo y dance de los 90."},
    {"id": "Radios.y.Musica.Axe", "n": "Axe", "t": "Axe", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Energía y ritmos festivos brasileños para celebrar sin parar."},
    {"id": "Radios.y.Musica.Blend", "n": "Blend", "t": "Blend", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Combinación equilibrada de distintos estilos y épocas."},
    {"id": "Radios.y.Musica.Bossa", "n": "Bossa", "t": "Bossa", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "La suavidad y sofisticación de la bossa nova."},
    {"id": "Radios.y.Musica.Chill.Africa", "n": "Chill Africa", "t": "Chill Africa", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Fusión de sonidos africanos y vibras chill con identidad propia."},
    {"id": "Radios.y.Musica.Chill.Out", "n": "Chill Out", "t": "Chill Out", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Ambientes relajantes y atmósferas envolventes para desconectar."},
    {"id": "Radios.y.Musica.Clasica", "n": "Clásica", "t": "Clásica", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Obras maestras de los grandes compositores de la historia."},
    {"id": "Radios.y.Musica.Classic.Cinema", "n": "Classic Cinema", "t": "Classic Cinema", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Un recorrido por las composiciones más emblemáticas del cine clásico."},
    {"id": "Radios.y.Musica.Disco", "n": "Disco", "t": "Disco", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Brillos y ritmos irresistibles de los clásicos de la era disco."},
    {"id": "Radios.y.Musica.Electronica", "n": "Electrónica", "t": "Electrónica", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Beats modernos y producción de vanguardia en la electrónica."},
    {"id": "Radios.y.Musica.Ellas", "n": "Ellas", "t": "Ellas", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Celebrando el talento y las voces más poderosas de la música femenina."},
    {"id": "Radios.y.Musica.Ellos", "n": "Ellos", "t": "Ellos", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Grandes artistas masculinos que han dejado huella."},
    {"id": "Radios.y.Musica.Grandes.del.Rock", "n": "Grandes del Rock", "t": "Grandes del Rock", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Las leyendas y bandas que hicieron del rock un movimiento eterno."},
    {"id": "Radios.y.Musica.Grandes.Voces", "n": "Grandes Voces", "t": "Grandes Voces", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Interpretaciones inolvidables de las voces más impactantes."},
    {"id": "Radios.y.Musica.Heavy.Metal", "n": "Heavy Metal", "t": "Heavy Metal", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Riffs intensos y pura adrenalina para los amantes del metal."},
    {"id": "Radios.y.Musica.Jazz", "n": "Jazz", "t": "Jazz", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Elegancia y tradición a través de los grandes estándares del jazz."},
    {"id": "Radios.y.Musica.Latinos", "n": "Latinos", "t": "Latinos", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Una celebración de los sonidos que hacen vibrar a Latinoamérica."},
    {"id": "Radios.y.Musica.Lentos", "n": "Lentos", "t": "Lentos", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Melodías suaves y envolventes para momentos tranquilos."},
    {"id": "Radios.y.Musica.Letras.y.Canciones", "n": "Letras y Canciones", "t": "Letras y Canciones", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Canciones con contenido y letras que dejan huella."},
    {"id": "Radios.y.Musica.Lounge", "n": "Lounge", "t": "Lounge", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Mezcla elegante de sonidos para ambientes sofisticados."},
    {"id": "Radios.y.Musica.MPB", "n": "MPB", "t": "MPB", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Lo mejor de la Música Popular Brasileña: Elegancia y poesía."},
    {"id": "Radios.y.Musica.New.Age", "n": "New Age", "t": "New Age", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Paisajes sonoros suaves para encontrar armonía interior."},
    {"id": "Radios.y.Musica.New.Party", "n": "New Party", "t": "New Party", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Hits actuales y energía alta para animar cualquier fiesta."},
    {"id": "Radios.y.Musica.New.Wave", "n": "New Wave", "t": "New Wave", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Sintetizadores y actitud del movimiento que redefinió el pop en los 80."},
    {"id": "Radios.y.Musica.Nuevos.Clasicos", "n": "Nuevos Clásicos", "t": "Nuevos Clásicos", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Éxitos de los últimos años que ya se sienten como imprescindibles."},
    {"id": "Radios.y.Musica.Opera", "n": "Ópera", "t": "Ópera", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Dramatismo y fuerza vocal en las grandes producciones operísticas."},
    {"id": "Radios.y.Musica.Opera.Romantica", "n": "Ópera Romántica", "t": "Ópera Romántica", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Las arias más apasionadas y emocionantes del repertorio."},
    {"id": "Radios.y.Musica.Peliculas", "n": "Películas", "t": "Películas", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Las canciones y bandas sonoras que dieron vida a historias en el cine."},
    {"id": "Radios.y.Musica.Power.Ballads", "n": "Power Ballads", "t": "Power Ballads", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Baladas intensas que combinan fuerza y emoción épica."},
    {"id": "Radios.y.Musica.Reggae", "n": "Reggae", "t": "Reggae", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Ritmos relajados y vibraciones positivas del sonido jamaicano."},
    {"id": "Radios.y.Musica.Reggaeton", "n": "Reggaeton", "t": "Reggaeton", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Ritmo urbano contagioso que domina las pistas globales."},
    {"id": "Radios.y.Musica.Reggaeton.Romantico", "n": "Reggaeton Romántico", "t": "Reggaeton Romántico", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "La fusión perfecta entre ritmo urbano y letras de amor."},
    {"id": "Radios.y.Musica.Retro.Mix", "n": "Retro Mix", "t": "Retro Mix", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Una mezcla irresistible de éxitos retro de distintas décadas."},
    {"id": "Radios.y.Musica.Rock.Alternativo", "n": "Rock Alternativo", "t": "Rock Alternativo", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Sonidos innovadores y propuestas que rompieron esquemas."},
    {"id": "Radios.y.Musica.Rock.Nacional", "n": "Rock Nacional", "t": "Rock Nacional", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "El sonido que define generaciones dentro del rock en nuestro idioma."},
    {"id": "Radios.y.Musica.Romanticas", "n": "Románticas", "t": "Románticas", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Canciones que hablan directo al corazón, ideales para dedicar."},
    {"id": "Radios.y.Musica.Salsa", "n": "Salsa", "t": "Salsa", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Sabor y ritmo caribeño con los clásicos y éxitos de la salsa."},
    {"id": "Radios.y.Musica.Smooth.Jazz", "n": "Smooth Jazz", "t": "Smooth Jazz", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Sonidos contemporáneos y relajados para ambientes sofisticados."},
    {"id": "Radios.y.Musica.Tango", "n": "Tango", "t": "Tango", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Pasión y elegancia rioplatense con los grandes clásicos del tango."},
    {"id": "Radios.y.Musica.Tango.Electronico", "n": "Tango Electrónico", "t": "Tango Electrónico", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "La tradición del tango fusionada con ritmos modernos."},
    {"id": "Radios.y.Musica.Teens", "n": "Teens", "t": "Teens", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "El sonido que marca tendencia entre las nuevas generaciones."},
    {"id": "Radios.y.Musica.Top.40", "n": "Top 40", "t": "Top 40", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Los 40 éxitos más sonados del momento reunidos en un solo canal."},
    {"id": "Radios.y.Musica.Top.Europa", "n": "Top Europa", "t": "Top Europa", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Descubre lo que está marcando el ritmo en las principales capitales europeas."},
    {"id": "Radios.y.Musica.Trendy", "n": "Trendy", "t": "Trendy", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Lo que está de moda ahora: Canciones virales y artistas nuevos."},
    {"id": "Radios.y.Musica.Vivo", "n": "Vivo", "t": "Vivo", "g": "Radios y Música", "i": "https://i.postimg.cc/RF7LHzy7/Ry-M.png", "d": "Presentaciones memorables y la magia irrepetible de la música en directo."},
	# Radios
    {"id": "Radio.10", "n": "Radio 10", "t": "Radio 10 AM 710", "g": "Radios", "i": "https://i.postimg.cc/rmvVrB6S/Radio-10.png", "d": "Actualidad, opinión y compañía informativa durante todo el día."},
    {"id": "Radio.Aspen", "n": "Radio Aspen", "t": "Radio Aspen FM 102.3", "g": "Radios", "i": "https://i.postimg.cc/NMWsH3hX/Radio-Aspen.png", "d": "Música selecta y sonido sofisticado para los amantes de los clásicos."},
    {"id": "Radio.Blue", "n": "Radio Blue", "t": "Radio Blue FM 100.7", "g": "Radios", "i": "https://i.postimg.cc/V6PLbh7J/Blue-mini.png", "d": "Clásicos del pop y rock internacional en una radio elegante y relajada. Grandes canciones de los 80, 90 y 2000 que crean la banda sonora perfecta para trabajar o relajarte."},
    {"id": "Radio.Cadena.3", "n": "Radio Cadena 3", "t": "Radio Cadena 3 AM 700", "g": "Radios", "i": "https://i.postimg.cc/DZtvX9Vv/Cadena-3.png", "d": "Noticias, deportes y entretenimiento de alcance federal."},
    {"id": "CNN.Radio.Argentina", "n": "CNN Radio Argentina", "t": "CNN Radio Argentina AM 950", "g": "Radios", "i": "https://i.imgur.com/CFRsZis.png", "d": "Noticias al instante, voces clave y análisis que te conectan con lo que importa hoy."},
	{"id": "Radio.Cosquin.Rock", "n": "Radio Cosquín Rock", "t": "Radio Cosquín Rock FM 95.5", "g": "Radios", "i": "https://i.postimg.cc/j5Bxm0hq/Cosquin-Rock.png", "d": "El rock argentino suena fuerte con clásicos y grabaciones en vivo."},
    {"id": "Radio.Del.Plata", "n": "Radio Del Plata", "t": "Radio Del Plata AM 1030", "g": "Radios", "i": "https://i.postimg.cc/MGjTbmRH/Radio-Del-Plata.png", "d": "Variedad musical, actualidad y deportes."},
    {"id": "Radio.Disney", "n": "Radio Disney", "t": "Radio Disney FM 94.3", "g": "Radios", "i": "https://i.postimg.cc/6pPqvm7Q/Radio-Disney.png", "d": "Los hits que todos aman y contenido para toda la familia."},
    {"id": "DSports.Radio", "n": "DSports Radio", "t": "DSports Radio FM 103.1", "g": "Radios", "i": "https://i.postimg.cc/sXtjhkFZ/DSports-Radio.png", "d": "La cobertura deportiva más completa con la voz de los expertos."},
    {"id": "Radio.France.Internationale", "n": "Radio France Internationale", "t": "Radio France Internationale", "g": "Radios", "i": "https://i.postimg.cc/6qk02LfR/RFI.png", "d": "Perspectiva global única con noticias y cultura desde Francia."},
    {"id": "Radio.La.Red", "n": "Radio La Red", "t": "Radio La Red AM 910", "g": "Radios", "i": "https://i.postimg.cc/1R7kshbP/Radio-La-Red.png", "d": "Fútbol, debate y las noticias del momento con opinión."},
    {"id": "Radio.Latina", "n": "Radio Latina", "t": "Radio Latina FM 101.1", "g": "Radios", "i": "https://i.postimg.cc/xdbCy3Hd/Radio-Latina.png", "d": "Éxitos en español y los ritmos latinos más populares."},
    {"id": "Radio.Los.40", "n": "Radio Los 40", "t": "Radio Los 40 FM 105.5", "g": "Radios", "i": "https://i.postimg.cc/CKf1HsD1/Radio-Los-40.png", "d": "Los hits que marcan tendencia y tus artistas favoritos."},
    {"id": "Radio.Mega", "n": "Radio Mega", "t": "Radio Mega FM 98.3", "g": "Radios", "i": "https://i.postimg.cc/Bv16cBDg/Radio-Mega.png", "d": "Puro rock nacional las 24 horas del día."},
    {"id": "Radio.Metro.Power.Hits", "n": "Radio Metro Power Hits", "t": "Radio Metro Power Hits FM 95.1", "g": "Radios", "i": "https://i.postimg.cc/TPD31xcm/MPH-mini.png", "d": "Éxitos globales del 2000 hasta hoy en una radio dinámica con más música y menos interrupciones. Pop, rock, latino y urbano en un mix nonstop que mantiene tu día siempre arriba."},
    {"id": "Radio.Nacional.Clasica", "n": "Radio Nacional Clásica", "t": "Radio Nacional Clásica FM 96.7", "g": "Radios", "i": "https://i.postimg.cc/QNRCn565/Radio-Nacional-Clasica.png", "d": "La mejor selección de música clásica y cultura sonora."},
    {"id": "Radio.Nacional.Folclorica", "n": "Radio Nacional Folclórica", "t": "Radio Nacional Folclórica FM 98.7", "g": "Radios", "i": "https://i.postimg.cc/zD9vPWd0/Radio-Nacional-Folclorica.png", "d": "Tradición y cultura argentina a través de sus raíces."},
    {"id": "Radio.Nacional.Rock", "n": "Radio Nacional Rock", "t": "Radio Nacional Rock FM 93.7", "g": "Radios", "i": "https://i.postimg.cc/Vs3vHM74/Radio-Nacional-Rock.png", "d": "Rock nacional e internacional con un toque alternativo."},
    {"id": "Radio.La.Popu", "n": "Radio La Popu", "t": "Radio La Popu FM 92.3", "g": "Radios", "i": "https://i.postimg.cc/MT7pgZ9S/Radio-La-Popu.png", "d": "Música popular que conecta con el sentimiento de la gente."},
    {"id": "Radio.Rivadavia", "n": "Radio Rivadavia", "t": "Radio Rivadavia AM 630", "g": "Radios", "i": "https://i.postimg.cc/y8Kd7KCN/Radio-Rivadavia.png", "d": "Una radio histórica con los periodistas más respetados del país."},
    {"id": "Radio.Rock.and.Pop", "n": "Radio Rock and Pop", "t": "Radio Rock and Pop FM 95.9", "g": "Radios", "i": "https://i.postimg.cc/fLcR1W8X/Radio-Rock-and-Pop.png", "d": "Todo el rock, el pop y la cultura musical alternativa."},
    {"id": "Pop.Radio", "n": "Pop Radio FM 101.5", "t": "Pop Radio FM 101.5", "g": "Radios", "i": "https://i.postimg.cc/s2HxhTTF/POP-mini.png", "d": "La radio del entretenimiento y los grandes éxitos. Humor, música y la compañía de las mejores voces de Buenos Aires."},
    {"id": "Radio.Con.Vos", "n": "Radio Con Vos FM 89.9", "t": "Radio Con Vos FM 89.9", "g": "Radios", "i": "https://i.postimg.cc/bvVrtmmh/Radio-Con-Vos-mini.png", "d": "Periodismo puro y análisis de la realidad. Información, opinión y actualidad con una mirada profunda durante todo el día."},
    {"id": "Radio.ADN.RAF", "n": "Radio ADN FM 97.9", "t": "Radio ADN FM 97.9", "g": "Radios", "i": "https://i.postimg.cc/Bv7bKmMr/ADN-mini.png", "d": "La voz informativa de Rafaela. Noticias al instante, móviles en vivo y el pulso de la ciudad y la región en la FM 97.9."},
    {"id": "Radio.LT28", "n": "Radio Rafaela LT28", "t": "Radio Rafaela LT28", "g": "Radios", "i": "https://i.postimg.cc/HxJx4bhF/Radio-Rafaela-Mini.png", "d": "Tradición y actualidad en el aire rafaelino. La histórica LT28 con la cobertura más completa de Rafaela y zona."},
    {"id": "Radio.Vida", "n": "Radio Vida", "t": "Radio Vida FM 97.9", "g": "Radios", "i": "https://i.ytimg.com/vi/dGQ25rVfUH4/maxresdefault.jpg", "d": "Compañía musical con los hits que suenan en todo momento."},
]

def clean_text(text):
    if not text: return ""
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace('"', "&quot;").replace("'", "&apos;")

def generar_epg():
    inicio_dinamico = (datetime.datetime.now() - datetime.timedelta(days=1)).replace(
        hour=0, minute=0, second=0, microsecond=0
    )
    lines = []
    lines.append('<?xml version="1.0" encoding="utf-8"?>')
    lines.append('<tv generator-info="EPG Generator">')

    for c in canales:
        nombre = clean_text(c["n"])
        lines.append(f'  <channel id="{c["id"]}">')
        lines.append(f'    <display-name>{nombre}</display-name>')
        lines.append('  </channel>')

    prog_rafaela = [
		{"s": "000000", "e": "000300", "t": "Himno nacional", "g": "Interés general", "d": "Himno nacional argentino", "i": "https://i.postimg.cc/m2nZCvHm/Himno.jpg"},
		{"s": "000300", "e": "003000", "t": "En síntesis", "g": "Noticias, Interés General", "d": "La información de último momento y lo que pasó durante la noche se complementa con tres resúmenes de noticias: una síntesis con los temas nacionales, una internacional y otra de deportes.", "i": "https://i.postimg.cc/W4B72y2C/Rafaela-Noticias.png"},
		{"s": "003000", "e": "010000", "t": "Somos país", "g": "Interés general", "d": "Resumen diario de noticias que reúne historias de cada localidad del país.", "i": "https://i.postimg.cc/qMFByP3m/Somos-Pais.jpg"},
		{"s": "010000", "e": "020000", "t": "Deporte y pasión", "g": "Deportivo", "d": "Un espacio que aborda toda la actualidad deportiva de Rafaela a través de los goles y las polémicas. Informamos sobre los equipos rafaelinos a nivel nacional y te traemos lo mejor del deporte, es pasión que una a las multitudes.", "i": "https://i.postimg.cc/NfnGm3HZ/Deporte-y-Pasion.jpg"},
		{"s": "020000", "e": "043000", "t": "Bien despiertos", "g": "Magazine", "d": "Un espacio que aborda diversas temáticas de relevancia en la actualidad a nivel regional y nacional. Compartimos análisis sobre política, economía, seguridad, deportes, cultura y negocios, además de debates en torno a problemas cotidianos.", "i": "https://i.postimg.cc/pTScqJJR/Bien-Despiertos.png"},
		{"s": "043000", "e": "053000", "t": "Deporte y pasión", "g": "Deportivo", "d": "Un espacio que aborda toda la actualidad deportiva de Rafaela a través de los goles y las polémicas. Informamos sobre los equipos rafaelinos a nivel nacional y te traemos lo mejor del deporte, es pasión que una a las multitudes.", "i": "https://i.postimg.cc/NfnGm3HZ/Deporte-y-Pasion.jpg"},
		{"s": "053000", "e": "060000", "t": "Planeta vinos", "g": "Cocina", "d": "Vero Martino y Diego Hernández te invitan a recorrer bodegas, ferias y eventos exclusivos de la vitivinicultura junto sus principales protagonistas.", "i": "https://i.postimg.cc/ncWVBymb/Planeta-Vinos.jpg"},
		{"s": "060000", "e": "063000", "t": "En síntesis", "g": "Noticias, Interés General", "d": "La información de último momento y lo que pasó durante la noche se complementa con tres resúmenes de noticias: una síntesis con los temas nacionales, una internacional y otra de deportes.", "i": "https://i.postimg.cc/W4B72y2C/Rafaela-Noticias.png"},
		{"s": "063000", "e": "070000", "t": "Somos país", "g": "Interés general", "d": "Resumen diario de noticias que reúne historias de cada localidad del país.", "i": "https://i.postimg.cc/qMFByP3m/Somos-Pais.jpg"},
		{"s": "070000", "e": "093000", "t": "Bien despiertos", "g": "Magazine", "d": "Un espacio que aborda diversas temáticas de relevancia en la actualidad a nivel regional y nacional. Compartimos análisis sobre política, economía, seguridad, deportes, cultura y negocios, además de debates en torno a problemas cotidianos.", "i": "https://i.postimg.cc/pTScqJJR/Bien-Despiertos.png"},
		{"s": "093000", "e": "120000", "t": "Arriba la mañana", "g": "Periodístico, Magazine", "d": "Un espacio matutino y entretenido donde abordamos toda la actualidad y las noticias más relevantes. Un gran equipo nos informa a través de móviles en la ciudad, con responsables en las principales ciudades de la provincia.", "i": "https://i.postimg.cc/hPY4TkdZ/Arriba-la-manana.jpg"},
		{"s": "120000", "e": "131500", "t": "Rafaela Noticias - Primera edición", "g": "Noticias, Interés general", "d": "Un programa que aborda los hechos más destacados de la agenda de noticias nacional e internacional. A través del trabajo de periodistas, reporteros y expertos, el público podrá informarse al completo sobre la realidad.", "i": "https://i.postimg.cc/QxzN127r/Rafaela-Noticias.jpg"},
		{"s": "131500", "e": "143000", "t": "Deporte y pasión", "g": "Deportivo", "d": "Un espacio que aborda toda la actualidad deportiva de Rafaela a través de los goles y las polémicas. Informamos sobre los equipos rafaelinos a nivel nacional y te traemos lo mejor del deporte, es pasión que una a las multitudes.", "i": "https://i.postimg.cc/NfnGm3HZ/Deporte-y-Pasion.jpg"},
		{"s": "143000", "e": "153000", "t": "Vida y milagro", "g": "Interés general", "d": "Toda la actualidad social, cultural e institucional es reseñada en este espacio que transmite el acontecer de los habitantes de la ciudad de Rafaela, desde una perspectiva amena, diferente e innovadora.", "i": "https://i.postimg.cc/9FkXZ69H/Vida-y-milagro.png"},
		{"s": "153000", "e": "180000", "t": "Bien despiertos", "g": "Magazine", "d": "Un espacio que aborda diversas temáticas de relevancia en la actualidad a nivel regional y nacional. Compartimos análisis sobre política, economía, seguridad, deportes, cultura y negocios, además de debates en torno a problemas cotidianos.", "i": "https://i.postimg.cc/pTScqJJR/Bien-Despiertos.png"},
		{"s": "180000", "e": "194500", "t": "Nunca es tarde", "g": "Magazine", "d": "Programa local con temas de actualidad, entretenimientos y música.", "i": "https://i.postimg.cc/HsNWXqMG/Nunca-es-tarde.jpg"},
		{"s": "194500", "e": "210000", "t": "Rafaela Noticias - Segunda edición", "g": "Noticias, Interés general", "d": "Un programa que aborda los hechos más destacados de la agenda de noticias nacional e internacional. A través del trabajo de periodistas, reporteros y expertos, el público podrá informarse al completo sobre la realidad.", "i": "https://i.postimg.cc/QxzN127r/Rafaela-Noticias.jpg"},
		{"s": "210000", "e": "220000", "t": "Vida y milagro", "g": "Interés general", "d": "Toda la actualidad social, cultural e institucional es reseñada en este espacio que transmite el acontecer de los habitantes de la ciudad de Rafaela, desde una perspectiva amena, diferente e innovadora.", "i": "https://i.postimg.cc/9FkXZ69H/Vida-y-milagro.png"},
		{"s": "220000", "e": "223000", "t": "Agenda Carburando", "g": "Automovilismo", "d": "El resumen de lo más importante del deporte motor del fin de semana.", "i": "https://i.postimg.cc/YqP2Y5WZ/Carburando.jpg"},
		{"s": "223000", "e": "233000", "t": "Agregándole valor a la vida", "g": "Magazine", "d": "Un ciclo que presenta historias interesantes e inspiradoras de las cuales podemos aprender. Diversos emprendedores cuentan sus experiencias, éxitos y fracasos y nos contagian de ilusión.", "i": "https://i.postimg.cc/NfGv6mQZ/Valor-Vida.jpg"},
		{"s": "233000", "e": "000000", "t": "Planeta vinos", "g": "Cocina", "d": "Vero Martino y Diego Hernández te invitan a recorrer bodegas, ferias y eventos exclusivos de la vitivinicultura junto sus principales protagonistas.", "i": "https://i.postimg.cc/ncWVBymb/Planeta-Vinos.jpg"}
    ]

    for d in range(3):
        for p in prog_rafaela:
            inicio_dia = inicio_dinamico + datetime.timedelta(days=d)

            st = inicio_dia.replace(
                hour=int(p["s"][:2]), minute=int(p["s"][2:4]), second=int(p["s"][4:])
            )
            et = inicio_dia.replace(
                hour=int(p["e"][:2]), minute=int(p["e"][2:4]), second=int(p["e"][4:])
            )

            if et <= st:
                et += datetime.timedelta(days=1)

            s_str = st.strftime("%Y%m%d%H%M%S -0300")
            e_str = et.strftime("%Y%m%d%H%M%S -0300")
    
            lines.append(f'  <programme start="{s_str}" stop="{e_str}" channel="Rafaela.Noticias">')
            lines.append(f'    <title>{clean_text(p["t"])}</title>')
            lines.append(f'    <desc>{clean_text(p["d"])}</desc>')
            lines.append(f'    <icon src="{p["i"]}"/>')
            lines.append(f'    <category>{clean_text(p["g"])}</category>')
            lines.append(f'  </programme>')

    for c in canales:
        if "rafaela" in c["id"].lower():
            continue
            
        for d in range(7):
            for h in range(0, 24, 4):
                start_dt = inicio_dinamico + datetime.timedelta(days=d, hours=h)
                stop_dt = start_dt + datetime.timedelta(hours=4)
                s = start_dt.strftime("%Y%m%d%H%M%S -0300")
                e = stop_dt.strftime("%Y%m%d%H%M%S -0300")
                lines.append(f'  <programme start="{s}" stop="{e}" channel="{c["id"]}">')
                lines.append(f'    <title>{clean_text(c["t"])}</title>')
                lines.append(f'    <desc>{clean_text(c["d"])}</desc>')
                lines.append(f'    <icon src="{c.get("i")}"/>')
                lines.append(f'    <category>{clean_text(c["g"])}</category>')
                lines.append(f'  </programme>')

    lines.append('</tv>')
    
    with open("data_v9.xml", "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print("EPG generado: data_v9.xml")

if __name__ == "__main__":
    generar_epg()
