name: Update
on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run Test Script
        run: python test_musicbox.py

      - name: Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Bot"
          git add test_musicbox.xml
          if git diff --staged --quiet; then
            echo "No hay cambios para subir"
          else
            git commit -m "test musicbox $(date +'%Y-%m-%d %H:%M')"
            git push
          fi
